LOGBOOK.LS     Robot Name ROBOT 10-FEB-20 18:04     

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Operation        
========================================
FILE 'MC:\IOSTATUS.CM' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\HTTPKCL.VR' is saved         
10-FEB-20 18:04 :58
========================================
FILE 'MC:\HTCOLREC.VR' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\HOME_IO.TP' is saved         
10-FEB-20 18:04 :58
========================================
FILE 'MC:\HIST.LS' is saved            
10-FEB-20 18:04 :58
========================================
FILE 'MC:\HIGHM61C.VR' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\HI03M61C.VR' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\GREENLED.GIF' is saved       
10-FEB-20 18:04 :58
========================================
FILE 'MC:\GETDATA.TP' is saved         
10-FEB-20 18:04 :58
========================================
FILE 'MC:\GEMDATA.VR' is saved         
10-FEB-20 18:04 :58
========================================
FILE 'MC:\FTPLOG.DG' is saved          
10-FEB-20 18:04 :58
========================================
FILE 'MC:\FRAMEVAR.VR' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\ETHERNET.DG' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\ERRSYS.LS' is saved          
10-FEB-20 18:04 :58
========================================
FILE 'MDS8:\ERRSYS.LS' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\ERRPWD.LS' is saved          
10-FEB-20 18:04 :58
========================================
FILE 'MDS7:\ERRPWD.LS' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\ERRMOT.LS' is saved          
10-FEB-20 18:04 :58
========================================
FILE 'MDS6:\ERRMOT.LS' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\ERRHIST.LS' is saved         
10-FEB-20 18:04 :58
========================================
FILE 'MDS5:\ERRHIST.LS' is saved       
10-FEB-20 18:04 :58
========================================
FILE 'MC:\ERREXT.LS' is saved          
10-FEB-20 18:04 :58
========================================
FILE 'MDS4:\ERREXT.LS' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\ERRCURR.LS' is saved         
10-FEB-20 18:04 :58
========================================
FILE 'MDS3:\ERRCURR.LS' is saved       
10-FEB-20 18:04 :58
========================================
FILE 'MC:\ERRCOMM.LS' is saved         
10-FEB-20 18:04 :58
========================================
FILE 'MDS2:\ERRCOMM.LS' is saved       
10-FEB-20 18:04 :58
========================================
FILE 'MC:\ERRAPP.LS' is saved          
10-FEB-20 18:04 :58
========================================
FILE 'MDS1:\ERRAPP.LS' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\ERRALL.LS' is saved          
10-FEB-20 18:04 :58
========================================
FILE 'MDS0:\ERRALL.LS' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\ERRACT.LS' is saved          
10-FEB-20 18:04 :58
========================================
FILE 'MDS9:\ERRACT.LS' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DIOCFGSV.IO' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DF_MOTN0.DF' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DF_LOGI6.DF' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DF_LOGI5.DF' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DF_LOGI4.DF' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DF_LOGI3.DF' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DF_LOGI2.DF' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DF_LOGI1.DF' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DCSVRFY3.DG' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DCSVRFY2.DG' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DCSVRFY1.DG' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DCSVRFY.DG' is saved         
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DCSDIFF.DG' is saved         
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DCSCHGD3.DG' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DCSCHGD2.DG' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DCSCHGD1.DG' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\DARKLED.GIF' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\CONSLOG.DG' is saved         
10-FEB-20 18:04 :58
========================================
FILE 'MC:\CELLIO.SV' is saved          
10-FEB-20 18:04 :58
========================================
FILE 'MC:\BACKDATE.DT' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\ATERRJOB.VR' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\AMBERLED.GIF' is saved       
10-FEB-20 18:04 :58
========================================
FILE 'MC:\-BCKEDT-.TP' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\-BCKED9-.TP' is saved        
10-FEB-20 18:04 :58
========================================
FILE 'MC:\-BCKED8-.TP' is saved        
10-FEB-20 18:04 :58
========================================
SHIFT,FWD is pressed                   
10-FEB-20 18:04 :52
========================================
'   YES' is selected in ' The cursor i
s on a different' window              
10-FEB-20 18:04 :50
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 33   \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
     ________________________________34 
  25:|The cursor is on a different  |   
  26:|line from where the program   |   
  27:|PAUSED [33].                  |   
  28:|Are you sure you want to run  |   
  29:|from this line ?              |   
  30:|                              |   
  31:|   \\\\YES\\\\       NO       |   
\\32:|______________________________|   
  33:L  P[14] 100mm/sec CNT100          
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,FWD is pressed                   
10-FEB-20 18:04 :50
========================================
R E S E T                              
                                       
                              00000000 
10-FEB-20 18:04 :46
========================================
RESET is pressed                       
10-FEB-20 18:04 :46
========================================
BWD is pressed                         
10-FEB-20 18:04 :42
========================================
FWD is pressed                         
10-FEB-20 18:04 :42
========================================
Single step ON                         
10-FEB-20 18:04 :40
========================================
STEP is pressed                        
10-FEB-20 18:04 :40
========================================
SHIFT,FWD is pressed                   
10-FEB-20 18:04 :32
========================================
'4 L P[] 100mm/sec CNT100' is selected 
in 'Default Motion' menu               
10-FEB-20 18:04 :22
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  33/33 
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 2000mm/sec FINE           
  30:L  P[2] 2000mm/sec CNT0            
  31:J  P[1] 100% CNT100                
  32:J  P[5] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 18:04 :18
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  33/33 
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 2000mm/sec FINE           
  30:L  P[2] 2000mm/sec CNT0            
  31:J  P[1] 100% CNT100                
  32:J  P[5] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
 is entered                            
10-FEB-20 18:04 :12
--Screen image--------------------------
                                        
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\WORLD\\30\%
\1\Upper\Case\\                         
 2 Lower Case                           
 3 Punctuation                          
 4 Options               --Insert--     
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  32/33 
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 2000mm/sec FINE           
  30:L  P[2] 2000mm/sec CNT0            
  31:J  P[1] 100% CNT100                
  32:J  P[5:                 ] 100%     
    :  CNT100                           
                                        
   ABCDEF GHIJKL  MNOPQR STUVWX  YZ_@*. 
========================================
ENTER is pressed                       
10-FEB-20 18:04 :12
========================================
5 is entered                           
10-FEB-20 18:04 :12
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  32/33 
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 2000mm/sec FINE           
  30:L  P[2] 2000mm/sec CNT0            
  31:J  P[1] 100% CNT100                
  32:J @P[14] 1] 100% CNT100            
[End]                                   
Old Value: 14                           
                        [CHOICE]POSITION
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
10-FEB-20 18:04 :06
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  32/32 
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 2000mm/sec FINE           
  30:L  P[2] 2000mm/sec CNT0            
  31:J  P[1] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 18:04 :04
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  32/32 
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 2000mm/sec FINE           
  30:L  P[2] 2000mm/sec CNT0            
  31:J  P[1] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
1 is entered                           
10-FEB-20 18:03 :58
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  31/32 
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 2000mm/sec FINE           
  30:L  P[2] 2000mm/sec CNT0            
  31:J @P[14] 1] 100% CNT100            
[End]                                   
Old Value: 14                           
                        [CHOICE]POSITION
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
10-FEB-20 18:03 :54
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3 L P[] 100mm/sec FINE                  
4\L\P[]\100mm/sec\CNT100\\\\\\\\\\\\\\\ 
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  31/31 
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 2000mm/sec FINE           
  30:L  P[2] 2000mm/sec CNT0            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 18:03 :48
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  31/31 
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 2000mm/sec FINE           
  30:L  P[2] 2000mm/sec CNT0            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
2000 is entered                        
10-FEB-20 18:03 :24
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  30/31 
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 2000mm/sec FINE           
  30:L  P[2] 100mmm/sec CNT0            
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
ENTER is pressed                       
10-FEB-20 18:03 :18
========================================
0 is entered                           
10-FEB-20 18:03 :16
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  30/31 
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 2000mm/sec FINE           
  30:L  P[2] 100mm/sec CNT100           
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2 is entered                           
10-FEB-20 18:03 :12
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  30/31 
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 2000mm/sec FINE           
  30:L @P[14] 1] 100mm/sec CNT100       
[End]                                   
Old Value: 14                           
                        [CHOICE]POSITION
========================================
'4 L P[] 100mm/sec CNT100' is selected 
in 'Default Motion' menu               
10-FEB-20 18:03 :08
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  30/30 
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 2000mm/sec FINE           
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 18:03 :06
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  30/30 
  21:L  P[10] 2000mm/sec CNT0           
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 2000mm/sec FINE           
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
2000 is entered                        
10-FEB-20 18:03 :02
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  29/30 
  21:L  P[10] 2000mm/sec CNT0           
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12] 100mmm/sec FINE           
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
 is entered                            
10-FEB-20 18:02 :58
--Screen image--------------------------
                                        
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\WORLD\\30\%
\1\Upper\Case\\                         
 2 Lower Case                           
 3 Punctuation                          
 4 Options               --Insert--     
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  29/30 
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L  P[12:                 ]         
    :  100mm/sec FINE                   
                                        
   ABCDEF GHIJKL  MNOPQR STUVWX  YZ_@*. 
========================================
ENTER is pressed                       
10-FEB-20 18:02 :56
========================================
12 is entered                          
10-FEB-20 18:02 :56
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  29/30 
  21:L  P[10] 2000mm/sec CNT0           
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
  29:L @P[14] 1] 100mm/sec FINE         
[End]                                   
Old Value: 14                           
                        [CHOICE]POSITION
========================================
SHIFT,F1( POINT  ) is pressed          
10-FEB-20 18:02 :26
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  29/29 
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
  28:L @P[13] 2000mm/sec FINE           
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,F5(TOUCHUP>) is pressed          
10-FEB-20 18:02 :20
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  28/29 
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L  P[12] 2000mm/sec CNT0           
\\28:L  P[13] 2000mm/sec FINE           
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,-Z(J3) is pressed                
10-FEB-20 18:02 :18
========================================
SHIFT,-Z(J3) is pressed                
10-FEB-20 18:02 :16
========================================
SHIFT,-Z(J3) is pressed                
10-FEB-20 18:02 :06
========================================
2000 is entered                        
10-FEB-20 18:01 :56
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  28/29 
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L @P[12] 2000mm/sec CNT0           
  28:L @P[13] 100mmm/sec FINE           
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'3 L P[] 100mm/sec FINE' is selected in
 'Default Motion' menu                 
10-FEB-20 18:01 :46
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3 L P[] 100mm/sec FINE                  
4\L\P[]\100mm/sec\CNT100\\\\\\\\\\\\\\\ 
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  28/28 
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L @P[12] 2000mm/sec CNT0           
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 18:01 :42
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  28/28 
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L @P[12] 2000mm/sec CNT0           
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
ENTER is pressed                       
10-FEB-20 18:01 :42
========================================
0 is entered                           
10-FEB-20 18:01 :40
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  27/28 
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L @P[12] 2000mm/sec CNT100         
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2000 is entered                        
10-FEB-20 18:01 :38
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  27/28 
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
  27:L @P[12] 100mmm/sec CNT100         
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'4 L P[] 100mm/sec CNT100' is selected 
in 'Default Motion' menu               
10-FEB-20 18:01 :30
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  27/27 
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 18:01 :26
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  27/27 
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L  P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,-Z(J3) is pressed                
10-FEB-20 18:01 :14
========================================
SHIFT,+Z(J3) is pressed                
10-FEB-20 18:01 :12
========================================
SHIFT,-Z(J3) is pressed                
10-FEB-20 18:01 :06
========================================
SHIFT,+X(J1) is pressed                
10-FEB-20 18:01 :00
========================================
SHIFT,+Y(J2) is pressed                
10-FEB-20 18:00 :52
========================================
SHIFT,-X(J1) is pressed                
10-FEB-20 18:00 :42
========================================
SHIFT,-Y(J2) is pressed                
10-FEB-20 18:00 :40
========================================
SHIFT,-X(J1) is pressed                
10-FEB-20 18:00 :36
========================================
SHIFT,-X(J1) is pressed                
10-FEB-20 18:00 :34
========================================
SHIFT,+X(J1) is pressed                
10-FEB-20 18:00 :32
========================================
SHIFT,FWD is pressed                   
10-FEB-20 17:56 :42
========================================
 is entered                            
10-FEB-20 17:56 :34
--Screen image--------------------------
                                        
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\WORLD\\30\%
\1\Upper\Case\\                         
 2 Lower Case                           
 3 Punctuation                          
 4 Options               --Insert--     
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  26/27 
  22:L @P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J  P[2:                 ] 100%     
    :  CNT100                           
                                        
   ABCDEF GHIJKL  MNOPQR STUVWX  YZ_@*. 
========================================
ENTER is pressed                       
10-FEB-20 17:56 :32
========================================
2 is entered                           
10-FEB-20 17:56 :32
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  26/27 
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
  26:J @P[12] 1] 100% CNT100            
[End]                                   
Old Value: 12                           
                        [CHOICE]POSITION
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
10-FEB-20 17:56 :28
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  26/26 
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:56 :26
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  26/26 
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J  P[1] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
1 is entered                           
10-FEB-20 17:56 :24
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  25/26 
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
  25:J @P[12] 1] 100% CNT100            
[End]                                   
Old Value: 12                           
                        [CHOICE]POSITION
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
10-FEB-20 17:56 :18
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3 L P[] 100mm/sec FINE                  
4\L\P[]\100mm/sec\CNT100\\\\\\\\\\\\\\\ 
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  25/25 
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:56 :16
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  25/25 
  16:L  P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT0            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
ENTER is pressed                       
10-FEB-20 17:56 :00
========================================
0 is entered                           
10-FEB-20 17:56 :00
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  24/25 
  16:L  P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 2000mm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2000 is entered                        
10-FEB-20 17:55 :58
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  24/25 
  16:L  P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L  P[5] 100mmm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
5 is entered                           
10-FEB-20 17:55 :50
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  24/25 
  16:L  P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
  24:L @P[12] 1] 100mm/sec CNT100       
[End]                                   
Old Value: 12                           
                        [CHOICE]POSITION
========================================
'4 L P[] 100mm/sec CNT100' is selected 
in 'Default Motion' menu               
10-FEB-20 17:55 :46
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  24/24 
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:55 :42
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  24/24 
  15:L  P[8] 2000mm/sec CNT0            
  16:L  P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
  23:L  P[10] 2000mm/sec FINE           
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
10 is entered                          
10-FEB-20 17:55 :18
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  23/24 
  15:L  P[8] 2000mm/sec CNT0            
  16:L  P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
  23:L @P[12] 2] 2000mm/sec FINE        
[End]                                   
Old Value: 12                           
                        [CHOICE]POSITION
========================================
2000 is entered                        
10-FEB-20 17:55 :12
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  23/24 
  15:L  P[8] 2000mm/sec CNT0            
  16:L  P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
  23:L @P[12] 100mmm/sec FINE           
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'3 L P[] 100mm/sec FINE' is selected in
 'Default Motion' menu                 
10-FEB-20 17:55 :06
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  23/23 
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:55 :04
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  23/23 
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L  P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 2000mm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
2000 is entered                        
10-FEB-20 17:55 :00
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  21/23 
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L  P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 100mmm/sec CNT0           
  22:L @P[11] 2000mm/sec FINE           
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2000 is entered                        
10-FEB-20 17:54 :54
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  22/23 
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L  P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 100mm/sec CNT0            
  22:L @P[11] 100mmm/sec FINE           
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'3 L P[] 100mm/sec FINE' is selected in
 'Default Motion' menu                 
10-FEB-20 17:54 :46
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3 L P[] 100mm/sec FINE                  
4\L\P[]\100mm/sec\CNT100\\\\\\\\\\\\\\\ 
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  22/22 
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 100mm/sec CNT0            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:54 :42
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  22/22 
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L  P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L  P[10] 100mm/sec CNT0            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,+Z(J3) is pressed                
10-FEB-20 17:54 :34
========================================
SHIFT,-Z(J3) is pressed                
10-FEB-20 17:54 :32
========================================
ENTER is pressed                       
10-FEB-20 17:54 :20
========================================
0 is entered                           
10-FEB-20 17:54 :20
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  21/22 
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L  P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
  21:L @P[10] 100mm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'4 L P[] 100mm/sec CNT100' is selected 
in 'Default Motion' menu               
10-FEB-20 17:54 :10
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  21/21 
  16:L  P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:54 :08
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  21/21 
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L  P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J  P[5] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,-Z(J3) is pressed                
10-FEB-20 17:53 :50
========================================
SHIFT,+Y(J2) is pressed                
10-FEB-20 17:53 :42
========================================
SHIFT,-Y(J2) is pressed                
10-FEB-20 17:53 :42
========================================
SHIFT,-X(J1) is pressed                
10-FEB-20 17:53 :40
========================================
SHIFT,+X(J1) is pressed                
10-FEB-20 17:53 :36
========================================
SHIFT,FWD is pressed                   
10-FEB-20 17:53 :12
========================================
5 is entered                           
10-FEB-20 17:53 :04
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  20/21 
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J @P[10] 1] 100% CNT100            
[End]                                   
Old Value: 10                           
                        [CHOICE]POSITION
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
10-FEB-20 17:53 :00
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  20/20 
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:52 :58
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  20/20 
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
1 is entered                           
10-FEB-20 17:52 :54
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  19/20 
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J @P[10] 1] 100% CNT100            
[End]                                   
Old Value: 10                           
                        [CHOICE]POSITION
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
10-FEB-20 17:52 :50
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3 L P[] 100mm/sec FINE                  
4\L\P[]\100mm/sec\CNT100\\\\\\\\\\\\\\\ 
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  19/19 
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:52 :46
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  19/19 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
ENTER is pressed                       
10-FEB-20 17:52 :46
========================================
0 is entered                           
10-FEB-20 17:52 :44
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  18/19 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2000 is entered                        
10-FEB-20 17:52 :42
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  18/19 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 100mmm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2 is entered                           
10-FEB-20 17:52 :38
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  18/19 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L @P[10] 1] 100mm/sec CNT100       
[End]                                   
Old Value: 10                           
                        [CHOICE]POSITION
========================================
'4 L P[] 100mm/sec CNT100' is selected 
in 'Default Motion' menu               
10-FEB-20 17:52 :32
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  18/18 
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:52 :30
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  18/18 
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
ENTER is pressed                       
10-FEB-20 17:52 :24
========================================
ENTER is pressed                       
10-FEB-20 17:52 :24
========================================
2000 is entered                        
10-FEB-20 17:52 :24
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  17/18 
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 100mmm/sec FINE            
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
8 is entered                           
10-FEB-20 17:52 :16
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  17/18 
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L @P[10] 1] 100mm/sec FINE         
[End]                                   
Old Value: 10                           
                        [CHOICE]POSITION
========================================
'3 L P[] 100mm/sec FINE' is selected in
 'Default Motion' menu                 
10-FEB-20 17:52 :08
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  17/17 
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:52 :08
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  17/17 
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
ENTER is pressed                       
10-FEB-20 17:52 :06
========================================
ENTER is pressed                       
10-FEB-20 17:52 :04
========================================
2000 is entered                        
10-FEB-20 17:52 :04
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  16/17 
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 100mmm/sec FINE            
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'3 L P[] 100mm/sec FINE' is selected in
 'Default Motion' menu                 
10-FEB-20 17:51 :58
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3 L P[] 100mm/sec FINE                  
4\L\P[]\100mm/sec\CNT100\\\\\\\\\\\\\\\ 
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  16/16 
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:51 :52
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  16/16 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,+Z(J3) is pressed                
10-FEB-20 17:51 :46
========================================
SHIFT,-Z(J3) is pressed                
10-FEB-20 17:51 :44
========================================
SHIFT,-Z(J3) is pressed                
10-FEB-20 17:51 :42
========================================
ENTER is pressed                       
10-FEB-20 17:50 :08
========================================
0 is entered                           
10-FEB-20 17:50 :08
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  15/16 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L @P[8] 2000mm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2000 is entered                        
10-FEB-20 17:50 :04
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  15/16 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L @P[8] 100mmm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'4 L P[] 100mm/sec CNT100' is selected 
in 'Default Motion' menu               
10-FEB-20 17:49 :56
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  15/15 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:49 :50
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  15/15 
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,+Z(J3) is pressed                
10-FEB-20 17:49 :42
========================================
SHIFT,-Z(J3) is pressed                
10-FEB-20 17:49 :40
========================================
SHIFT,-Y(J2) is pressed                
10-FEB-20 17:49 :32
========================================
SHIFT,+Y(J2) is pressed                
10-FEB-20 17:49 :30
========================================
SHIFT,-X(J1) is pressed                
10-FEB-20 17:49 :28
========================================
SHIFT,+X(J1) is pressed                
10-FEB-20 17:49 :26
========================================
SHIFT,+X(J1) is pressed                
10-FEB-20 17:49 :24
========================================
SHIFT,FWD is pressed                   
10-FEB-20 17:47 :28
========================================
2 is entered                           
10-FEB-20 17:47 :22
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  14/15 
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J @P[8] 10] 100% CNT100            
[End]                                   
Old Value: 8                            
                        [CHOICE]POSITION
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
10-FEB-20 17:47 :14
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  14/14 
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:47 :06
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  14/14 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
1 is entered                           
10-FEB-20 17:47 :04
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  13/14 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J @P[8] 10] 100% CNT100            
[End]                                   
Old Value: 8                            
                        [CHOICE]POSITION
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
10-FEB-20 17:46 :54
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3 L P[] 100mm/sec FINE                  
4\L\P[]\100mm/sec\CNT100\\\\\\\\\\\\\\\ 
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  13/13 
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:46 :50
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  13/13 
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
ENTER is pressed                       
10-FEB-20 17:46 :08
========================================
0 is entered                           
10-FEB-20 17:46 :06
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  12/13 
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2000 is entered                        
10-FEB-20 17:46 :04
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  12/13 
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 100mmm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
5 is entered                           
10-FEB-20 17:46 :00
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  12/13 
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L @P[8] 10] 100mm/sec CNT100       
[End]                                   
Old Value: 8                            
                        [CHOICE]POSITION
========================================
'4 L P[] 100mm/sec CNT100' is selected 
in 'Default Motion' menu               
10-FEB-20 17:45 :52
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  12/12 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:45 :46
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  12/12 
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
2000 is entered                        
10-FEB-20 17:45 :32
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  11/12 
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 100mmm/sec FINE            
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
6 is entered                           
10-FEB-20 17:45 :28
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  11/12 
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L @P[8] 10] 100mm/sec FINE         
[End]                                   
Old Value: 8                            
                        [CHOICE]POSITION
========================================
'3 L P[] 100mm/sec FINE' is selected in
 'Default Motion' menu                 
10-FEB-20 17:45 :24
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  11/11 
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:45 :20
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  11/11 
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
2000 is entered                        
10-FEB-20 17:45 :18
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  10/11 
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 100mmm/sec FINE            
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'3 L P[] 100mm/sec FINE' is selected in
 'Default Motion' menu                 
10-FEB-20 17:45 :10
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  10/10 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:45 :06
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                  10/10 
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,-Z(J3) is pressed                
10-FEB-20 17:44 :54
========================================
SHIFT,-Z(J3) is pressed                
10-FEB-20 17:44 :50
========================================
0 is entered                           
10-FEB-20 17:44 :38
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                   9/10 
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L @P[6] 2000mm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'Linear' is selected in 'Motion Modify'
 menu                                  
10-FEB-20 17:44 :32
--Screen image--------------------------
                                        
Motion\Modify\\\\\\\\\\\\\\\\WORLD\\30\%
\1\Joint\\\\\\\\\\\\5                   
 2 Linear           6                   
 3 Circular         7                   
                    8                   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                   9/10 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:J @P[6] 100% CNT100                
[End]                                   
Select item                             
                        [CHOICE]        
========================================
F4([CHOICE]) is pressed                
10-FEB-20 17:44 :30
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                   9/10 
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:J @P[6] 100% CNT100                
[End]                                   
                                        
                        [CHOICE]        
========================================
SHIFT,F1( POINT  ) is pressed          
10-FEB-20 17:44 :22
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                    9/9 
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,+Z(J3) is pressed                
10-FEB-20 17:44 :16
========================================
SHIFT,-Z(J3) is pressed                
10-FEB-20 17:44 :14
========================================
SHIFT,+Z(J3) is pressed                
10-FEB-20 17:44 :12
========================================
SHIFT,-Z(J3) is pressed                
10-FEB-20 17:44 :10
========================================
SHIFT,-Y(J2) is pressed                
10-FEB-20 17:44 :02
========================================
SHIFT,-Y(J2) is pressed                
10-FEB-20 17:44 :02
========================================
SHIFT,+Y(J2) is pressed                
10-FEB-20 17:43 :58
========================================
SHIFT,-Y(J2) is pressed                
10-FEB-20 17:43 :56
========================================
SHIFT,+X(J1) is pressed                
10-FEB-20 17:43 :52
========================================
SHIFT,+X(J1) is pressed                
10-FEB-20 17:43 :46
========================================
SHIFT,-X(J1) is pressed                
10-FEB-20 17:43 :44
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
10-FEB-20 17:43 :28
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    8/8 
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:43 :14
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                    8/8 
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
PREV is pressed                        
10-FEB-20 17:43 :04
========================================
PREV is pressed                        
10-FEB-20 17:43 :04
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:43 :02
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                    1/8 
\\\1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
[End]                                   
                                        
                                        
                                        
 POINT                          TOUCHUP>
========================================
R E S E T                              
                                       
                              00000000 
10-FEB-20 17:42 :58
========================================
SYST-039 Operation mode T2 Selected    
                                       
                                       
SERVO                         00110110 
10-FEB-20 17:42 :58
========================================
Override 30%                           
10-FEB-20 17:42 :58
========================================
FILE 'MC:\PRO_MOV2.LS' is loaded       
10-FEB-20 17:42 :56
========================================
Override 100%                          
10-FEB-20 17:42 :56
========================================
R E S E T                              
                                       
                              00000000 
10-FEB-20 17:42 :56
========================================
R E S E T                              
                                       
                              00000000 
10-FEB-20 17:42 :56
========================================
SYST-040 Operation mode AUTO Selected  
                                       
                                       
SERVO                         00110110 
10-FEB-20 17:42 :56
========================================
SYST-043 TP disabled in T1/T2 mode     
                                       
                                       
STOP.L                        00000110 
10-FEB-20 17:42 :56
========================================
SHIFT,FWD is pressed                   
10-FEB-20 17:42 :30
========================================
1 is entered                           
10-FEB-20 17:42 :24
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                    7/8 
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J @P[5] 10] 100% CNT100            
[End]                                   
Old Value: 5                            
                        [CHOICE]POSITION
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
10-FEB-20 17:42 :20
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3 L P[] 100mm/sec FINE                  
4\L\P[]\100mm/sec\CNT100\\\\\\\\\\\\\\\ 
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    7/7 
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:42 :14
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                    7/7 
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
ENTER is pressed                       
10-FEB-20 17:42 :12
========================================
0 is entered                           
10-FEB-20 17:42 :12
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                    6/7 
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2000 is entered                        
10-FEB-20 17:42 :10
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                    6/7 
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 100mmm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2 is entered                           
10-FEB-20 17:42 :04
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                    6/7 
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L @P[5] 10] 100mm/sec CNT100       
[End]                                   
Old Value: 5                            
                        [CHOICE]POSITION
========================================
'4 L P[] 100mm/sec CNT100' is selected 
in 'Default Motion' menu               
10-FEB-20 17:41 :58
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\30\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    6/6 
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
10-FEB-20 17:41 :36
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                    6/6 
                                        
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
2000 is entered                        
10-FEB-20 17:41 :28
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\30\%
                                    5/6 
                                        
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 100mmm/sec FINE            
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
I/O              
========================================
 SO[    1]    ON  -> OFF
Tick:   1805880
TB:     924981588
10-FEB-20 18:04 :52
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1805879
TB:     924971979
10-FEB-20 18:04 :52
========================================
Paused       MULTIROBOTTASK,  32       
   (TASK:1,TB:924915778)               
10-FEB-20 18:04 :52
========================================
 SO[    1]    OFF -> ON 
Tick:   1804980
TB:     922790901
10-FEB-20 18:04 :52
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1804979
TB:     922789518
10-FEB-20 18:04 :52
========================================
Run FWD      MULTIROBOTTASK,  32       
   (TASK:1,TB:922712494)               
10-FEB-20 18:04 :52
========================================
 SO[    1]    ON  -> OFF
Tick:   1792854
TB:     893667700
10-FEB-20 18:04 :38
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1792853
TB:     893653460
10-FEB-20 18:04 :38
========================================
Paused       MULTIROBOTTASK,  33       
   (TASK:1,TB:893155038)               
10-FEB-20 18:04 :38
========================================
Run FWD      MULTIROBOTTASK,  33       
   (TASK:1,TB:881902625)               
10-FEB-20 18:04 :34
========================================
 SO[    1]    OFF -> ON 
Tick:   1786392
TB:     877768504
10-FEB-20 18:04 :32
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   1786391
TB:     877766835
10-FEB-20 18:04 :32
========================================
Run FWD      MULTIROBOTTASK,  32       
   (TASK:1,TB:877717240)               
10-FEB-20 18:04 :32
========================================
 SO[    1]    ON  -> OFF
Tick:   1355028
TB:     -169749282
10-FEB-20 17:56 :44
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   1355027
TB:     -169751156
10-FEB-20 17:56 :44
========================================
Aborted      MULTIROBOTTASK,   0       
   (TASK:1,TB:-169859121)              
10-FEB-20 17:56 :44
========================================
 SO[    1]    OFF -> ON 
Tick:   1353108
TB:     -174406878
10-FEB-20 17:56 :42
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   1353107
TB:     -174407960
10-FEB-20 17:56 :42
========================================
Run FWD      MULTIROBOTTASK,  26       
   (TASK:1,TB:-174440160)              
10-FEB-20 17:56 :42
========================================
 SO[    1]    ON  -> OFF
Tick:   1161396
TB:     -639822776
10-FEB-20 17:53 :14
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   1161395
TB:     -639824346
10-FEB-20 17:53 :14
========================================
Aborted      MULTIROBOTTASK,   0       
   (TASK:1,TB:-639894324)              
10-FEB-20 17:53 :14
========================================
Run FWD      MULTIROBOTTASK,  20       
   (TASK:1,TB:-642670626)              
10-FEB-20 17:53 :14
========================================
Run FWD      MULTIROBOTTASK,  19       
   (TASK:1,TB:-644023851)              
10-FEB-20 17:53 :12
========================================
Run FWD      MULTIROBOTTASK,  18       
   (TASK:1,TB:-645160583)              
10-FEB-20 17:53 :12
========================================
Run FWD      MULTIROBOTTASK,  17       
   (TASK:1,TB:-645975874)              
10-FEB-20 17:53 :12
========================================
 SO[    1]    OFF -> ON 
Tick:   1158648
TB:     -646592969
10-FEB-20 17:53 :12
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   1158647
TB:     -646594569
10-FEB-20 17:53 :12
========================================
Run FWD      MULTIROBOTTASK,  16       
   (TASK:1,TB:-646684903)              
10-FEB-20 17:53 :12
========================================
 SO[    1]    ON  -> OFF
Tick:   843156
TB:     -1408120691
10-FEB-20 17:47 :32
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   843155
TB:     -1408121607
10-FEB-20 17:47 :32
========================================
Aborted      MULTIROBOTTASK,   0       
   (TASK:1,TB:-1408155775)             
10-FEB-20 17:47 :32
========================================
Run FWD      MULTIROBOTTASK,  14       
   (TASK:1,TB:-1410881117)             
10-FEB-20 17:47 :30
========================================
Run FWD      MULTIROBOTTASK,  13       
   (TASK:1,TB:-1412250594)             
10-FEB-20 17:47 :30
========================================
Run FWD      MULTIROBOTTASK,  12       
   (TASK:1,TB:-1413769946)             
10-FEB-20 17:47 :30
========================================
Run FWD      MULTIROBOTTASK,  11       
   (TASK:1,TB:-1414698335)             
10-FEB-20 17:47 :28
========================================
 SO[    1]    OFF -> ON 
Tick:   840180
TB:     -1415400527
10-FEB-20 17:47 :28
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   840179
TB:     -1415402436
10-FEB-20 17:47 :28
========================================
Run FWD      MULTIROBOTTASK,  10       
   (TASK:1,TB:-1415459844)             
10-FEB-20 17:47 :28
========================================
 SO[    3]    ON  -> OFF
Tick:   586488
TB:     -2021386339
10-FEB-20 17:42 :58
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   586487
TB:     -2021394181
10-FEB-20 17:42 :58
========================================
 SO[    3]    OFF -> ON 
Tick:   586260
TB:     -2021975667
10-FEB-20 17:42 :58
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   586259
TB:     -2021976726
10-FEB-20 17:42 :58
========================================
 SO[    7]    OFF -> ON 
Tick:   586230
TB:     -2022046685
10-FEB-20 17:42 :58
========================================
 UO[    8]    OFF -> ON 
Tick:   586229
TB:     -2022053828
10-FEB-20 17:42 :58
========================================
 SO[    1]    ON  -> OFF
Tick:   585780
TB:     -2023226202
10-FEB-20 17:42 :58
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   585779
TB:     -2023226764
10-FEB-20 17:42 :58
========================================
Aborted      PRO_MOV2    ,   0         
 (TASK:7,TB:-2023236782)               
10-FEB-20 17:42 :58
========================================
 SO[    1]    OFF -> ON 
Tick:   585174
TB:     -2024647744
10-FEB-20 17:42 :56
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   585173
TB:     -2024648008
10-FEB-20 17:42 :56
========================================
Run FWD      PRO_MOV2    ,   3         
 (TASK:7,TB:-2024677169)               
10-FEB-20 17:42 :56
========================================
Run FWD      PRO_MOV2    ,   2         
 (TASK:7,TB:-2024677208)               
10-FEB-20 17:42 :56
========================================
Run FWD      PRO_MOV2    ,   1         
 (TASK:7,TB:-2024677261)               
10-FEB-20 17:42 :56
========================================
 SO[    3]    ON  -> OFF
Tick:   584568
TB:     -2026160890
10-FEB-20 17:42 :56
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   584567
TB:     -2026162893
10-FEB-20 17:42 :56
========================================
 SO[    3]    OFF -> ON 
Tick:   584184
TB:     -2027154451
10-FEB-20 17:42 :56
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   584183
TB:     -2027154780
10-FEB-20 17:42 :56
========================================
 SO[    7]    ON  -> OFF
Tick:   584148
TB:     -2027236456
10-FEB-20 17:42 :56
========================================
 UO[    8]    ON  -> OFF
Tick:   584147
TB:     -2027236622
10-FEB-20 17:42 :56
========================================
 SO[    1]    ON  -> OFF
Tick:   562296
TB:     -2079790969
10-FEB-20 17:42 :32
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   562295
TB:     -2079793860
10-FEB-20 17:42 :32
========================================
Aborted      MULTIROBOTTASK,   0       
   (TASK:1,TB:-2079822965)             
10-FEB-20 17:42 :32
========================================
 SO[    1]    OFF -> ON 
Tick:   561204
TB:     -2082498223
10-FEB-20 17:42 :30
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   561203
TB:     -2082498330
10-FEB-20 17:42 :30
========================================
Run FWD      MULTIROBOTTASK,   7       
   (TASK:1,TB:-2082557046)             
10-FEB-20 17:42 :30
========================================
 SO[    1]    ON  -> OFF
Tick:   342648
TB:     1697700894
10-FEB-20 17:38 :42
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   342647
TB:     1697698407
10-FEB-20 17:38 :42
========================================
Aborted      MULTIROBOTTASK,   0       
   (TASK:1,TB:1697557484)              
10-FEB-20 17:38 :40
========================================
 SO[    1]    OFF -> ON 
Tick:   341814
TB:     1695650069
10-FEB-20 17:38 :40
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   341813
TB:     1695645079
10-FEB-20 17:38 :40
========================================
Run FWD      MULTIROBOTTASK,   2       
   (TASK:1,TB:1695561531)              
10-FEB-20 17:38 :40
========================================
 SO[    3]    ON  -> OFF
Tick:   325656
TB:     1657917335
10-FEB-20 17:38 :24
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   325655
TB:     1657902927
10-FEB-20 17:38 :24
========================================
 SO[    3]    OFF -> ON 
Tick:   325428
TB:     1657363293
10-FEB-20 17:38 :24
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   325427
TB:     1657361545
10-FEB-20 17:38 :24
========================================
 SO[    7]    OFF -> ON 
Tick:   325368
TB:     1657202827
10-FEB-20 17:38 :22
========================================
 UO[    8]    OFF -> ON 
Tick:   325367
TB:     1657201672
10-FEB-20 17:38 :22
========================================
 SO[    1]    ON  -> OFF
Tick:   324918
TB:     1656124732
10-FEB-20 17:38 :22
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   324917
TB:     1656123340
10-FEB-20 17:38 :22
========================================
Aborted      PRO_MOV2    ,   0         
 (TASK:7,TB:1656071416)                
10-FEB-20 17:38 :22
========================================
 SO[    1]    OFF -> ON 
Tick:   324084
TB:     1654166161
10-FEB-20 17:38 :22
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   324083
TB:     1654165067
10-FEB-20 17:38 :22
========================================
Run FWD      PRO_MOV2    ,   3         
 (TASK:7,TB:1654098454)                
10-FEB-20 17:38 :22
========================================
Run FWD      PRO_MOV2    ,   2         
 (TASK:7,TB:1654098421)                
10-FEB-20 17:38 :22
========================================
Run FWD      PRO_MOV2    ,   1         
 (TASK:7,TB:1654098240)                
10-FEB-20 17:38 :22
========================================
 SO[    3]    ON  -> OFF
Tick:   323544
TB:     1652810286
10-FEB-20 17:38 :20
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   323543
TB:     1652808840
10-FEB-20 17:38 :20
========================================
 SO[    3]    OFF -> ON 
Tick:   323220
TB:     1652009998
10-FEB-20 17:38 :20
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   323219
TB:     1652008734
10-FEB-20 17:38 :20
========================================
 SO[    7]    ON  -> OFF
Tick:   323190
TB:     1651909168
10-FEB-20 17:38 :20
========================================
 UO[    8]    ON  -> OFF
Tick:   323189
TB:     1651908228
10-FEB-20 17:38 :20
========================================
 SO[    3]    ON  -> OFF
Tick:   297684
TB:     1592171890
10-FEB-20 17:37 :54
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   297683
TB:     1592170936
10-FEB-20 17:37 :54
========================================
 SO[    3]    OFF -> ON 
Tick:   297462
TB:     1591633971
10-FEB-20 17:37 :54
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   297461
TB:     1591632631
10-FEB-20 17:37 :54
========================================
 SO[    7]    OFF -> ON 
Tick:   297396
TB:     1591447957
10-FEB-20 17:37 :54
========================================
 UO[    8]    OFF -> ON 
Tick:   297395
TB:     1591446543
10-FEB-20 17:37 :54
========================================
 SO[    1]    ON  -> OFF
Tick:   297078
TB:     1590719692
10-FEB-20 17:37 :54
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   297077
TB:     1590717373
10-FEB-20 17:37 :54
========================================
Aborted      PRO_MOV2    ,   0         
 (TASK:7,TB:1590615732)                
10-FEB-20 17:37 :54
========================================
 SO[    1]    OFF -> ON 
Tick:   296628
TB:     1589540657
10-FEB-20 17:37 :52
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   296627
TB:     1589527728
10-FEB-20 17:37 :52
========================================
Run FWD      PRO_MOV2    ,   3         
 (TASK:7,TB:1589136927)                
10-FEB-20 17:37 :52
========================================
Run FWD      PRO_MOV2    ,   2         
 (TASK:7,TB:1589136878)                
10-FEB-20 17:37 :52
========================================
Run FWD      PRO_MOV2    ,   1         
 (TASK:7,TB:1589136762)                
10-FEB-20 17:37 :52
========================================
 SO[    3]    ON  -> OFF
Tick:   295956
TB:     1587183003
10-FEB-20 17:37 :52
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   295955
TB:     1587182246
10-FEB-20 17:37 :52
========================================
 SO[    3]    OFF -> ON 
Tick:   295668
TB:     1586484128
10-FEB-20 17:37 :52
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   295667
TB:     1586483979
10-FEB-20 17:37 :52
========================================
 SO[    7]    ON  -> OFF
Tick:   295638
TB:     1586387445
10-FEB-20 17:37 :52
========================================
 UO[    8]    ON  -> OFF
Tick:   295637
TB:     1586385211
10-FEB-20 17:37 :52
========================================
 SO[    3]    ON  -> OFF
Tick:   263670
TB:     1510155388
10-FEB-20 17:37 :18
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   263669
TB:     1510153166
10-FEB-20 17:37 :18
========================================
 SO[    3]    OFF -> ON 
Tick:   263352
TB:     1509404629
10-FEB-20 17:37 :16
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   263351
TB:     1509403092
10-FEB-20 17:37 :16
========================================
 SO[    7]    OFF -> ON 
Tick:   263316
TB:     1509321246
10-FEB-20 17:37 :16
========================================
 UO[    8]    OFF -> ON 
Tick:   263315
TB:     1509321040
10-FEB-20 17:37 :16
========================================
 UO[    2]    OFF -> ON 
Tick:   407
TB:     865839817
10-FEB-20 17:32 :30
========================================
 AO[    3]    0
 AO[    3]    0
 AO[    5]    0
 AO[    5]    0
 AO[    7]    0
 UI[    1]    ON 
 UI[    2]    ON 
 UI[    3]    ON 
 UI[    4]    OFF
 UI[    5]    OFF
 UI[    6]    OFF
 UI[    7]    OFF
 UI[    8]    ON 
 UI[   17]    OFF
 UI[   18]    OFF
 UI[   19]    OFF
 UI[   20]    OFF
 UI[   21]    OFF
 UI[   22]    OFF
 UI[   23]    OFF
 UI[   24]    OFF
 UI[   33]    OFF
 UI[   34]    OFF
 UO[    1]    OFF
 UO[    2]    OFF
 UO[    3]    OFF
 UO[    4]    OFF
 UO[    5]    OFF
 UO[    6]    OFF
 UO[    7]    OFF
 UO[    8]    OFF
 UO[   17]    OFF
 UO[   18]    OFF
 UO[   19]    OFF
 UO[   20]    OFF
 UO[   21]    OFF
 UO[   22]    OFF
 UO[   23]    OFF
 UO[   24]    OFF
 UO[   33]    OFF
 UO[   34]    OFF
 UO[   35]    OFF
 UO[   36]    OFF
Tick:   233
TB:     863034379
10-FEB-20 17:32 :28
========================================
 AI[   17]    0
 AI[   13]    0
 AI[   15]    0
 AI[   17]    0
 AI[   19]    0
 AI[   21]    0
 AI[   23]    0
 AO[    1]    0
Tick:   232
TB:     863034307
10-FEB-20 17:32 :28
========================================
 AI[    7]    0
 AI[    9]    0
 AI[   11]    0
 AI[    7]    0
 AI[    9]    0
 AI[   11]    0
 AI[   13]    0
 AI[   15]    0
Tick:   231
TB:     863008687
10-FEB-20 17:32 :28
========================================
 DO[   65]    OFF
 DO[   66]    OFF
 DO[   67]    OFF
 DO[   68]    OFF
 DO[   69]    OFF
 DO[   70]    OFF
 DO[   71]    OFF
 DO[   72]    OFF
 DO[   73]    OFF
 DO[   74]    OFF
 DO[   75]    OFF
 DO[   76]    OFF
 DO[   77]    OFF
 DO[   78]    OFF
 DO[   79]    OFF
 DO[   80]    OFF
 DO[   81]    OFF
 DO[   82]    OFF
 DO[   83]    OFF
 DO[   84]    OFF
 DO[   85]    OFF
 DO[   86]    OFF
 DO[   87]    OFF
 DO[   88]    OFF
 DO[   89]    OFF
 DO[   90]    OFF
 DO[   91]    OFF
 DO[   92]    OFF
 DO[   93]    OFF
 DO[   94]    OFF
 DO[   95]    OFF
 DO[   96]    OFF
 DO[   97]    OFF
 DO[   98]    OFF
 DO[   99]    OFF
 DO[  100]    OFF
 DO[  101]    OFF
 DO[  102]    OFF
 DO[  103]    OFF
 DO[  104]    OFF
 DO[  105]    OFF
 DO[  106]    OFF
 DO[  107]    OFF
 DO[  108]    OFF
 DO[  109]    OFF
 DO[  110]    OFF
 DO[  111]    OFF
 DO[  112]    OFF
 DO[  113]    OFF
 DO[  114]    OFF
 DO[  115]    OFF
 DO[  116]    OFF
 DO[  117]    OFF
 DO[  118]    OFF
 DO[  119]    OFF
 DO[  120]    OFF
 DO[  121]    OFF
 DO[  122]    OFF
 DO[  123]    OFF
 DO[  124]    OFF
 DO[  125]    OFF
 DO[  126]    OFF
 DO[  127]    OFF
 DO[  128]    OFF
 DO[  129]    OFF
 DO[  130]    OFF
 DO[  131]    OFF
 DO[  132]    OFF
 DO[  133]    OFF
 DO[  134]    OFF
 DO[  135]    OFF
 DO[  136]    OFF
 DO[  137]    OFF
 DO[  138]    OFF
 DO[  139]    OFF
 DO[  140]    OFF
 DO[  141]    OFF
 DO[  142]    OFF
 DO[  143]    OFF
 DO[  144]    OFF
 AI[    1]    0
 AI[    3]    0
 AI[    5]    0
Tick:   230
TB:     863007278
10-FEB-20 17:32 :28
========================================
 DI[   81]    OFF
 DI[   82]    OFF
 DI[   83]    OFF
 DI[   84]    OFF
 DI[   85]    OFF
 DI[   86]    OFF
 DI[   87]    OFF
 DI[   88]    OFF
 DI[   89]    OFF
 DI[   90]    OFF
 DI[   91]    OFF
 DI[   92]    OFF
 DI[   93]    OFF
 DI[   94]    OFF
 DI[   95]    OFF
 DI[   96]    OFF
 DI[   97]    OFF
 DI[   98]    OFF
 DI[   99]    OFF
 DI[  100]    OFF
 DI[  101]    OFF
 DI[  102]    OFF
 DI[  103]    OFF
 DI[  104]    OFF
 DI[  105]    OFF
 DI[  106]    OFF
 DI[  107]    OFF
 DI[  108]    OFF
 DI[  109]    OFF
 DI[  110]    OFF
 DI[  111]    OFF
 DI[  112]    OFF
 DI[  113]    OFF
 DI[  114]    OFF
 DI[  115]    OFF
 DI[  116]    OFF
 DI[  117]    OFF
 DI[  118]    OFF
 DI[  119]    OFF
 DI[  120]    OFF
 DI[  121]    OFF
 DI[  122]    OFF
 DI[  123]    OFF
 DI[  124]    OFF
 DI[  125]    OFF
 DI[  126]    OFF
 DI[  127]    OFF
 DI[  128]    OFF
 DI[  129]    OFF
 DI[  130]    OFF
 DI[  131]    OFF
 DI[  132]    OFF
 DI[  133]    OFF
 DI[  134]    OFF
 DI[  135]    OFF
 DI[  136]    OFF
 DI[  137]    OFF
 DI[  138]    OFF
 DI[  139]    OFF
 DI[  140]    OFF
 DI[  141]    OFF
 DI[  142]    OFF
 DI[  143]    OFF
 DI[  144]    OFF
 DO[   21]    OFF
 DO[   22]    OFF
 DO[   23]    OFF
 DO[   24]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
 DO[   41]    OFF
 DO[   42]    OFF
 DO[   43]    OFF
 DO[   44]    OFF
 DO[   53]    OFF
 DO[   54]    OFF
 DO[   55]    OFF
 DO[   56]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   29]    OFF
 DO[   30]    OFF
 DO[   31]    OFF
 DO[   32]    OFF
 DO[   33]    OFF
 DO[   34]    OFF
 DO[   35]    OFF
 DO[   36]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
 DO[   41]    OFF
 DO[   42]    OFF
 DO[   43]    OFF
 DO[   44]    OFF
 DO[   45]    OFF
 DO[   46]    OFF
 DO[   47]    OFF
 DO[   48]    OFF
 DO[   49]    OFF
 DO[   50]    OFF
 DO[   51]    OFF
 DO[   52]    OFF
 DO[   53]    OFF
 DO[   54]    OFF
 DO[   55]    OFF
 DO[   56]    OFF
 DO[   57]    OFF
 DO[   58]    OFF
 DO[   59]    OFF
 DO[   60]    OFF
 DO[   61]    OFF
 DO[   62]    OFF
 DO[   63]    OFF
 DO[   64]    OFF
Tick:   229
TB:     863007176
10-FEB-20 17:32 :28
========================================
 SI[    0]    ON 
 SI[    1]    OFF
 SI[    2]    ON 
 SI[    3]    ON 
 SI[    4]    OFF
 SI[    5]    OFF
 SI[    6]    OFF
 SI[    7]    OFF
 SI[    8]    OFF
 SI[    9]    OFF
 SI[   10]    OFF
 SI[   11]    OFF
 SI[   12]    OFF
 SI[   13]    OFF
 SI[   14]    OFF
 SI[   15]    OFF
 SO[    0]    OFF
 SO[    1]    OFF
 SO[    2]    OFF
 SO[    3]    OFF
 SO[    4]    OFF
 SO[    5]    OFF
 SO[    6]    OFF
 SO[    7]    OFF
 SO[    8]    OFF
 SO[    9]    OFF
 SO[   10]    OFF
 SO[   11]    OFF
 SO[   12]    OFF
 SO[   13]    OFF
 SO[   14]    OFF
 SO[   15]    OFF
 RI[    1]    OFF
 RI[    2]    OFF
 RI[    3]    OFF
 RI[    4]    OFF
 RI[    5]    OFF
 RI[    6]    OFF
 RI[    7]    OFF
 RI[    8]    OFF
 RO[    1]    OFF
 RO[    2]    OFF
 RO[    3]    OFF
 RO[    4]    OFF
 RO[    5]    OFF
 RO[    6]    OFF
 RO[    7]    OFF
 RO[    8]    OFF
 DI[   19]    OFF
 DI[   20]    OFF
 DI[   21]    OFF
 DI[   22]    OFF
 DI[   23]    OFF
 DI[   24]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   41]    OFF
 DI[   42]    OFF
 DI[   51]    OFF
 DI[   52]    OFF
 DI[   53]    OFF
 DI[   54]    OFF
 DI[   55]    OFF
 DI[   56]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   27]    OFF
 DI[   28]    OFF
 DI[   29]    OFF
 DI[   30]    OFF
 DI[   31]    OFF
 DI[   32]    OFF
 DI[   33]    OFF
 DI[   34]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   41]    OFF
 DI[   42]    OFF
 DI[   43]    OFF
 DI[   44]    OFF
 DI[   45]    OFF
 DI[   46]    OFF
 DI[   47]    OFF
 DI[   48]    OFF
 DI[   49]    OFF
 DI[   50]    OFF
 DI[   51]    OFF
 DI[   52]    OFF
 DI[   53]    OFF
 DI[   54]    OFF
 DI[   55]    OFF
 DI[   56]    OFF
 DI[   57]    OFF
 DI[   58]    OFF
 DI[   59]    OFF
 DI[   60]    OFF
 DI[   61]    OFF
 DI[   62]    OFF
 DI[   63]    OFF
 DI[   64]    OFF
 DI[   65]    OFF
 DI[   66]    OFF
 DI[   67]    OFF
 DI[   68]    OFF
 DI[   69]    OFF
 DI[   70]    OFF
 DI[   71]    OFF
 DI[   72]    OFF
 DI[   73]    OFF
 DI[   74]    OFF
 DI[   75]    OFF
 DI[   76]    OFF
 DI[   77]    OFF
 DI[   78]    OFF
 DI[   79]    OFF
 DI[   80]    OFF
Tick:   228
TB:     863007046
10-FEB-20 17:32 :28
