ERRMOT.LS      Robot Name ROBOT 10-FEB-20 18:04     

1" 10-FEB-20 17:32 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
2" 10-FEB-20 07:45 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
3" 09-FEB-20 18:44 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
4" 09-FEB-20 09:06 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
5" 29-JAN-20 23:09 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
6" 29-JAN-20 18:35 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
7" 28-JAN-20 15:20 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
