ERRACT.LS      Robot Name ROBOT 10-MAY-20 09:09     

466" 10-MAY-20 09:08 " MOTN-056 Speed limits used (G:1)                  " DATA     0   2   0    0   0        5              " NONE                          10000000" 
467" 10-MAY-20 09:08 " SRVO-171 MotorSpd lim/DVC(G:1 A:1)                " " NONE                          10000000" 
468" 10-MAY-20 09:08 " SRVO-171 MotorSpd lim/DVC(G:1 A:4)                " " NONE                          10000000" 
469" 10-MAY-20 09:08 " SRVO-171 MotorSpd lim/DVC(G:1 A:4)                " " NONE                          10000000" 
470" 10-MAY-20 09:08 " MOTN-056 Speed limits used (G:1)                  " DATA     0   2   0    0   0        5              " NONE                          10000000" 
