ERRMOT.LS      Robot Name ROBOT 09-FEB-20 19:03     

1" 09-FEB-20 18:44 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
2" 09-FEB-20 09:06 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
3" 29-JAN-20 23:09 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
4" 29-JAN-20 18:35 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
5" 28-JAN-20 15:20 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
