LOGBOOK.LS     Robot Name ROBOT 09-FEB-20 19:03     

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Operation        
========================================
FILE 'MC:\IOSTATUS.CM' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\HTTPKCL.VR' is saved         
09-FEB-20 19:03 :00
========================================
FILE 'MC:\HTCOLREC.VR' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\HOME_IO.TP' is saved         
09-FEB-20 19:03 :00
========================================
FILE 'MC:\HIST.LS' is saved            
09-FEB-20 19:03 :00
========================================
FILE 'MC:\HIGHM61C.VR' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\HI03M61C.VR' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\GREENLED.GIF' is saved       
09-FEB-20 19:03 :00
========================================
FILE 'MC:\GETDATA.TP' is saved         
09-FEB-20 19:03 :00
========================================
FILE 'MC:\GEMDATA.VR' is saved         
09-FEB-20 19:03 :00
========================================
FILE 'MC:\FTPLOG.DG' is saved          
09-FEB-20 19:03 :00
========================================
FILE 'MC:\FRAMEVAR.VR' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\ETHERNET.DG' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\ERRSYS.LS' is saved          
09-FEB-20 19:03 :00
========================================
FILE 'MDS6:\ERRSYS.LS' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\ERRPWD.LS' is saved          
09-FEB-20 19:03 :00
========================================
FILE 'MDS5:\ERRPWD.LS' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\ERRMOT.LS' is saved          
09-FEB-20 19:03 :00
========================================
FILE 'MDS4:\ERRMOT.LS' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\ERRHIST.LS' is saved         
09-FEB-20 19:03 :00
========================================
FILE 'MDS3:\ERRHIST.LS' is saved       
09-FEB-20 19:03 :00
========================================
FILE 'MC:\ERREXT.LS' is saved          
09-FEB-20 19:03 :00
========================================
FILE 'MDS2:\ERREXT.LS' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\ERRCURR.LS' is saved         
09-FEB-20 19:03 :00
========================================
FILE 'MDS1:\ERRCURR.LS' is saved       
09-FEB-20 19:03 :00
========================================
FILE 'MC:\ERRCOMM.LS' is saved         
09-FEB-20 19:03 :00
========================================
FILE 'MDS0:\ERRCOMM.LS' is saved       
09-FEB-20 19:03 :00
========================================
FILE 'MC:\ERRAPP.LS' is saved          
09-FEB-20 19:03 :00
========================================
FILE 'MDS9:\ERRAPP.LS' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\ERRALL.LS' is saved          
09-FEB-20 19:03 :00
========================================
FILE 'MDS8:\ERRALL.LS' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\ERRACT.LS' is saved          
09-FEB-20 19:03 :00
========================================
FILE 'MDS7:\ERRACT.LS' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\DIOCFGSV.IO' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\DF_MOTN0.DF' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\DF_LOGI6.DF' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\DF_LOGI5.DF' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\DF_LOGI4.DF' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\DF_LOGI3.DF' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\DF_LOGI2.DF' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\DF_LOGI1.DF' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\DCSVRFY3.DG' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\DCSVRFY2.DG' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\DCSVRFY1.DG' is saved        
09-FEB-20 19:03 :00
========================================
FILE 'MC:\DCSVRFY.DG' is saved         
09-FEB-20 19:02 :58
========================================
FILE 'MC:\DCSDIFF.DG' is saved         
09-FEB-20 19:02 :58
========================================
FILE 'MC:\DCSCHGD3.DG' is saved        
09-FEB-20 19:02 :58
========================================
FILE 'MC:\DCSCHGD2.DG' is saved        
09-FEB-20 19:02 :58
========================================
FILE 'MC:\DCSCHGD1.DG' is saved        
09-FEB-20 19:02 :58
========================================
FILE 'MC:\DARKLED.GIF' is saved        
09-FEB-20 19:02 :58
========================================
FILE 'MC:\CONSLOG.DG' is saved         
09-FEB-20 19:02 :58
========================================
FILE 'MC:\CELLIO.SV' is saved          
09-FEB-20 19:02 :58
========================================
FILE 'MC:\BACKDATE.DT' is saved        
09-FEB-20 19:02 :58
========================================
FILE 'MC:\ATERRJOB.VR' is saved        
09-FEB-20 19:02 :58
========================================
FILE 'MC:\AMBERLED.GIF' is saved       
09-FEB-20 19:02 :58
========================================
FILE 'MC:\-BCKEDT-.TP' is saved        
09-FEB-20 19:02 :58
========================================
FILE 'MC:\-BCKED9-.TP' is saved        
09-FEB-20 19:02 :58
========================================
FILE 'MC:\-BCKED8-.TP' is saved        
09-FEB-20 19:02 :58
========================================
Override 20%                           
09-FEB-20 19:02 :58
========================================
Override 100%                          
09-FEB-20 19:02 :48
========================================
R E S E T                              
                                       
                              00000000 
09-FEB-20 19:02 :48
========================================
FILE 'MC:\XXXXXLED.GIF' is saved       
09-FEB-20 19:02 :48
========================================
FILE 'MC:\UPDTLOG.LS' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\UPDATES.DAT' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\TPRECKL.VR' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\TPREC.TP' is saved           
09-FEB-20 19:02 :48
========================================
FILE 'MC:\TPEINS.XML' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SYSVARS.SV' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SYSUIF.SV' is saved          
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SYSSERVO.SV' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SYSPASS.SV' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SYSMAST.SV' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SYSMACRO.SV' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SYSHOST.SV' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SYSFSAC.SV' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SYSFRAME.SV' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SUMMARY.DG' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\STRREG.VR' is saved          
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SPACER.GIF' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SHADOW.DG' is saved          
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SENDSYSV.TP' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SENDEVNT.TP' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\SENDDATA.TP' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\REQMENU.TP' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\REDLED.GIF' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\PSRBWLD.CM' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\PRO_MOV2.TP' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\POSREG.VR' is saved          
09-FEB-20 19:02 :48
========================================
FILE 'MC:\PBUTTON.GIF' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\PANEL4.STM' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\PANEL4.DT' is saved          
09-FEB-20 19:02 :48
========================================
FILE 'MC:\PANEL3.STM' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\PANEL3.DT' is saved          
09-FEB-20 19:02 :48
========================================
FILE 'MC:\PANEL2.STM' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\PANEL2.DT' is saved          
09-FEB-20 19:02 :48
========================================
FILE 'MC:\PANEL1.STM' is saved         
09-FEB-20 19:02 :48
========================================
FILE 'MC:\PANEL1.DT' is saved          
09-FEB-20 19:02 :48
========================================
FILE 'MC:\OTEMGRUN.VR' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\OTEMGMON.VR' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\ORDERFIL.DAT' is saved       
09-FEB-20 19:02 :48
========================================
FILE 'MC:\NUMREG.VR' is saved          
09-FEB-20 19:02 :48
========================================
FILE 'MC:\NTDAQ.VR' is saved           
09-FEB-20 19:02 :48
========================================
FILE 'MC:\NORMM61C.VR' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\NO03M61C.VR' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\NBUTTON.GIF' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\MULTIROBOTTASK.TP' is saved  
09-FEB-20 19:02 :48
========================================
FILE 'MC:\MIXLOGIC.SV' is saved        
09-FEB-20 19:02 :48
========================================
FILE 'MC:\MEM_PORT.VR' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\MEMCHECK.DG' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\M61C.DT' is saved            
09-FEB-20 19:02 :46
========================================
FILE 'MC:\M10SET10.VR' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\M10SET06.VR' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\M10SET03.VR' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\LOGBOOK.LS' is saved         
09-FEB-20 19:02 :46
========================================
FILE 'MDS9:\LOGBOOK.LS' is saved       
09-FEB-20 19:02 :46
========================================
FILE 'MC:\IOSTATUS.CM' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\HTTPKCL.VR' is saved         
09-FEB-20 19:02 :46
========================================
FILE 'MC:\HTCOLREC.VR' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\HOME_IO.TP' is saved         
09-FEB-20 19:02 :46
========================================
FILE 'MC:\HIST.LS' is saved            
09-FEB-20 19:02 :46
========================================
FILE 'MC:\HIGHM61C.VR' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\HI03M61C.VR' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\GREENLED.GIF' is saved       
09-FEB-20 19:02 :46
========================================
FILE 'MC:\GETDATA.TP' is saved         
09-FEB-20 19:02 :46
========================================
FILE 'MC:\GEMDATA.VR' is saved         
09-FEB-20 19:02 :46
========================================
FILE 'MC:\FTPLOG.DG' is saved          
09-FEB-20 19:02 :46
========================================
FILE 'MC:\FRAMEVAR.VR' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\ETHERNET.DG' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\ERRSYS.LS' is saved          
09-FEB-20 19:02 :46
========================================
FILE 'MDS5:\ERRSYS.LS' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\ERRPWD.LS' is saved          
09-FEB-20 19:02 :46
========================================
FILE 'MDS4:\ERRPWD.LS' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\ERRMOT.LS' is saved          
09-FEB-20 19:02 :46
========================================
FILE 'MDS3:\ERRMOT.LS' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\ERRHIST.LS' is saved         
09-FEB-20 19:02 :46
========================================
FILE 'MDS2:\ERRHIST.LS' is saved       
09-FEB-20 19:02 :46
========================================
FILE 'MC:\ERREXT.LS' is saved          
09-FEB-20 19:02 :46
========================================
FILE 'MDS1:\ERREXT.LS' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\ERRCURR.LS' is saved         
09-FEB-20 19:02 :46
========================================
FILE 'MDS0:\ERRCURR.LS' is saved       
09-FEB-20 19:02 :46
========================================
FILE 'MC:\ERRCOMM.LS' is saved         
09-FEB-20 19:02 :46
========================================
FILE 'MDS9:\ERRCOMM.LS' is saved       
09-FEB-20 19:02 :46
========================================
FILE 'MC:\ERRAPP.LS' is saved          
09-FEB-20 19:02 :46
========================================
FILE 'MDS8:\ERRAPP.LS' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\ERRALL.LS' is saved          
09-FEB-20 19:02 :46
========================================
FILE 'MDS7:\ERRALL.LS' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\ERRACT.LS' is saved          
09-FEB-20 19:02 :46
========================================
FILE 'MDS6:\ERRACT.LS' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DIOCFGSV.IO' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DF_MOTN0.DF' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DF_LOGI6.DF' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DF_LOGI5.DF' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DF_LOGI4.DF' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DF_LOGI3.DF' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DF_LOGI2.DF' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DF_LOGI1.DF' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DCSVRFY3.DG' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DCSVRFY2.DG' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DCSVRFY1.DG' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DCSVRFY.DG' is saved         
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DCSDIFF.DG' is saved         
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DCSCHGD3.DG' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DCSCHGD2.DG' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DCSCHGD1.DG' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\DARKLED.GIF' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\CONSLOG.DG' is saved         
09-FEB-20 19:02 :46
========================================
FILE 'MC:\CELLIO.SV' is saved          
09-FEB-20 19:02 :46
========================================
FILE 'MC:\BACKDATE.DT' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\ATERRJOB.VR' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\AMBERLED.GIF' is saved       
09-FEB-20 19:02 :46
========================================
FILE 'MC:\-BCKEDT-.TP' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\-BCKED9-.TP' is saved        
09-FEB-20 19:02 :46
========================================
FILE 'MC:\-BCKED8-.TP' is saved        
09-FEB-20 19:02 :46
========================================
SHIFT,FWD is pressed                   
09-FEB-20 18:57 :46
========================================
5 is entered                           
09-FEB-20 18:57 :34
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  20/21 
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
  20:J @P[10] 1] 100% CNT100            
[End]                                   
Old Value: 10                           
                        [CHOICE]POSITION
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
09-FEB-20 18:57 :28
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\20\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3 L P[] 100mm/sec FINE                  
4\L\P[]\100mm/sec\CNT100\\\\\\\\\\\\\\\ 
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  20/20 
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
09-FEB-20 18:57 :24
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  20/20 
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
100 is entered                         
09-FEB-20 18:55 :48
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  19/20 
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J  P[1] 5% % CNT100                
[End]                                   
Old Value: 5                            
REGISTER                [CHOICE]        
========================================
1 is entered                           
09-FEB-20 18:55 :44
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  19/20 
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:J @P[10] 5] 5% CNT100              
[End]                                   
Old Value: 10                           
                        [CHOICE]POSITION
========================================
'Joint' is selected in 'Motion Modify' 
menu                                   
09-FEB-20 18:55 :42
--Screen image--------------------------
                                        
Motion\Modify\\\\\\\\\\\\\\\\WORLD\\20\%
\1\Joint\\\\\\\\\\\\5                   
 2 Linear           6                   
 3 Circular         7                   
                    8                   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  19/20 
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:L @P[10] 100mm/sec CNT100          
[End]                                   
Select item                             
                        [CHOICE]        
========================================
F4([CHOICE]) is pressed                
09-FEB-20 18:55 :40
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  19/20 
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
  19:L @P[10] 100mm/sec CNT100          
[End]                                   
                                        
                        [CHOICE]        
========================================
'4 L P[] 100mm/sec CNT100' is selected 
in 'Default Motion' menu               
09-FEB-20 18:55 :38
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\20\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3 L P[] 100mm/sec FINE                  
4\L\P[]\100mm/sec\CNT100\\\\\\\\\\\\\\\ 
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  19/19 
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
09-FEB-20 18:55 :34
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  19/19 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
'Joint' is selected in 'Motion Modify' 
menu                                   
09-FEB-20 18:55 :28
--Screen image--------------------------
                                        
Motion\Modify\\\\\\\\\\\\\\\\WORLD\\20\%
\1\Joint\\\\\\\\\\\\5                   
 2 Linear           6                   
 3 Circular         7                   
                    8                   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  14/19 
  14:L  P[2] 2000mm/sec CNT100          
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
[End]                                   
Select item                             
                        [CHOICE]        
========================================
F4([CHOICE]) is pressed                
09-FEB-20 18:55 :26
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  14/19 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:L  P[2] 2000mm/sec CNT100          
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
[End]                                   
                                        
                        [CHOICE]        
========================================
'Linear' is selected in 'Motion Modify'
 menu                                  
09-FEB-20 18:55 :00
--Screen image--------------------------
                                        
Motion\Modify\\\\\\\\\\\\\\\\WORLD\\20\%
\1\Joint\\\\\\\\\\\\5                   
 2 Linear           6                   
 3 Circular         7                   
                    8                   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  14/19 
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
[End]                                   
Select item                             
                        [CHOICE]        
========================================
F4([CHOICE]) is pressed                
09-FEB-20 18:54 :58
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  14/19 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT0            
[End]                                   
                                        
                        [CHOICE]        
========================================
0 is entered                           
09-FEB-20 18:54 :36
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  18/19 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 2000mm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2000 is entered                        
09-FEB-20 18:54 :32
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  18/19 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L  P[2] 100mmm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2 is entered                           
09-FEB-20 18:54 :20
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  18/19 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
  18:L @P[10] 1] 100mm/sec CNT100       
[End]                                   
Old Value: 10                           
                        [CHOICE]POSITION
========================================
'4 L P[] 100mm/sec CNT100' is selected 
in 'Default Motion' menu               
09-FEB-20 18:54 :14
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\20\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  18/18 
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
09-FEB-20 18:54 :08
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  18/18 
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 2000mm/sec FINE            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
2000 is entered                        
09-FEB-20 18:54 :00
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  17/18 
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L  P[8] 100mmm/sec FINE            
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
8 is entered                           
09-FEB-20 18:53 :54
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  17/18 
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
  17:L @P[10] 1] 100mm/sec FINE         
[End]                                   
Old Value: 10                           
                        [CHOICE]POSITION
========================================
'3 L P[] 100mm/sec FINE' is selected in
 'Default Motion' menu                 
09-FEB-20 18:53 :48
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\20\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  17/17 
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
09-FEB-20 18:53 :44
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  17/17 
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 2000mm/sec FINE            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
2000 is entered                        
09-FEB-20 18:53 :30
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  16/17 
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 200mmm/sec FINE            
[End]                                   
Old Value: 200                          
REGISTER                [CHOICE]        
========================================
200 is entered                         
09-FEB-20 18:53 :26
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  16/17 
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
  16:L @P[9] 100mmm/sec FINE            
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
SHIFT,F1( POINT  ) is pressed          
09-FEB-20 18:53 :10
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  16/16 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L  P[8] 2000mm/sec CNT0            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,-Z(J3) is pressed                
09-FEB-20 18:53 :02
========================================
SHIFT,+Z(J3) is pressed                
09-FEB-20 18:53 :02
========================================
SHIFT,-Z(J3) is pressed                
09-FEB-20 18:53 :00
========================================
SHIFT,-Z(J3) is pressed                
09-FEB-20 18:52 :56
========================================
SHIFT,+Z(J3) is pressed                
09-FEB-20 18:52 :52
========================================
0 is entered                           
09-FEB-20 18:51 :48
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  15/16 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L @P[8] 2000mm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'Cnt' is selected in 'Motion Modify' me
nu                                     
09-FEB-20 18:51 :46
--Screen image--------------------------
                                        
Motion\Modify\\\\\\\\\\\\\\\\WORLD\\20\%
\1\Fine\\\\\\\\\\\\\5                   
 2 Cnt              6                   
                    7                   
                    8                   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  15/16 
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L @P[8] 2000mm/sec FINE            
[End]                                   
Select item                             
                        [CHOICE]        
========================================
F4([CHOICE]) is pressed                
09-FEB-20 18:51 :44
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  15/16 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L @P[8] 2000mm/sec FINE            
[End]                                   
                                        
                        [CHOICE]        
========================================
2000 is entered                        
09-FEB-20 18:51 :42
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  15/16 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
  15:L @P[8] 100mmm/sec FINE            
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'3 L P[] 100mm/sec FINE' is selected in
 'Default Motion' menu                 
09-FEB-20 18:51 :32
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\20\%
1\J\P[]\100%\FINE\\\\\\\\\\\\\\\\\\\\\\ 
2 J P[] 100% CNT100                     
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  15/15 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
09-FEB-20 18:51 :18
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  15/15 
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
PREV is pressed                        
09-FEB-20 18:51 :14
========================================
F1([ INST ]) is pressed                
09-FEB-20 18:51 :12
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  15/15 
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
[End]                                   
                                        
[ INST ]                        [EDCMD]>
========================================
PREV is pressed                        
09-FEB-20 18:51 :10
========================================
R E S E T                              
                                       
                              00000000 
09-FEB-20 18:51 :08
========================================
SYST-039 Operation mode T2 Selected    
                                       
                                       
SERVO                         00110110 
09-FEB-20 18:51 :08
========================================
R E S E T                              
                                       
                              00000000 
09-FEB-20 18:51 :08
========================================
SYST-040 Operation mode AUTO Selected  
                                       
                                       
SERVO                         00110110 
09-FEB-20 18:51 :08
========================================
SHIFT,PREV is pressed                  
09-FEB-20 18:51 :06
========================================
SHIFT,PREV is pressed                  
09-FEB-20 18:51 :06
========================================
SHIFT,PREV is pressed                  
09-FEB-20 18:51 :06
========================================
SHIFT,F1([ INST ]) is pressed          
09-FEB-20 18:51 :00
--Screen image--------------------------
                                        
Instruction\\\\\\\\\\\\\\\\\\WORLD\\20\%
\1\Registers\\\\\\\\5 JMP/LBL           
 2 I/O              6 CALL              
 3 IF/SELECT        7 Miscellaneous     
 4 WAIT             8 ---next page---   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  15/15 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
[End]                                   
                                        
[ INST ]                        [EDCMD]>
========================================
SHIFT,PREV is pressed                  
09-FEB-20 18:51 :00
========================================
SHIFT,PREV is pressed                  
09-FEB-20 18:50 :54
========================================
SHIFT,PREV is pressed                  
09-FEB-20 18:50 :52
========================================
SHIFT,F1([ INST ]) is pressed          
09-FEB-20 18:50 :50
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\20\%
                                  15/15 
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J  P[2] 100% CNT100                
[End]                                   
                                        
[ INST ]                        [EDCMD]>
========================================
SHIFT,-Z(J3) is pressed                
09-FEB-20 18:50 :32
========================================
SHIFT,+Z(J3) is pressed                
09-FEB-20 18:50 :32
========================================
SHIFT,-Z(J3) is pressed                
09-FEB-20 18:50 :24
========================================
SHIFT,+Z(J3) is pressed                
09-FEB-20 18:50 :22
========================================
SHIFT,+Y(J2) is pressed                
09-FEB-20 18:50 :14
========================================
SHIFT,-Y(J2) is pressed                
09-FEB-20 18:50 :10
========================================
SHIFT,+Y(J2) is pressed                
09-FEB-20 18:50 :08
========================================
SHIFT,+X(J1) is pressed                
09-FEB-20 18:50 :02
========================================
SHIFT,-X(J1) is pressed                
09-FEB-20 18:50 :00
========================================
SHIFT,+X(J1) is pressed                
09-FEB-20 18:49 :58
========================================
SHIFT,+Z(J3) is pressed                
09-FEB-20 18:49 :40
========================================
SHIFT,+Y(J2) is pressed                
09-FEB-20 18:49 :34
========================================
SHIFT,+Y(J2) is pressed                
09-FEB-20 18:49 :32
========================================
SHIFT,-Y(J2) is pressed                
09-FEB-20 18:49 :30
========================================
SHIFT,-Y(J2) is pressed                
09-FEB-20 18:49 :04
========================================
SHIFT,+Z(J3) is pressed                
09-FEB-20 18:48 :56
========================================
SHIFT,-Z(J3) is pressed                
09-FEB-20 18:48 :52
========================================
SHIFT,-Y(J2) is pressed                
09-FEB-20 18:48 :50
========================================
SHIFT,+Y(J2) is pressed                
09-FEB-20 18:48 :48
========================================
SHIFT,+X(J1) is pressed                
09-FEB-20 18:48 :46
========================================
SHIFT,+X(J1) is pressed                
09-FEB-20 18:48 :44
========================================
SHIFT,-X(J1) is pressed                
09-FEB-20 18:48 :42
========================================
Override 20%                           
09-FEB-20 18:48 :40
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :40
========================================
Override 25%                           
09-FEB-20 18:48 :40
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :40
========================================
Override 30%                           
09-FEB-20 18:48 :40
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :40
========================================
Override 35%                           
09-FEB-20 18:48 :38
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :38
========================================
Override 40%                           
09-FEB-20 18:48 :38
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :38
========================================
Override 45%                           
09-FEB-20 18:48 :38
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :38
========================================
Override 50%                           
09-FEB-20 18:48 :38
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :38
========================================
Override 55%                           
09-FEB-20 18:48 :38
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :38
========================================
Override 60%                           
09-FEB-20 18:48 :38
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :38
========================================
Override 65%                           
09-FEB-20 18:48 :38
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :36
========================================
Override 70%                           
09-FEB-20 18:48 :36
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :36
========================================
Override 75%                           
09-FEB-20 18:48 :36
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :36
========================================
Override 80%                           
09-FEB-20 18:48 :36
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :36
========================================
Override 85%                           
09-FEB-20 18:48 :36
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :36
========================================
Override 90%                           
09-FEB-20 18:48 :36
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :36
========================================
Override 95%                           
09-FEB-20 18:48 :36
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :36
========================================
Override 100%                          
09-FEB-20 18:48 :36
========================================
Override 95%                           
09-FEB-20 18:48 :36
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :36
========================================
SHIFT -% is pressed                    
09-FEB-20 18:48 :36
========================================
SHIFT,-X(J1) is pressed                
09-FEB-20 18:48 :32
========================================
SHIFT,+X(J1) is pressed                
09-FEB-20 18:48 :26
========================================
F4(  YES   ) is pressed                
09-FEB-20 18:47 :42
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\100\%
                                  15/16 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J @P[2] 100% CNT100                
\\15:J  P[1] 100% FINE                  
[End]                                   
Delete line(s) ?                        
                          YES     NO    
========================================
'Delete' is selected                   
09-FEB-20 18:47 :40
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\100\%
                                  15/16 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT1__________________
   9:L  P[6] 2000mm/se| 1\Insert\\\\\\ |
  10:L  P[7] 2000mm/se| 2 Delete       |
  11:L  P[6] 2000mm/se| 3 Copy         |
  12:L  P[5] 2000mm/se| 4 Find         |
  13:J  P[1] 100% CNT1| 5 Replace      |
  14:J @P[2] 100% CNT1| 6 Renumber     |
\\15:J  P[1] 100% FINE| 7 Comment      |
[End]                 | 8 Undo         |
                      ----------+     +-
[ INST ]                        |EDCMD|>
========================================
F5([EDCMD]>) is pressed                
09-FEB-20 18:47 :38
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\100\%
                                  15/16 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J @P[2] 100% CNT100                
\\15:J  P[1] 100% FINE                  
[End]                                   
                                        
[ INST ]                        [EDCMD]>
========================================
F5(TOUCHUP>) is pressed                
09-FEB-20 18:47 :36
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\100\%
                                  15/16 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J @P[2] 100% CNT100                
\\15:J  P[1] 100% FINE                  
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
PREV is pressed                        
09-FEB-20 18:47 :32
========================================
F4([CHOICE]) is pressed                
09-FEB-20 18:47 :16
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\100\%
                                  15/16 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J @P[2] 100% CNT100                
  15:J  P[1] 100% FINE                  
[End]                                   
                                        
                        [CHOICE]        
========================================
1 is entered                           
09-FEB-20 18:47 :08
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\100\%
                                  15/16 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J @P[2] 100% CNT100                
  15:J @P[8] 10] 100% FINE              
[End]                                   
Old Value: 8                            
                        [CHOICE]POSITION
========================================
SHIFT,F1( POINT  ) is pressed          
09-FEB-20 18:46 :58
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\100\%
                                  15/15 
   6:L @P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[1] 100% CNT100                
  14:J @P[2] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,FWD is pressed                   
09-FEB-20 18:46 :28
========================================
SHIFT,FWD is pressed                   
09-FEB-20 18:46 :20
========================================
Single step OFF                        
09-FEB-20 18:46 :18
========================================
SHIFT,STEP is pressed                  
09-FEB-20 18:46 :18
========================================
SHIFT,FWD is pressed                   
09-FEB-20 18:46 :12
========================================
SHIFT,FWD is pressed                   
09-FEB-20 18:46 :08
========================================
SHIFT,FWD is pressed                   
09-FEB-20 18:46 :06
========================================
R E S E T                              
                                       
                              00000000 
09-FEB-20 18:46 :04
========================================
SYST-039 Operation mode T2 Selected    
                                       
                                       
SERVO                         00110110 
09-FEB-20 18:46 :04
========================================
Single step ON                         
09-FEB-20 18:46 :02
========================================
STEP is pressed                        
09-FEB-20 18:46 :02
========================================
R E S E T                              
                                       
                              00000000 
09-FEB-20 18:44 :36
========================================
Menu changed 'MULTIROBOTTASK'          
09-FEB-20 18:44 :26
========================================
R E S E T                              
                                       
                              00000000 
09-FEB-20 18:44 :26
========================================
Power failure recovery                 
09-FEB-20 18:44 :12
========================================
R E S E T                              
                                       
                              00000000 
09-FEB-20 09:08 :16
========================================
SYST-040 Operation mode AUTO Selected  
                                       
                                       
SERVO                         00110110 
09-FEB-20 09:08 :16
========================================
SYST-043 TP disabled in T1/T2 mode     
                                       
                                       
STOP.L                        00000110 
09-FEB-20 09:08 :16
========================================
SHIFT,FWD is pressed                   
09-FEB-20 09:07 :44
========================================
Single step OFF                        
09-FEB-20 09:07 :42
========================================
SHIFT,STEP is pressed                  
09-FEB-20 09:07 :42
========================================
SHIFT,FWD is pressed                   
09-FEB-20 09:07 :40
========================================
SHIFT,FWD is pressed                   
09-FEB-20 09:07 :40
========================================
SHIFT,FWD is pressed                   
09-FEB-20 09:07 :36
========================================
SHIFT,FWD is pressed                   
09-FEB-20 09:07 :30
========================================
R E S E T                              
                                       
                              00000000 
09-FEB-20 09:07 :28
========================================
SYST-039 Operation mode T2 Selected    
                                       
                                       
SERVO                         00110110 
09-FEB-20 09:07 :28
========================================
Menu changed 'MULTIROBOTTASK'          
09-FEB-20 09:07 :26
========================================
ENTER is pressed                       
09-FEB-20 09:07 :26
========================================
R E S E T                              
                                       
                              00000000 
09-FEB-20 09:06 :16
========================================
Override 100%                          
09-FEB-20 09:06 :14
========================================
Menu changed 'Select'                  
09-FEB-20 09:06 :06
========================================
R E S E T                              
                                       
                              00000000 
09-FEB-20 09:06 :06
========================================
Power failure recovery                 
09-FEB-20 09:05 :54
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:43 :10
========================================
FILE 'MC:\XXXXXLED.GIF' is saved       
29-JAN-20 23:43 :10
========================================
FILE 'MC:\UPDTLOG.LS' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\UPDATES.DAT' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\TPRECKL.VR' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\TPREC.TP' is saved           
29-JAN-20 23:43 :10
========================================
FILE 'MC:\TPEINS.XML' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SYSVARS.SV' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SYSUIF.SV' is saved          
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SYSSERVO.SV' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SYSPASS.SV' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SYSMAST.SV' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SYSMACRO.SV' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SYSHOST.SV' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SYSFSAC.SV' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SYSFRAME.SV' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SUMMARY.DG' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\STRREG.VR' is saved          
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SPACER.GIF' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SHADOW.DG' is saved          
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SENDSYSV.TP' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SENDEVNT.TP' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\SENDDATA.TP' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\REQMENU.TP' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\REDLED.GIF' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\PSRBWLD.CM' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\PRO_MOV2.TP' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\POSREG.VR' is saved          
29-JAN-20 23:43 :10
========================================
FILE 'MC:\PBUTTON.GIF' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\PANEL4.STM' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\PANEL4.DT' is saved          
29-JAN-20 23:43 :10
========================================
FILE 'MC:\PANEL3.STM' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\PANEL3.DT' is saved          
29-JAN-20 23:43 :10
========================================
FILE 'MC:\PANEL2.STM' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\PANEL2.DT' is saved          
29-JAN-20 23:43 :10
========================================
FILE 'MC:\PANEL1.STM' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\PANEL1.DT' is saved          
29-JAN-20 23:43 :10
========================================
FILE 'MC:\OTEMGRUN.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\OTEMGMON.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\ORDERFIL.DAT' is saved       
29-JAN-20 23:43 :10
========================================
FILE 'MC:\NUMREG.VR' is saved          
29-JAN-20 23:43 :10
========================================
FILE 'MC:\NTDAQ.VR' is saved           
29-JAN-20 23:43 :10
========================================
FILE 'MC:\NORMM61C.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\NO03M61C.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\NBUTTON.GIF' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\MULTIROBOTTASK.TP' is saved  
29-JAN-20 23:43 :10
========================================
FILE 'MC:\MIXLOGIC.SV' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\MEM_PORT.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\MEMCHECK.DG' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\M61C.DT' is saved            
29-JAN-20 23:43 :10
========================================
FILE 'MC:\M10SET10.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\M10SET06.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\M10SET03.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\LOGBOOK.LS' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MDS1:\LOGBOOK.LS' is saved       
29-JAN-20 23:43 :10
========================================
FILE 'MC:\IOSTATUS.CM' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\HTTPKCL.VR' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\HTCOLREC.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\HOME_IO.TP' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\HIST.LS' is saved            
29-JAN-20 23:43 :10
========================================
FILE 'MC:\HIGHM61C.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\HI03M61C.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\GREENLED.GIF' is saved       
29-JAN-20 23:43 :10
========================================
FILE 'MC:\GETDATA.TP' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\GEMDATA.VR' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\FTPLOG.DG' is saved          
29-JAN-20 23:43 :10
========================================
FILE 'MC:\FRAMEVAR.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\ETHERNET.DG' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRSYS.LS' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MDS7:\ERRSYS.LS' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRPWD.LS' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MDS6:\ERRPWD.LS' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRMOT.LS' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MDS5:\ERRMOT.LS' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRHIST.LS' is saved         
29-JAN-20 23:43 :08
========================================
FILE 'MDS4:\ERRHIST.LS' is saved       
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERREXT.LS' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MDS3:\ERREXT.LS' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRCURR.LS' is saved         
29-JAN-20 23:43 :08
========================================
FILE 'MDS2:\ERRCURR.LS' is saved       
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRCOMM.LS' is saved         
29-JAN-20 23:43 :08
========================================
FILE 'MDS1:\ERRCOMM.LS' is saved       
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRAPP.LS' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MDS0:\ERRAPP.LS' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRALL.LS' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MDS9:\ERRALL.LS' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRACT.LS' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MDS8:\ERRACT.LS' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DIOCFGSV.IO' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DF_MOTN0.DF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DF_LOGI6.DF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DF_LOGI5.DF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DF_LOGI4.DF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DF_LOGI3.DF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DF_LOGI2.DF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DF_LOGI1.DF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSVRFY3.DG' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSVRFY2.DG' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSVRFY1.DG' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSVRFY.DG' is saved         
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSDIFF.DG' is saved         
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSCHGD3.DG' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSCHGD2.DG' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSCHGD1.DG' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DARKLED.GIF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\CONSLOG.DG' is saved         
29-JAN-20 23:43 :08
========================================
FILE 'MC:\CELLIO.SV' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MC:\BACKDATE.DT' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ATERRJOB.VR' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\AMBERLED.GIF' is saved       
29-JAN-20 23:43 :08
========================================
FILE 'MC:\-BCKEDT-.TP' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\-BCKED9-.TP' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\-BCKED8-.TP' is saved        
29-JAN-20 23:43 :08
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:42 :58
========================================
FILE 'MC:\XXXXXLED.GIF' is saved       
29-JAN-20 23:42 :58
========================================
FILE 'MC:\UPDTLOG.LS' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\UPDATES.DAT' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\TPRECKL.VR' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\TPREC.TP' is saved           
29-JAN-20 23:42 :58
========================================
FILE 'MC:\TPEINS.XML' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSVARS.SV' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSUIF.SV' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSSERVO.SV' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSPASS.SV' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSMAST.SV' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSMACRO.SV' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSHOST.SV' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSFSAC.SV' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSFRAME.SV' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SUMMARY.DG' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\STRREG.VR' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SPACER.GIF' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SHADOW.DG' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SENDSYSV.TP' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SENDEVNT.TP' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SENDDATA.TP' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\REQMENU.TP' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\REDLED.GIF' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PSRBWLD.CM' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PRO_MOV2.TP' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\POSREG.VR' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PBUTTON.GIF' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL4.STM' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL4.DT' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL3.STM' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL3.DT' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL2.STM' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL2.DT' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL1.STM' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL1.DT' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\OTEMGRUN.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\OTEMGMON.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\ORDERFIL.DAT' is saved       
29-JAN-20 23:42 :58
========================================
FILE 'MC:\NUMREG.VR' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\NTDAQ.VR' is saved           
29-JAN-20 23:42 :58
========================================
FILE 'MC:\NORMM61C.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\NO03M61C.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\NBUTTON.GIF' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\MULTIROBOTTASK.TP' is saved  
29-JAN-20 23:42 :58
========================================
FILE 'MC:\MIXLOGIC.SV' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\MEM_PORT.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\MEMCHECK.DG' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\M61C.DT' is saved            
29-JAN-20 23:42 :58
========================================
FILE 'MC:\M10SET10.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\M10SET06.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\M10SET03.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\LOGBOOK.LS' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MDS0:\LOGBOOK.LS' is saved       
29-JAN-20 23:42 :58
========================================
FILE 'MC:\IOSTATUS.CM' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\HTTPKCL.VR' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\HTCOLREC.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\HOME_IO.TP' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\HIST.LS' is saved            
29-JAN-20 23:42 :58
========================================
FILE 'MC:\HIGHM61C.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\HI03M61C.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\GREENLED.GIF' is saved       
29-JAN-20 23:42 :58
========================================
FILE 'MC:\GETDATA.TP' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\GEMDATA.VR' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\FTPLOG.DG' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\FRAMEVAR.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\ETHERNET.DG' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\ERRSYS.LS' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MDS6:\ERRSYS.LS' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRPWD.LS' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MDS5:\ERRPWD.LS' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRMOT.LS' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MDS4:\ERRMOT.LS' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRHIST.LS' is saved         
29-JAN-20 23:42 :56
========================================
FILE 'MDS3:\ERRHIST.LS' is saved       
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERREXT.LS' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MDS2:\ERREXT.LS' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRCURR.LS' is saved         
29-JAN-20 23:42 :56
========================================
FILE 'MDS1:\ERRCURR.LS' is saved       
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRCOMM.LS' is saved         
29-JAN-20 23:42 :56
========================================
FILE 'MDS0:\ERRCOMM.LS' is saved       
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRAPP.LS' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MDS9:\ERRAPP.LS' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRALL.LS' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MDS8:\ERRALL.LS' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRACT.LS' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MDS7:\ERRACT.LS' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DIOCFGSV.IO' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DF_MOTN0.DF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DF_LOGI6.DF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DF_LOGI5.DF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DF_LOGI4.DF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DF_LOGI3.DF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DF_LOGI2.DF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DF_LOGI1.DF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSVRFY3.DG' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSVRFY2.DG' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSVRFY1.DG' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSVRFY.DG' is saved         
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSDIFF.DG' is saved         
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSCHGD3.DG' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSCHGD2.DG' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSCHGD1.DG' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DARKLED.GIF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\CONSLOG.DG' is saved         
29-JAN-20 23:42 :56
========================================
FILE 'MC:\CELLIO.SV' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MC:\BACKDATE.DT' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ATERRJOB.VR' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\AMBERLED.GIF' is saved       
29-JAN-20 23:42 :56
========================================
FILE 'MC:\-BCKEDT-.TP' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\-BCKED9-.TP' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\-BCKED8-.TP' is saved        
29-JAN-20 23:42 :56
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:42 :50
========================================
SYST-040 Operation mode AUTO Selected  
                                       
                                       
SERVO                         00110110 
29-JAN-20 23:42 :50
========================================
Menu changed 'Select'                  
29-JAN-20 23:42 :46
========================================
SELECT is pressed                      
29-JAN-20 23:42 :46
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:42 :08
========================================
'   YES' is selected in ' The cursor i
s on a different' window              
29-JAN-20 23:42 :08
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 13   \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
     ________________________________15 
   6:|The cursor is on a different  |   
   7:|line from where the program   |   
   8:|PAUSED [13].                  |   
   9:|Are you sure you want to run  |   
  10:|from this line ?              |   
  11:|                              |   
  12:|   \\\\YES\\\\       NO       |   
  13:|______________________________|   
\\14:J  P[2] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:42 :06
========================================
'Cnt' is selected in 'Motion Modify' me
nu                                     
29-JAN-20 23:42 :00
--Screen image--------------------------
                                        
Motion\Modify\\\\\\\\\\\\\\\\WORLD\\40\%
\1\Fine\\\\\\\\\\\\\5                   
 2 Cnt              6                   
                    7                   
                    8                   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                       PAUSED     14/15 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J @P[1] 100% CNT100                
  14:J  P[2] 100% FINE                  
[End]                                   
Select item                             
                        [CHOICE]        
========================================
F4([CHOICE]) is pressed                
29-JAN-20 23:41 :58
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 13   \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                       PAUSED     14/15 
   6:L  P[2] 2000mm/sec CNT0            
   7:J @P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J @P[1] 100% CNT100                
  14:J  P[2] 100% FINE                  
[End]                                   
                                        
                        [CHOICE]        
========================================
2 is entered                           
29-JAN-20 23:41 :54
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 13   \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                       PAUSED     14/15 
   6:L  P[2] 2000mm/sec CNT0            
   7:J @P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J @P[1] 100% CNT100                
  14:J @P[8] 10] 100% FINE              
[End]                                   
Old Value: 8                            
                        [CHOICE]POSITION
========================================
'1 J P[] 100% FINE' is selected in 'De
fault Motion' menu                    
29-JAN-20 23:41 :40
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\40\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                       PAUSED     14/14 
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J @P[1] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:41 :34
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 13   \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                       PAUSED     14/14 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J @P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J @P[1] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
F5(   NO   ) is pressed                
29-JAN-20 23:41 :32
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 13   \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                       PAUSED     13/14 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J @P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
\\13:J @P[1] 100% CNT100                
[End]                                   
Set new id?                             
                          YES      NO   
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
29-JAN-20 23:41 :28
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\40\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                       PAUSED     13/14 
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
\\13:J @P[1] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:41 :26
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 13   \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                       PAUSED     13/14 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J @P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
\\13:J @P[1] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:41 :10
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:41 :02
========================================
RESET is pressed                       
29-JAN-20 23:41 :02
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:41 :02
========================================
SHIFT,RESET is pressed                 
29-JAN-20 23:41 :02
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:41 :02
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:40 :58
========================================
FILE 'MC:\XXXXXLED.GIF' is saved       
29-JAN-20 23:40 :58
========================================
FILE 'MC:\UPDTLOG.LS' is saved         
29-JAN-20 23:40 :58
========================================
FILE 'MC:\UPDATES.DAT' is saved        
29-JAN-20 23:40 :58
========================================
FILE 'MC:\TPRECKL.VR' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\TPREC.TP' is saved           
29-JAN-20 23:40 :56
========================================
FILE 'MC:\TPEINS.XML' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSVARS.SV' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSUIF.SV' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSSERVO.SV' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSPASS.SV' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSMAST.SV' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSMACRO.SV' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSHOST.SV' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSFSAC.SV' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSFRAME.SV' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SUMMARY.DG' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\STRREG.VR' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SPACER.GIF' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SHADOW.DG' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SENDSYSV.TP' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SENDEVNT.TP' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SENDDATA.TP' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\REQMENU.TP' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\REDLED.GIF' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PSRBWLD.CM' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PRO_MOV2.TP' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\POSREG.VR' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PBUTTON.GIF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL4.STM' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL4.DT' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL3.STM' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL3.DT' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL2.STM' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL2.DT' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL1.STM' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL1.DT' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\OTEMGRUN.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\OTEMGMON.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ORDERFIL.DAT' is saved       
29-JAN-20 23:40 :56
========================================
FILE 'MC:\NUMREG.VR' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\NTDAQ.VR' is saved           
29-JAN-20 23:40 :56
========================================
FILE 'MC:\NORMM61C.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\NO03M61C.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\NBUTTON.GIF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\MULTIROBOTTASK.TP' is saved  
29-JAN-20 23:40 :56
========================================
FILE 'MC:\MIXLOGIC.SV' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\MEM_PORT.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\MEMCHECK.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\M61C.DT' is saved            
29-JAN-20 23:40 :56
========================================
FILE 'MC:\M10SET10.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\M10SET06.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\M10SET03.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\LOGBOOK.LS' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MDS9:\LOGBOOK.LS' is saved       
29-JAN-20 23:40 :56
========================================
FILE 'MC:\IOSTATUS.CM' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\HTTPKCL.VR' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\HTCOLREC.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\HOME_IO.TP' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\HIST.LS' is saved            
29-JAN-20 23:40 :56
========================================
FILE 'MC:\HIGHM61C.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\HI03M61C.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\GREENLED.GIF' is saved       
29-JAN-20 23:40 :56
========================================
FILE 'MC:\GETDATA.TP' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\GEMDATA.VR' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\FTPLOG.DG' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\FRAMEVAR.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ETHERNET.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRSYS.LS' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MDS5:\ERRSYS.LS' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRPWD.LS' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MDS4:\ERRPWD.LS' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRMOT.LS' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MDS3:\ERRMOT.LS' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRHIST.LS' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MDS2:\ERRHIST.LS' is saved       
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERREXT.LS' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MDS1:\ERREXT.LS' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRCURR.LS' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MDS0:\ERRCURR.LS' is saved       
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRCOMM.LS' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MDS9:\ERRCOMM.LS' is saved       
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRAPP.LS' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MDS8:\ERRAPP.LS' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRALL.LS' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MDS7:\ERRALL.LS' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRACT.LS' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MDS6:\ERRACT.LS' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DIOCFGSV.IO' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DF_MOTN0.DF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DF_LOGI6.DF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DF_LOGI5.DF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DF_LOGI4.DF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DF_LOGI3.DF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DF_LOGI2.DF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DF_LOGI1.DF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSVRFY3.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSVRFY2.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSVRFY1.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSVRFY.DG' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSDIFF.DG' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSCHGD3.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSCHGD2.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSCHGD1.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DARKLED.GIF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\CONSLOG.DG' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\CELLIO.SV' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\BACKDATE.DT' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ATERRJOB.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\AMBERLED.GIF' is saved       
29-JAN-20 23:40 :56
========================================
FILE 'MC:\-BCKEDT-.TP' is saved        
29-JAN-20 23:40 :54
========================================
FILE 'MC:\-BCKED9-.TP' is saved        
29-JAN-20 23:40 :54
========================================
FILE 'MC:\-BCKED8-.TP' is saved        
29-JAN-20 23:40 :54
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:40 :52
========================================
Single step ON                         
29-JAN-20 23:40 :30
========================================
STEP is pressed                        
29-JAN-20 23:40 :30
========================================
PREV is pressed                        
29-JAN-20 23:40 :18
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
29-JAN-20 23:40 :12
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\40\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                   1/14 
\\\1:J @P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:40 :06
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                   1/14 
\\\1:J @P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J @P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
                                        
 POINT                          TOUCHUP>
========================================
Single step OFF                        
29-JAN-20 23:39 :06
========================================
STEP is pressed                        
29-JAN-20 23:39 :06
========================================
Single step ON                         
29-JAN-20 23:39 :04
========================================
STEP is pressed                        
29-JAN-20 23:39 :04
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:38 :58
========================================
Single step OFF                        
29-JAN-20 23:38 :56
========================================
STEP is pressed                        
29-JAN-20 23:38 :56
========================================
1 is entered                           
29-JAN-20 23:38 :52
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  13/14 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[2] 10] 100% CNT100            
[End]                                   
Old Value: 2                            
                        [CHOICE]POSITION
========================================
2 is entered                           
29-JAN-20 23:38 :50
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  13/14 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J @P[8] 10] 100% CNT100            
[End]                                   
Old Value: 8                            
                        [CHOICE]POSITION
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
29-JAN-20 23:38 :42
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\40\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3 L P[] 100mm/sec FINE                  
4\L\P[]\100mm/sec\CNT100\\\\\\\\\\\\\\\ 
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  13/13 
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:38 :38
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  13/13 
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
ENTER is pressed                       
29-JAN-20 23:38 :32
========================================
0 is entered                           
29-JAN-20 23:38 :32
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  12/13 
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2000 is entered                        
29-JAN-20 23:38 :30
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  12/13 
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 100mmm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
5 is entered                           
29-JAN-20 23:38 :22
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  12/13 
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L @P[8] 10] 100mm/sec CNT100       
[End]                                   
Old Value: 8                            
                        [CHOICE]POSITION
========================================
'4 L P[] 100mm/sec CNT100' is selected 
in 'Default Motion' menu               
29-JAN-20 23:38 :18
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\40\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  12/12 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
I/O              
========================================
 SO[    1]    ON  -> OFF
Tick:   782233
TB:     1674553943
09-FEB-20 18:58 :04
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   782232
TB:     1674553743
09-FEB-20 18:58 :04
========================================
Aborted      MULTIROBOTTASK,   0       
   (TASK:1,TB:1674464283)              
09-FEB-20 18:58 :04
========================================
Run FWD      MULTIROBOTTASK,  20       
   (TASK:1,TB:1670463849)              
09-FEB-20 18:58 :04
========================================
Run FWD      MULTIROBOTTASK,  19       
   (TASK:1,TB:1668493930)              
09-FEB-20 18:58 :02
========================================
Run FWD      MULTIROBOTTASK,  18       
   (TASK:1,TB:1667010262)              
09-FEB-20 18:58 :02
========================================
Run FWD      MULTIROBOTTASK,  17       
   (TASK:1,TB:1665770859)              
09-FEB-20 18:58 :02
========================================
Run FWD      MULTIROBOTTASK,  16       
   (TASK:1,TB:1664600947)              
09-FEB-20 18:58 :00
========================================
Run FWD      MULTIROBOTTASK,  15       
   (TASK:1,TB:1662144825)              
09-FEB-20 18:58 :00
========================================
Run FWD      MULTIROBOTTASK,  14       
   (TASK:1,TB:1659576412)              
09-FEB-20 18:57 :58
========================================
Run FWD      MULTIROBOTTASK,  13       
   (TASK:1,TB:1657559208)              
09-FEB-20 18:57 :58
========================================
Run FWD      MULTIROBOTTASK,  12       
   (TASK:1,TB:1655442555)              
09-FEB-20 18:57 :56
========================================
Run FWD      MULTIROBOTTASK,  11       
   (TASK:1,TB:1654289713)              
09-FEB-20 18:57 :56
========================================
Run FWD      MULTIROBOTTASK,  10       
   (TASK:1,TB:1653115197)              
09-FEB-20 18:57 :56
========================================
Run FWD      MULTIROBOTTASK,   9       
   (TASK:1,TB:1649688729)              
09-FEB-20 18:57 :54
========================================
Run FWD      MULTIROBOTTASK,   8       
   (TASK:1,TB:1647145232)              
09-FEB-20 18:57 :52
========================================
Run FWD      MULTIROBOTTASK,   7       
   (TASK:1,TB:1645116927)              
09-FEB-20 18:57 :52
========================================
Run FWD      MULTIROBOTTASK,   6       
   (TASK:1,TB:1642945113)              
09-FEB-20 18:57 :50
========================================
Run FWD      MULTIROBOTTASK,   5       
   (TASK:1,TB:1641660673)              
09-FEB-20 18:57 :50
========================================
Run FWD      MULTIROBOTTASK,   4       
   (TASK:1,TB:1640435049)              
09-FEB-20 18:57 :50
========================================
Run FWD      MULTIROBOTTASK,   3       
   (TASK:1,TB:1636793214)              
09-FEB-20 18:57 :48
========================================
Run FWD      MULTIROBOTTASK,   2       
   (TASK:1,TB:1634079674)              
09-FEB-20 18:57 :46
========================================
 SO[    1]    OFF -> ON 
Tick:   764407
TB:     1631739787
09-FEB-20 18:57 :46
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   764406
TB:     1631736515
09-FEB-20 18:57 :46
========================================
Run FWD      MULTIROBOTTASK,   1       
   (TASK:1,TB:1631666397)              
09-FEB-20 18:57 :46
========================================
 SO[    3]    ON  -> OFF
Tick:   383383
TB:     742441987
09-FEB-20 18:51 :10
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   383382
TB:     742439789
09-FEB-20 18:51 :10
========================================
 SO[    3]    OFF -> ON 
Tick:   383161
TB:     741908687
09-FEB-20 18:51 :08
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   383160
TB:     741907190
09-FEB-20 18:51 :08
========================================
 SO[    7]    OFF -> ON 
Tick:   383095
TB:     741698485
09-FEB-20 18:51 :08
========================================
 UO[    8]    OFF -> ON 
Tick:   383094
TB:     741696098
09-FEB-20 18:51 :08
========================================
 SO[    3]    ON  -> OFF
Tick:   382645
TB:     740660393
09-FEB-20 18:51 :08
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   382644
TB:     740659532
09-FEB-20 18:51 :08
========================================
 SO[    3]    OFF -> ON 
Tick:   382423
TB:     740074002
09-FEB-20 18:51 :08
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   382422
TB:     740072645
09-FEB-20 18:51 :08
========================================
 SO[    7]    ON  -> OFF
Tick:   382393
TB:     739952985
09-FEB-20 18:51 :08
========================================
 UO[    8]    ON  -> OFF
Tick:   382392
TB:     739951960
09-FEB-20 18:51 :08
========================================
 SO[    1]    ON  -> OFF
Tick:   118297
TB:     121463412
09-FEB-20 18:46 :32
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   118296
TB:     121462542
09-FEB-20 18:46 :32
========================================
Aborted      MULTIROBOTTASK,   0       
   (TASK:1,TB:121364828)               
09-FEB-20 18:46 :32
========================================
Run FWD      MULTIROBOTTASK,  14       
   (TASK:1,TB:120562272)               
09-FEB-20 18:46 :32
========================================
Run FWD      MULTIROBOTTASK,  13       
   (TASK:1,TB:120062616)               
09-FEB-20 18:46 :32
========================================
Run FWD      MULTIROBOTTASK,  12       
   (TASK:1,TB:119477688)               
09-FEB-20 18:46 :32
========================================
Run FWD      MULTIROBOTTASK,  11       
   (TASK:1,TB:119141434)               
09-FEB-20 18:46 :30
========================================
Run FWD      MULTIROBOTTASK,  10       
   (TASK:1,TB:118805973)               
09-FEB-20 18:46 :30
========================================
Run FWD      MULTIROBOTTASK,   9       
   (TASK:1,TB:118097178)               
09-FEB-20 18:46 :30
========================================
Run FWD      MULTIROBOTTASK,   8       
   (TASK:1,TB:117599783)               
09-FEB-20 18:46 :30
========================================
Run FWD      MULTIROBOTTASK,   7       
   (TASK:1,TB:117077514)               
09-FEB-20 18:46 :30
========================================
Run FWD      MULTIROBOTTASK,   6       
   (TASK:1,TB:116523812)               
09-FEB-20 18:46 :30
========================================
Run FWD      MULTIROBOTTASK,   5       
   (TASK:1,TB:116147128)               
09-FEB-20 18:46 :30
========================================
Run FWD      MULTIROBOTTASK,   4       
   (TASK:1,TB:115797684)               
09-FEB-20 18:46 :30
========================================
Run FWD      MULTIROBOTTASK,   3       
   (TASK:1,TB:115081179)               
09-FEB-20 18:46 :30
========================================
Run FWD      MULTIROBOTTASK,   2       
   (TASK:1,TB:114548461)               
09-FEB-20 18:46 :28
========================================
 SO[    1]    OFF -> ON 
Tick:   115255
TB:     114044786
09-FEB-20 18:46 :28
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   115254
TB:     114042684
09-FEB-20 18:46 :28
========================================
Run FWD      MULTIROBOTTASK,   1       
   (TASK:1,TB:114010500)               
09-FEB-20 18:46 :28
========================================
 SO[    1]    ON  -> OFF
Tick:   109081
TB:     99801909
09-FEB-20 18:46 :22
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   109080
TB:     99800286
09-FEB-20 18:46 :22
========================================
Aborted      MULTIROBOTTASK,   0       
   (TASK:1,TB:99715646)                
09-FEB-20 18:46 :22
========================================
Run FWD      MULTIROBOTTASK,  14       
   (TASK:1,TB:98919688)                
09-FEB-20 18:46 :22
========================================
Run FWD      MULTIROBOTTASK,  13       
   (TASK:1,TB:98395467)                
09-FEB-20 18:46 :22
========================================
Run FWD      MULTIROBOTTASK,  12       
   (TASK:1,TB:97814758)                
09-FEB-20 18:46 :22
========================================
Run FWD      MULTIROBOTTASK,  11       
   (TASK:1,TB:97460839)                
09-FEB-20 18:46 :22
========================================
Run FWD      MULTIROBOTTASK,  10       
   (TASK:1,TB:97088643)                
09-FEB-20 18:46 :22
========================================
Run FWD      MULTIROBOTTASK,   9       
   (TASK:1,TB:96411955)                
09-FEB-20 18:46 :20
========================================
Run FWD      MULTIROBOTTASK,   8       
   (TASK:1,TB:95892122)                
09-FEB-20 18:46 :20
========================================
Run FWD      MULTIROBOTTASK,   7       
   (TASK:1,TB:95396709)                
09-FEB-20 18:46 :20
========================================
Run FWD      MULTIROBOTTASK,   6       
   (TASK:1,TB:94843249)                
09-FEB-20 18:46 :20
========================================
Run FWD      MULTIROBOTTASK,   5       
   (TASK:1,TB:94437482)                
09-FEB-20 18:46 :20
========================================
Run FWD      MULTIROBOTTASK,   4       
   (TASK:1,TB:94064215)                
09-FEB-20 18:46 :20
========================================
Run FWD      MULTIROBOTTASK,   3       
   (TASK:1,TB:93373149)                
09-FEB-20 18:46 :20
========================================
 SO[    1]    OFF -> ON 
Tick:   106231
TB:     92859484
09-FEB-20 18:46 :20
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   106230
TB:     92856960
09-FEB-20 18:46 :20
========================================
Run FWD      MULTIROBOTTASK,   2       
   (TASK:1,TB:92853414)                
09-FEB-20 18:46 :20
========================================
 SO[    1]    ON  -> OFF
Tick:   100213
TB:     78919314
09-FEB-20 18:46 :12
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   100212
TB:     78918389
09-FEB-20 18:46 :12
========================================
Paused       MULTIROBOTTASK,   1       
   (TASK:1,TB:78809007)                
09-FEB-20 18:46 :12
========================================
 SO[    1]    OFF -> ON 
Tick:   99865
TB:     78078894
09-FEB-20 18:46 :12
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   99864
TB:     78077541
09-FEB-20 18:46 :12
========================================
Run FWD      MULTIROBOTTASK,   1       
   (TASK:1,TB:77970807)                
09-FEB-20 18:46 :12
========================================
 SO[    1]    ON  -> OFF
Tick:   96121
TB:     69402438
09-FEB-20 18:46 :08
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   96120
TB:     69399958
09-FEB-20 18:46 :08
========================================
Aborted      MULTIROBOTTASK,   0       
   (TASK:1,TB:69328016)                
09-FEB-20 18:46 :08
========================================
 SO[    1]    OFF -> ON 
Tick:   96085
TB:     69291703
09-FEB-20 18:46 :08
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   96084
TB:     69291086
09-FEB-20 18:46 :08
========================================
 SO[    1]    ON  -> OFF
Tick:   94681
TB:     66008699
09-FEB-20 18:46 :08
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   94680
TB:     66008560
09-FEB-20 18:46 :08
========================================
Paused       MULTIROBOTTASK,  14       
   (TASK:1,TB:65917780)                
09-FEB-20 18:46 :08
========================================
 SO[    1]    OFF -> ON 
Tick:   94357
TB:     65256156
09-FEB-20 18:46 :06
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   94356
TB:     65254596
09-FEB-20 18:46 :06
========================================
Run FWD      MULTIROBOTTASK,  14       
   (TASK:1,TB:64896173)                
09-FEB-20 18:46 :06
========================================
 SO[    3]    ON  -> OFF
Tick:   92407
TB:     60418703
09-FEB-20 18:46 :04
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   92406
TB:     60416482
09-FEB-20 18:46 :04
========================================
 SO[    3]    OFF -> ON 
Tick:   92149
TB:     59784517
09-FEB-20 18:46 :04
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   92148
TB:     59783691
09-FEB-20 18:46 :04
========================================
 SO[    7]    OFF -> ON 
Tick:   92119
TB:     59688561
09-FEB-20 18:46 :04
========================================
 UO[    8]    OFF -> ON 
Tick:   92118
TB:     59687655
09-FEB-20 18:46 :04
========================================
 UO[    2]    OFF -> ON 
Tick:   408
TB:     -159541042
09-FEB-20 18:44 :26
========================================
 AO[    3]    0
 AO[    3]    0
 AO[    5]    0
 AO[    5]    0
 AO[    7]    0
 UI[    1]    ON 
 UI[    2]    ON 
 UI[    3]    ON 
 UI[    4]    OFF
 UI[    5]    OFF
 UI[    6]    OFF
 UI[    7]    OFF
 UI[    8]    ON 
 UI[   17]    OFF
 UI[   18]    OFF
 UI[   19]    OFF
 UI[   20]    OFF
 UI[   21]    OFF
 UI[   22]    OFF
 UI[   23]    OFF
 UI[   24]    OFF
 UI[   33]    OFF
 UI[   34]    OFF
 UO[    1]    OFF
 UO[    2]    OFF
 UO[    3]    OFF
 UO[    4]    OFF
 UO[    5]    OFF
 UO[    6]    OFF
 UO[    7]    OFF
 UO[    8]    OFF
 UO[   17]    OFF
 UO[   18]    OFF
 UO[   19]    OFF
 UO[   20]    OFF
 UO[   21]    OFF
 UO[   22]    OFF
 UO[   23]    OFF
 UO[   24]    OFF
 UO[   33]    OFF
 UO[   34]    OFF
 UO[   35]    OFF
 UO[   36]    OFF
Tick:   234
TB:     -161857760
09-FEB-20 18:44 :26
========================================
 AI[   17]    0
 AI[   13]    0
 AI[   15]    0
 AI[   17]    0
 AI[   19]    0
 AI[   21]    0
 AI[   23]    0
 AO[    1]    0
Tick:   233
TB:     -161857835
09-FEB-20 18:44 :26
========================================
 AI[    7]    0
 AI[    9]    0
 AI[   11]    0
 AI[    7]    0
 AI[    9]    0
 AI[   11]    0
 AI[   13]    0
 AI[   15]    0
Tick:   232
TB:     -161876893
09-FEB-20 18:44 :26
========================================
 DO[   65]    OFF
 DO[   66]    OFF
 DO[   67]    OFF
 DO[   68]    OFF
 DO[   69]    OFF
 DO[   70]    OFF
 DO[   71]    OFF
 DO[   72]    OFF
 DO[   73]    OFF
 DO[   74]    OFF
 DO[   75]    OFF
 DO[   76]    OFF
 DO[   77]    OFF
 DO[   78]    OFF
 DO[   79]    OFF
 DO[   80]    OFF
 DO[   81]    OFF
 DO[   82]    OFF
 DO[   83]    OFF
 DO[   84]    OFF
 DO[   85]    OFF
 DO[   86]    OFF
 DO[   87]    OFF
 DO[   88]    OFF
 DO[   89]    OFF
 DO[   90]    OFF
 DO[   91]    OFF
 DO[   92]    OFF
 DO[   93]    OFF
 DO[   94]    OFF
 DO[   95]    OFF
 DO[   96]    OFF
 DO[   97]    OFF
 DO[   98]    OFF
 DO[   99]    OFF
 DO[  100]    OFF
 DO[  101]    OFF
 DO[  102]    OFF
 DO[  103]    OFF
 DO[  104]    OFF
 DO[  105]    OFF
 DO[  106]    OFF
 DO[  107]    OFF
 DO[  108]    OFF
 DO[  109]    OFF
 DO[  110]    OFF
 DO[  111]    OFF
 DO[  112]    OFF
 DO[  113]    OFF
 DO[  114]    OFF
 DO[  115]    OFF
 DO[  116]    OFF
 DO[  117]    OFF
 DO[  118]    OFF
 DO[  119]    OFF
 DO[  120]    OFF
 DO[  121]    OFF
 DO[  122]    OFF
 DO[  123]    OFF
 DO[  124]    OFF
 DO[  125]    OFF
 DO[  126]    OFF
 DO[  127]    OFF
 DO[  128]    OFF
 DO[  129]    OFF
 DO[  130]    OFF
 DO[  131]    OFF
 DO[  132]    OFF
 DO[  133]    OFF
 DO[  134]    OFF
 DO[  135]    OFF
 DO[  136]    OFF
 DO[  137]    OFF
 DO[  138]    OFF
 DO[  139]    OFF
 DO[  140]    OFF
 DO[  141]    OFF
 DO[  142]    OFF
 DO[  143]    OFF
 DO[  144]    OFF
 AI[    1]    0
 AI[    3]    0
 AI[    5]    0
Tick:   231
TB:     -161924832
09-FEB-20 18:44 :26
========================================
 DI[   81]    OFF
 DI[   82]    OFF
 DI[   83]    OFF
 DI[   84]    OFF
 DI[   85]    OFF
 DI[   86]    OFF
 DI[   87]    OFF
 DI[   88]    OFF
 DI[   89]    OFF
 DI[   90]    OFF
 DI[   91]    OFF
 DI[   92]    OFF
 DI[   93]    OFF
 DI[   94]    OFF
 DI[   95]    OFF
 DI[   96]    OFF
 DI[   97]    OFF
 DI[   98]    OFF
 DI[   99]    OFF
 DI[  100]    OFF
 DI[  101]    OFF
 DI[  102]    OFF
 DI[  103]    OFF
 DI[  104]    OFF
 DI[  105]    OFF
 DI[  106]    OFF
 DI[  107]    OFF
 DI[  108]    OFF
 DI[  109]    OFF
 DI[  110]    OFF
 DI[  111]    OFF
 DI[  112]    OFF
 DI[  113]    OFF
 DI[  114]    OFF
 DI[  115]    OFF
 DI[  116]    OFF
 DI[  117]    OFF
 DI[  118]    OFF
 DI[  119]    OFF
 DI[  120]    OFF
 DI[  121]    OFF
 DI[  122]    OFF
 DI[  123]    OFF
 DI[  124]    OFF
 DI[  125]    OFF
 DI[  126]    OFF
 DI[  127]    OFF
 DI[  128]    OFF
 DI[  129]    OFF
 DI[  130]    OFF
 DI[  131]    OFF
 DI[  132]    OFF
 DI[  133]    OFF
 DI[  134]    OFF
 DI[  135]    OFF
 DI[  136]    OFF
 DI[  137]    OFF
 DI[  138]    OFF
 DI[  139]    OFF
 DI[  140]    OFF
 DI[  141]    OFF
 DI[  142]    OFF
 DI[  143]    OFF
 DI[  144]    OFF
 DO[   21]    OFF
 DO[   22]    OFF
 DO[   23]    OFF
 DO[   24]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
 DO[   41]    OFF
 DO[   42]    OFF
 DO[   43]    OFF
 DO[   44]    OFF
 DO[   53]    OFF
 DO[   54]    OFF
 DO[   55]    OFF
 DO[   56]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   29]    OFF
 DO[   30]    OFF
 DO[   31]    OFF
 DO[   32]    OFF
 DO[   33]    OFF
 DO[   34]    OFF
 DO[   35]    OFF
 DO[   36]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
 DO[   41]    OFF
 DO[   42]    OFF
 DO[   43]    OFF
 DO[   44]    OFF
 DO[   45]    OFF
 DO[   46]    OFF
 DO[   47]    OFF
 DO[   48]    OFF
 DO[   49]    OFF
 DO[   50]    OFF
 DO[   51]    OFF
 DO[   52]    OFF
 DO[   53]    OFF
 DO[   54]    OFF
 DO[   55]    OFF
 DO[   56]    OFF
 DO[   57]    OFF
 DO[   58]    OFF
 DO[   59]    OFF
 DO[   60]    OFF
 DO[   61]    OFF
 DO[   62]    OFF
 DO[   63]    OFF
 DO[   64]    OFF
Tick:   230
TB:     -161924940
09-FEB-20 18:44 :26
========================================
 SI[    0]    ON 
 SI[    1]    OFF
 SI[    2]    ON 
 SI[    3]    ON 
 SI[    4]    OFF
 SI[    5]    OFF
 SI[    6]    OFF
 SI[    7]    OFF
 SI[    8]    OFF
 SI[    9]    OFF
 SI[   10]    OFF
 SI[   11]    OFF
 SI[   12]    OFF
 SI[   13]    OFF
 SI[   14]    OFF
 SI[   15]    OFF
 SO[    0]    OFF
 SO[    1]    OFF
 SO[    2]    OFF
 SO[    3]    OFF
 SO[    4]    OFF
 SO[    5]    OFF
 SO[    6]    OFF
 SO[    7]    OFF
 SO[    8]    OFF
 SO[    9]    OFF
 SO[   10]    OFF
 SO[   11]    OFF
 SO[   12]    OFF
 SO[   13]    OFF
 SO[   14]    OFF
 SO[   15]    OFF
 RI[    1]    OFF
 RI[    2]    OFF
 RI[    3]    OFF
 RI[    4]    OFF
 RI[    5]    OFF
 RI[    6]    OFF
 RI[    7]    OFF
 RI[    8]    OFF
 RO[    1]    OFF
 RO[    2]    OFF
 RO[    3]    OFF
 RO[    4]    OFF
 RO[    5]    OFF
 RO[    6]    OFF
 RO[    7]    OFF
 RO[    8]    OFF
 DI[   19]    OFF
 DI[   20]    OFF
 DI[   21]    OFF
 DI[   22]    OFF
 DI[   23]    OFF
 DI[   24]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   41]    OFF
 DI[   42]    OFF
 DI[   51]    OFF
 DI[   52]    OFF
 DI[   53]    OFF
 DI[   54]    OFF
 DI[   55]    OFF
 DI[   56]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   27]    OFF
 DI[   28]    OFF
 DI[   29]    OFF
 DI[   30]    OFF
 DI[   31]    OFF
 DI[   32]    OFF
 DI[   33]    OFF
 DI[   34]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   41]    OFF
 DI[   42]    OFF
 DI[   43]    OFF
 DI[   44]    OFF
 DI[   45]    OFF
 DI[   46]    OFF
 DI[   47]    OFF
 DI[   48]    OFF
 DI[   49]    OFF
 DI[   50]    OFF
 DI[   51]    OFF
 DI[   52]    OFF
 DI[   53]    OFF
 DI[   54]    OFF
 DI[   55]    OFF
 DI[   56]    OFF
 DI[   57]    OFF
 DI[   58]    OFF
 DI[   59]    OFF
 DI[   60]    OFF
 DI[   61]    OFF
 DI[   62]    OFF
 DI[   63]    OFF
 DI[   64]    OFF
 DI[   65]    OFF
 DI[   66]    OFF
 DI[   67]    OFF
 DI[   68]    OFF
 DI[   69]    OFF
 DI[   70]    OFF
 DI[   71]    OFF
 DI[   72]    OFF
 DI[   73]    OFF
 DI[   74]    OFF
 DI[   75]    OFF
 DI[   76]    OFF
 DI[   77]    OFF
 DI[   78]    OFF
 DI[   79]    OFF
 DI[   80]    OFF
Tick:   229
TB:     -161925158
09-FEB-20 18:44 :26
