ERRMOT.LS      Robot Name ROBOT 29-JAN-20 23:43     

1" 29-JAN-20 23:09 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
2" 29-JAN-20 18:35 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
3" 28-JAN-20 15:20 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
