LOGBOOK.LS     Robot Name ROBOT 29-JAN-20 23:43     

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Operation        
========================================
FILE 'MC:\IOSTATUS.CM' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\HTTPKCL.VR' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\HTCOLREC.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\HOME_IO.TP' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\HIST.LS' is saved            
29-JAN-20 23:43 :10
========================================
FILE 'MC:\HIGHM61C.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\HI03M61C.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\GREENLED.GIF' is saved       
29-JAN-20 23:43 :10
========================================
FILE 'MC:\GETDATA.TP' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\GEMDATA.VR' is saved         
29-JAN-20 23:43 :10
========================================
FILE 'MC:\FTPLOG.DG' is saved          
29-JAN-20 23:43 :10
========================================
FILE 'MC:\FRAMEVAR.VR' is saved        
29-JAN-20 23:43 :10
========================================
FILE 'MC:\ETHERNET.DG' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRSYS.LS' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MDS7:\ERRSYS.LS' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRPWD.LS' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MDS6:\ERRPWD.LS' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRMOT.LS' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MDS5:\ERRMOT.LS' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRHIST.LS' is saved         
29-JAN-20 23:43 :08
========================================
FILE 'MDS4:\ERRHIST.LS' is saved       
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERREXT.LS' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MDS3:\ERREXT.LS' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRCURR.LS' is saved         
29-JAN-20 23:43 :08
========================================
FILE 'MDS2:\ERRCURR.LS' is saved       
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRCOMM.LS' is saved         
29-JAN-20 23:43 :08
========================================
FILE 'MDS1:\ERRCOMM.LS' is saved       
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRAPP.LS' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MDS0:\ERRAPP.LS' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRALL.LS' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MDS9:\ERRALL.LS' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ERRACT.LS' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MDS8:\ERRACT.LS' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DIOCFGSV.IO' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DF_MOTN0.DF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DF_LOGI6.DF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DF_LOGI5.DF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DF_LOGI4.DF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DF_LOGI3.DF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DF_LOGI2.DF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DF_LOGI1.DF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSVRFY3.DG' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSVRFY2.DG' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSVRFY1.DG' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSVRFY.DG' is saved         
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSDIFF.DG' is saved         
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSCHGD3.DG' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSCHGD2.DG' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DCSCHGD1.DG' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\DARKLED.GIF' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\CONSLOG.DG' is saved         
29-JAN-20 23:43 :08
========================================
FILE 'MC:\CELLIO.SV' is saved          
29-JAN-20 23:43 :08
========================================
FILE 'MC:\BACKDATE.DT' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\ATERRJOB.VR' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\AMBERLED.GIF' is saved       
29-JAN-20 23:43 :08
========================================
FILE 'MC:\-BCKEDT-.TP' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\-BCKED9-.TP' is saved        
29-JAN-20 23:43 :08
========================================
FILE 'MC:\-BCKED8-.TP' is saved        
29-JAN-20 23:43 :08
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:42 :58
========================================
FILE 'MC:\XXXXXLED.GIF' is saved       
29-JAN-20 23:42 :58
========================================
FILE 'MC:\UPDTLOG.LS' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\UPDATES.DAT' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\TPRECKL.VR' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\TPREC.TP' is saved           
29-JAN-20 23:42 :58
========================================
FILE 'MC:\TPEINS.XML' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSVARS.SV' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSUIF.SV' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSSERVO.SV' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSPASS.SV' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSMAST.SV' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSMACRO.SV' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSHOST.SV' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSFSAC.SV' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SYSFRAME.SV' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SUMMARY.DG' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\STRREG.VR' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SPACER.GIF' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SHADOW.DG' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SENDSYSV.TP' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SENDEVNT.TP' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\SENDDATA.TP' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\REQMENU.TP' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\REDLED.GIF' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PSRBWLD.CM' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PRO_MOV2.TP' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\POSREG.VR' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PBUTTON.GIF' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL4.STM' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL4.DT' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL3.STM' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL3.DT' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL2.STM' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL2.DT' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL1.STM' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\PANEL1.DT' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\OTEMGRUN.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\OTEMGMON.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\ORDERFIL.DAT' is saved       
29-JAN-20 23:42 :58
========================================
FILE 'MC:\NUMREG.VR' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\NTDAQ.VR' is saved           
29-JAN-20 23:42 :58
========================================
FILE 'MC:\NORMM61C.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\NO03M61C.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\NBUTTON.GIF' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\MULTIROBOTTASK.TP' is saved  
29-JAN-20 23:42 :58
========================================
FILE 'MC:\MIXLOGIC.SV' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\MEM_PORT.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\MEMCHECK.DG' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\M61C.DT' is saved            
29-JAN-20 23:42 :58
========================================
FILE 'MC:\M10SET10.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\M10SET06.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\M10SET03.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\LOGBOOK.LS' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MDS0:\LOGBOOK.LS' is saved       
29-JAN-20 23:42 :58
========================================
FILE 'MC:\IOSTATUS.CM' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\HTTPKCL.VR' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\HTCOLREC.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\HOME_IO.TP' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\HIST.LS' is saved            
29-JAN-20 23:42 :58
========================================
FILE 'MC:\HIGHM61C.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\HI03M61C.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\GREENLED.GIF' is saved       
29-JAN-20 23:42 :58
========================================
FILE 'MC:\GETDATA.TP' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\GEMDATA.VR' is saved         
29-JAN-20 23:42 :58
========================================
FILE 'MC:\FTPLOG.DG' is saved          
29-JAN-20 23:42 :58
========================================
FILE 'MC:\FRAMEVAR.VR' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\ETHERNET.DG' is saved        
29-JAN-20 23:42 :58
========================================
FILE 'MC:\ERRSYS.LS' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MDS6:\ERRSYS.LS' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRPWD.LS' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MDS5:\ERRPWD.LS' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRMOT.LS' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MDS4:\ERRMOT.LS' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRHIST.LS' is saved         
29-JAN-20 23:42 :56
========================================
FILE 'MDS3:\ERRHIST.LS' is saved       
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERREXT.LS' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MDS2:\ERREXT.LS' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRCURR.LS' is saved         
29-JAN-20 23:42 :56
========================================
FILE 'MDS1:\ERRCURR.LS' is saved       
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRCOMM.LS' is saved         
29-JAN-20 23:42 :56
========================================
FILE 'MDS0:\ERRCOMM.LS' is saved       
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRAPP.LS' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MDS9:\ERRAPP.LS' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRALL.LS' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MDS8:\ERRALL.LS' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ERRACT.LS' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MDS7:\ERRACT.LS' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DIOCFGSV.IO' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DF_MOTN0.DF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DF_LOGI6.DF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DF_LOGI5.DF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DF_LOGI4.DF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DF_LOGI3.DF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DF_LOGI2.DF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DF_LOGI1.DF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSVRFY3.DG' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSVRFY2.DG' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSVRFY1.DG' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSVRFY.DG' is saved         
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSDIFF.DG' is saved         
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSCHGD3.DG' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSCHGD2.DG' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DCSCHGD1.DG' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\DARKLED.GIF' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\CONSLOG.DG' is saved         
29-JAN-20 23:42 :56
========================================
FILE 'MC:\CELLIO.SV' is saved          
29-JAN-20 23:42 :56
========================================
FILE 'MC:\BACKDATE.DT' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\ATERRJOB.VR' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\AMBERLED.GIF' is saved       
29-JAN-20 23:42 :56
========================================
FILE 'MC:\-BCKEDT-.TP' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\-BCKED9-.TP' is saved        
29-JAN-20 23:42 :56
========================================
FILE 'MC:\-BCKED8-.TP' is saved        
29-JAN-20 23:42 :56
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:42 :50
========================================
SYST-040 Operation mode AUTO Selected  
                                       
                                       
SERVO                         00110110 
29-JAN-20 23:42 :50
========================================
Menu changed 'Select'                  
29-JAN-20 23:42 :46
========================================
SELECT is pressed                      
29-JAN-20 23:42 :46
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:42 :08
========================================
'   YES' is selected in ' The cursor i
s on a different' window              
29-JAN-20 23:42 :08
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 13   \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
     ________________________________15 
   6:|The cursor is on a different  |   
   7:|line from where the program   |   
   8:|PAUSED [13].                  |   
   9:|Are you sure you want to run  |   
  10:|from this line ?              |   
  11:|                              |   
  12:|   \\\\YES\\\\       NO       |   
  13:|______________________________|   
\\14:J  P[2] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:42 :06
========================================
'Cnt' is selected in 'Motion Modify' me
nu                                     
29-JAN-20 23:42 :00
--Screen image--------------------------
                                        
Motion\Modify\\\\\\\\\\\\\\\\WORLD\\40\%
\1\Fine\\\\\\\\\\\\\5                   
 2 Cnt              6                   
                    7                   
                    8                   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                       PAUSED     14/15 
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J @P[1] 100% CNT100                
  14:J  P[2] 100% FINE                  
[End]                                   
Select item                             
                        [CHOICE]        
========================================
F4([CHOICE]) is pressed                
29-JAN-20 23:41 :58
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 13   \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                       PAUSED     14/15 
   6:L  P[2] 2000mm/sec CNT0            
   7:J @P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J @P[1] 100% CNT100                
  14:J  P[2] 100% FINE                  
[End]                                   
                                        
                        [CHOICE]        
========================================
2 is entered                           
29-JAN-20 23:41 :54
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 13   \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                       PAUSED     14/15 
   6:L  P[2] 2000mm/sec CNT0            
   7:J @P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J @P[1] 100% CNT100                
  14:J @P[8] 10] 100% FINE              
[End]                                   
Old Value: 8                            
                        [CHOICE]POSITION
========================================
'1 J P[] 100% FINE' is selected in 'De
fault Motion' menu                    
29-JAN-20 23:41 :40
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\40\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                       PAUSED     14/14 
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J @P[1] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:41 :34
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 13   \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                       PAUSED     14/14 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J @P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J @P[1] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
F5(   NO   ) is pressed                
29-JAN-20 23:41 :32
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 13   \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                       PAUSED     13/14 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J @P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
\\13:J @P[1] 100% CNT100                
[End]                                   
Set new id?                             
                          YES      NO   
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
29-JAN-20 23:41 :28
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\40\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                       PAUSED     13/14 
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
\\13:J @P[1] 100% CNT100                
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:41 :26
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 13   \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                       PAUSED     13/14 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J @P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
\\13:J @P[1] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:41 :10
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:41 :02
========================================
RESET is pressed                       
29-JAN-20 23:41 :02
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:41 :02
========================================
SHIFT,RESET is pressed                 
29-JAN-20 23:41 :02
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:41 :02
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:40 :58
========================================
FILE 'MC:\XXXXXLED.GIF' is saved       
29-JAN-20 23:40 :58
========================================
FILE 'MC:\UPDTLOG.LS' is saved         
29-JAN-20 23:40 :58
========================================
FILE 'MC:\UPDATES.DAT' is saved        
29-JAN-20 23:40 :58
========================================
FILE 'MC:\TPRECKL.VR' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\TPREC.TP' is saved           
29-JAN-20 23:40 :56
========================================
FILE 'MC:\TPEINS.XML' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSVARS.SV' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSUIF.SV' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSSERVO.SV' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSPASS.SV' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSMAST.SV' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSMACRO.SV' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSHOST.SV' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSFSAC.SV' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SYSFRAME.SV' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SUMMARY.DG' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\STRREG.VR' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SPACER.GIF' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SHADOW.DG' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SENDSYSV.TP' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SENDEVNT.TP' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\SENDDATA.TP' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\REQMENU.TP' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\REDLED.GIF' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PSRBWLD.CM' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PRO_MOV2.TP' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\POSREG.VR' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PBUTTON.GIF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL4.STM' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL4.DT' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL3.STM' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL3.DT' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL2.STM' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL2.DT' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL1.STM' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\PANEL1.DT' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\OTEMGRUN.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\OTEMGMON.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ORDERFIL.DAT' is saved       
29-JAN-20 23:40 :56
========================================
FILE 'MC:\NUMREG.VR' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\NTDAQ.VR' is saved           
29-JAN-20 23:40 :56
========================================
FILE 'MC:\NORMM61C.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\NO03M61C.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\NBUTTON.GIF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\MULTIROBOTTASK.TP' is saved  
29-JAN-20 23:40 :56
========================================
FILE 'MC:\MIXLOGIC.SV' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\MEM_PORT.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\MEMCHECK.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\M61C.DT' is saved            
29-JAN-20 23:40 :56
========================================
FILE 'MC:\M10SET10.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\M10SET06.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\M10SET03.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\LOGBOOK.LS' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MDS9:\LOGBOOK.LS' is saved       
29-JAN-20 23:40 :56
========================================
FILE 'MC:\IOSTATUS.CM' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\HTTPKCL.VR' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\HTCOLREC.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\HOME_IO.TP' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\HIST.LS' is saved            
29-JAN-20 23:40 :56
========================================
FILE 'MC:\HIGHM61C.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\HI03M61C.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\GREENLED.GIF' is saved       
29-JAN-20 23:40 :56
========================================
FILE 'MC:\GETDATA.TP' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\GEMDATA.VR' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\FTPLOG.DG' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\FRAMEVAR.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ETHERNET.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRSYS.LS' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MDS5:\ERRSYS.LS' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRPWD.LS' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MDS4:\ERRPWD.LS' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRMOT.LS' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MDS3:\ERRMOT.LS' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRHIST.LS' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MDS2:\ERRHIST.LS' is saved       
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERREXT.LS' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MDS1:\ERREXT.LS' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRCURR.LS' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MDS0:\ERRCURR.LS' is saved       
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRCOMM.LS' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MDS9:\ERRCOMM.LS' is saved       
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRAPP.LS' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MDS8:\ERRAPP.LS' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRALL.LS' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MDS7:\ERRALL.LS' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ERRACT.LS' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MDS6:\ERRACT.LS' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DIOCFGSV.IO' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DF_MOTN0.DF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DF_LOGI6.DF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DF_LOGI5.DF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DF_LOGI4.DF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DF_LOGI3.DF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DF_LOGI2.DF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DF_LOGI1.DF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSVRFY3.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSVRFY2.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSVRFY1.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSVRFY.DG' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSDIFF.DG' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSCHGD3.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSCHGD2.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DCSCHGD1.DG' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\DARKLED.GIF' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\CONSLOG.DG' is saved         
29-JAN-20 23:40 :56
========================================
FILE 'MC:\CELLIO.SV' is saved          
29-JAN-20 23:40 :56
========================================
FILE 'MC:\BACKDATE.DT' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\ATERRJOB.VR' is saved        
29-JAN-20 23:40 :56
========================================
FILE 'MC:\AMBERLED.GIF' is saved       
29-JAN-20 23:40 :56
========================================
FILE 'MC:\-BCKEDT-.TP' is saved        
29-JAN-20 23:40 :54
========================================
FILE 'MC:\-BCKED9-.TP' is saved        
29-JAN-20 23:40 :54
========================================
FILE 'MC:\-BCKED8-.TP' is saved        
29-JAN-20 23:40 :54
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:40 :52
========================================
Single step ON                         
29-JAN-20 23:40 :30
========================================
STEP is pressed                        
29-JAN-20 23:40 :30
========================================
PREV is pressed                        
29-JAN-20 23:40 :18
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
29-JAN-20 23:40 :12
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\40\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                   1/14 
\\\1:J @P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:40 :06
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                   1/14 
\\\1:J @P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J @P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L  P[7] 2000mm/sec FINE            
                                        
 POINT                          TOUCHUP>
========================================
Single step OFF                        
29-JAN-20 23:39 :06
========================================
STEP is pressed                        
29-JAN-20 23:39 :06
========================================
Single step ON                         
29-JAN-20 23:39 :04
========================================
STEP is pressed                        
29-JAN-20 23:39 :04
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:38 :58
========================================
Single step OFF                        
29-JAN-20 23:38 :56
========================================
STEP is pressed                        
29-JAN-20 23:38 :56
========================================
1 is entered                           
29-JAN-20 23:38 :52
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  13/14 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J  P[2] 10] 100% CNT100            
[End]                                   
Old Value: 2                            
                        [CHOICE]POSITION
========================================
2 is entered                           
29-JAN-20 23:38 :50
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  13/14 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
  13:J @P[8] 10] 100% CNT100            
[End]                                   
Old Value: 8                            
                        [CHOICE]POSITION
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
29-JAN-20 23:38 :42
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\40\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3 L P[] 100mm/sec FINE                  
4\L\P[]\100mm/sec\CNT100\\\\\\\\\\\\\\\ 
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  13/13 
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:38 :38
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  13/13 
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT0            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
ENTER is pressed                       
29-JAN-20 23:38 :32
========================================
0 is entered                           
29-JAN-20 23:38 :32
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  12/13 
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 2000mm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2000 is entered                        
29-JAN-20 23:38 :30
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  12/13 
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L  P[5] 100mmm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
5 is entered                           
29-JAN-20 23:38 :22
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  12/13 
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
  12:L @P[8] 10] 100mm/sec CNT100       
[End]                                   
Old Value: 8                            
                        [CHOICE]POSITION
========================================
'4 L P[] 100mm/sec CNT100' is selected 
in 'Default Motion' menu               
29-JAN-20 23:38 :18
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\40\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  12/12 
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:38 :12
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  12/12 
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 2000mm/sec FINE            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
2000 is entered                        
29-JAN-20 23:38 :00
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  11/12 
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L  P[6] 100mmm/sec FINE            
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
6 is entered                           
29-JAN-20 23:37 :54
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  11/12 
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
  11:L @P[8] 10] 100mm/sec FINE         
[End]                                   
Old Value: 8                            
                        [CHOICE]POSITION
========================================
'3 L P[] 100mm/sec FINE' is selected in
 'Default Motion' menu                 
29-JAN-20 23:37 :44
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\40\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  11/11 
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:37 :36
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  11/11 
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 2000mm/sec FINE            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
2000 is entered                        
29-JAN-20 23:37 :22
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  10/11 
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
  10:L @P[7] 100mmm/sec FINE            
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'3 L P[] 100mm/sec FINE' is selected in
 'Default Motion' menu                 
29-JAN-20 23:37 :16
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\40\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3 L P[] 100mm/sec FINE                  
4\L\P[]\100mm/sec\CNT100\\\\\\\\\\\\\\\ 
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                  10/10 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
[End]                                   
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:37 :10
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                  10/10 
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L  P[6] 2000mm/sec CNT0            
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,-Z(J3) is pressed                
29-JAN-20 23:36 :54
========================================
SHIFT,+Z(J3) is pressed                
29-JAN-20 23:36 :52
========================================
SHIFT,+Z(J3) is pressed                
29-JAN-20 23:36 :52
========================================
SHIFT,-Z(J3) is pressed                
29-JAN-20 23:36 :46
========================================
ENTER is pressed                       
29-JAN-20 23:36 :40
========================================
0 is entered                           
29-JAN-20 23:36 :40
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                   9/10 
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L @P[6] 2000mm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2000 is entered                        
29-JAN-20 23:36 :34
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                   9/10 
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
   9:L @P[6] 100mmm/sec CNT100          
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'4 L P[] 100mm/sec CNT100' is selected 
in 'Default Motion' menu               
29-JAN-20 23:36 :26
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\40\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    9/9 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
[End]                                   
                                        
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:36 :12
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\40\%
                                    9/9 
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
   8:J  P[5] 100% CNT100                
[End]                                   
                                        
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,-Z(J3) is pressed                
29-JAN-20 23:36 :04
========================================
SHIFT,+Z(J3) is pressed                
29-JAN-20 23:36 :02
========================================
SHIFT,+Z(J3) is pressed                
29-JAN-20 23:36 :00
========================================
SHIFT,-Z(J3) is pressed                
29-JAN-20 23:35 :48
========================================
SHIFT,-X(J1) is pressed                
29-JAN-20 23:35 :38
========================================
SHIFT,+X(J1) is pressed                
29-JAN-20 23:35 :36
========================================
SHIFT,+X(J1) is pressed                
29-JAN-20 23:35 :36
========================================
SHIFT,+X(J1) is pressed                
29-JAN-20 23:35 :34
========================================
SHIFT,-X(J1) is pressed                
29-JAN-20 23:35 :34
========================================
SHIFT,+Z(J3) is pressed                
29-JAN-20 23:35 :30
========================================
SHIFT,-Y(J2) is pressed                
29-JAN-20 23:35 :30
========================================
SHIFT,+Y(J2) is pressed                
29-JAN-20 23:35 :28
========================================
SHIFT,-Y(J2) is pressed                
29-JAN-20 23:35 :24
========================================
SHIFT,-Y(J2) is pressed                
29-JAN-20 23:35 :22
========================================
Override 40%                           
29-JAN-20 23:35 :20
========================================
-% is pressed                          
29-JAN-20 23:35 :20
========================================
Override 45%                           
29-JAN-20 23:35 :20
========================================
-% is pressed                          
29-JAN-20 23:35 :20
========================================
Override 50%                           
29-JAN-20 23:35 :20
========================================
-% is pressed                          
29-JAN-20 23:35 :20
========================================
Override 55%                           
29-JAN-20 23:35 :20
========================================
-% is pressed                          
29-JAN-20 23:35 :18
========================================
Override 60%                           
29-JAN-20 23:35 :18
========================================
-% is pressed                          
29-JAN-20 23:35 :18
========================================
Override 65%                           
29-JAN-20 23:35 :18
========================================
-% is pressed                          
29-JAN-20 23:35 :18
========================================
Override 70%                           
29-JAN-20 23:35 :18
========================================
-% is pressed                          
29-JAN-20 23:35 :18
========================================
Override 75%                           
29-JAN-20 23:35 :18
========================================
-% is pressed                          
29-JAN-20 23:35 :18
========================================
Override 80%                           
29-JAN-20 23:35 :18
========================================
-% is pressed                          
29-JAN-20 23:35 :18
========================================
Override 85%                           
29-JAN-20 23:35 :18
========================================
-% is pressed                          
29-JAN-20 23:35 :18
========================================
Override 90%                           
29-JAN-20 23:35 :18
========================================
-% is pressed                          
29-JAN-20 23:35 :18
========================================
Override 95%                           
29-JAN-20 23:35 :18
========================================
-% is pressed                          
29-JAN-20 23:35 :18
========================================
-% is pressed                          
29-JAN-20 23:35 :18
========================================
SHIFT,+Y(J2) is pressed                
29-JAN-20 23:35 :14
========================================
SHIFT,-Y(J2) is pressed                
29-JAN-20 23:35 :12
========================================
SHIFT,+X(J1) is pressed                
29-JAN-20 23:35 :08
========================================
+% is pressed                          
29-JAN-20 23:35 :06
========================================
Override 100%                          
29-JAN-20 23:35 :06
========================================
+% is pressed                          
29-JAN-20 23:35 :06
========================================
Override 95%                           
29-JAN-20 23:35 :06
========================================
+% is pressed                          
29-JAN-20 23:35 :06
========================================
Override 90%                           
29-JAN-20 23:35 :04
========================================
+% is pressed                          
29-JAN-20 23:35 :04
========================================
Override 85%                           
29-JAN-20 23:35 :04
========================================
+% is pressed                          
29-JAN-20 23:35 :04
========================================
Override 80%                           
29-JAN-20 23:35 :04
========================================
+% is pressed                          
29-JAN-20 23:35 :04
========================================
Override 75%                           
29-JAN-20 23:35 :04
========================================
+% is pressed                          
29-JAN-20 23:35 :04
========================================
Override 70%                           
29-JAN-20 23:35 :04
========================================
+% is pressed                          
29-JAN-20 23:35 :04
========================================
Override 65%                           
29-JAN-20 23:35 :04
========================================
+% is pressed                          
29-JAN-20 23:35 :04
========================================
Override 60%                           
29-JAN-20 23:35 :04
========================================
+% is pressed                          
29-JAN-20 23:35 :04
========================================
Override 55%                           
29-JAN-20 23:35 :04
========================================
+% is pressed                          
29-JAN-20 23:35 :04
========================================
Override 50%                           
29-JAN-20 23:35 :04
========================================
+% is pressed                          
29-JAN-20 23:35 :04
========================================
Override 45%                           
29-JAN-20 23:35 :04
========================================
+% is pressed                          
29-JAN-20 23:35 :04
========================================
Override 40%                           
29-JAN-20 23:35 :04
========================================
+% is pressed                          
29-JAN-20 23:35 :02
========================================
Override 35%                           
29-JAN-20 23:35 :02
========================================
+% is pressed                          
29-JAN-20 23:35 :02
========================================
Override 30%                           
29-JAN-20 23:35 :02
========================================
+% is pressed                          
29-JAN-20 23:35 :02
========================================
Override 25%                           
29-JAN-20 23:35 :02
========================================
+% is pressed                          
29-JAN-20 23:35 :02
========================================
Override 20%                           
29-JAN-20 23:35 :02
========================================
+% is pressed                          
29-JAN-20 23:35 :02
========================================
Override 15%                           
29-JAN-20 23:35 :02
========================================
+% is pressed                          
29-JAN-20 23:35 :02
========================================
+% is pressed                          
29-JAN-20 23:35 :02
========================================
  WORLD coordinate(G:1)                
29-JAN-20 23:35 :00
========================================
COORD is pressed                       
29-JAN-20 23:35 :00
========================================
  JGFRM coordinate(G:1)                
29-JAN-20 23:35 :00
========================================
COORD is pressed                       
29-JAN-20 23:35 :00
========================================
  JOINT coordinate(G:1)                
29-JAN-20 23:35 :00
========================================
COORD is pressed                       
29-JAN-20 23:35 :00
========================================
   USER coordinate(G:1)                
29-JAN-20 23:34 :58
========================================
COORD is pressed                       
29-JAN-20 23:34 :58
========================================
   TOOL coordinate(G:1)                
29-JAN-20 23:34 :58
========================================
COORD is pressed                       
29-JAN-20 23:34 :58
========================================
Override 10%                           
29-JAN-20 23:34 :58
========================================
  WORLD coordinate(G:1)                
29-JAN-20 23:34 :58
========================================
COORD is pressed                       
29-JAN-20 23:34 :58
========================================
Override 100%                          
29-JAN-20 23:34 :58
========================================
Override 10%                           
29-JAN-20 23:34 :58
========================================
  JGFRM coordinate(G:1)                
29-JAN-20 23:34 :58
========================================
COORD is pressed                       
29-JAN-20 23:34 :58
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
29-JAN-20 23:34 :28
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\JOINT\100\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    8/8 
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
[End]                                   
                                        
                                        
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:34 :12
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\JOINT\100\%
                                    8/8 
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J  P[1] 100% CNT100                
[End]                                   
                                        
                                        
                                        
 POINT                          TOUCHUP>
========================================
Single step ON                         
29-JAN-20 23:33 :40
========================================
STEP is pressed                        
29-JAN-20 23:33 :40
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:33 :38
========================================
SYST-039 Operation mode T2 Selected    
                                       
                                       
SERVO                         00110110 
29-JAN-20 23:33 :38
========================================
Single step OFF                        
29-JAN-20 23:33 :38
========================================
FILE 'MC:\PRO_MOV2.LS' is loaded       
29-JAN-20 23:33 :38
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:33 :34
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:33 :34
========================================
SYST-040 Operation mode AUTO Selected  
                                       
                                       
SERVO                         00110110 
29-JAN-20 23:33 :34
========================================
SYST-043 TP disabled in T1/T2 mode     
                                       
                                       
STOP.L                        00000110 
29-JAN-20 23:33 :34
========================================
PREV is pressed                        
29-JAN-20 23:33 :24
========================================
Override 100%                          
29-JAN-20 23:33 :22
========================================
+% is pressed                          
29-JAN-20 23:33 :22
========================================
Override 95%                           
29-JAN-20 23:33 :22
========================================
+% is pressed                          
29-JAN-20 23:33 :22
========================================
Override 90%                           
29-JAN-20 23:33 :22
========================================
+% is pressed                          
29-JAN-20 23:33 :22
========================================
Override 85%                           
29-JAN-20 23:33 :22
========================================
+% is pressed                          
29-JAN-20 23:33 :22
========================================
Override 80%                           
29-JAN-20 23:33 :20
========================================
+% is pressed                          
29-JAN-20 23:33 :20
========================================
Override 75%                           
29-JAN-20 23:33 :20
========================================
+% is pressed                          
29-JAN-20 23:33 :20
========================================
Override 70%                           
29-JAN-20 23:33 :20
========================================
+% is pressed                          
29-JAN-20 23:33 :20
========================================
Override 65%                           
29-JAN-20 23:33 :20
========================================
+% is pressed                          
29-JAN-20 23:33 :20
========================================
Override 60%                           
29-JAN-20 23:33 :20
========================================
+% is pressed                          
29-JAN-20 23:33 :20
========================================
Override 55%                           
29-JAN-20 23:33 :20
========================================
+% is pressed                          
29-JAN-20 23:33 :20
========================================
Override 50%                           
29-JAN-20 23:33 :20
========================================
+% is pressed                          
29-JAN-20 23:33 :20
========================================
Override 45%                           
29-JAN-20 23:33 :18
========================================
+% is pressed                          
29-JAN-20 23:33 :18
========================================
Override 40%                           
29-JAN-20 23:33 :18
========================================
+% is pressed                          
29-JAN-20 23:33 :18
========================================
Override 35%                           
29-JAN-20 23:33 :18
========================================
+% is pressed                          
29-JAN-20 23:33 :18
========================================
Override 30%                           
29-JAN-20 23:33 :18
========================================
+% is pressed                          
29-JAN-20 23:33 :18
========================================
Override 25%                           
29-JAN-20 23:33 :18
========================================
+% is pressed                          
29-JAN-20 23:33 :18
========================================
Override 20%                           
29-JAN-20 23:33 :18
========================================
+% is pressed                          
29-JAN-20 23:33 :18
========================================
Override 15%                           
29-JAN-20 23:33 :18
========================================
+% is pressed                          
29-JAN-20 23:33 :18
========================================
+% is pressed                          
29-JAN-20 23:33 :18
========================================
  JOINT coordinate(G:1)                
29-JAN-20 23:33 :16
========================================
COORD is pressed                       
29-JAN-20 23:33 :16
========================================
   USER coordinate(G:1)                
29-JAN-20 23:33 :14
========================================
COORD is pressed                       
29-JAN-20 23:33 :14
========================================
   TOOL coordinate(G:1)                
29-JAN-20 23:33 :14
========================================
COORD is pressed                       
29-JAN-20 23:33 :14
========================================
SHIFT,COORD is pressed                 
29-JAN-20 23:33 :12
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:32 :38
========================================
'   YES' is selected in ' The cursor i
s on a different' window              
29-JAN-20 23:32 :38
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 4    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
     ________________________________/8 
     |The cursor is on a different  |   
     |line from where the program   |   
   1:|PAUSED [4].                   |   
   2:|Are you sure you want to run  |   
   3:|from this line ?              |   
   4:|                              |   
   5:|   \\\\YES\\\\       NO       |   
   6:|______________________________|   
\\\7:J  P[1] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:32 :36
========================================
1 is entered                           
29-JAN-20 23:32 :24
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 4    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       7/8 
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
   7:J @P[5] 10] 100% CNT100            
[End]                                   
Old Value: 5                            
                        [CHOICE]POSITION
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
29-JAN-20 23:32 :20
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\10\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                       PAUSED       7/7 
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
[End]                                   
                                        
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:32 :14
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 4    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       7/7 
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT0            
[End]                                   
                                        
                                        
 POINT                          TOUCHUP>
========================================
0 is entered                           
29-JAN-20 23:32 :06
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 4    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       6/7 
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec CNT100          
[End]                                   
                                        
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'Cnt' is selected in 'Motion Modify' me
nu                                     
29-JAN-20 23:32 :04
--Screen image--------------------------
                                        
Motion\Modify\\\\\\\\\\\\\\\\WORLD\\10\%
\1\Fine\\\\\\\\\\\\\5                   
 2 Cnt              6                   
                    7                   
                    8                   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                       PAUSED       6/7 
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec FINE            
[End]                                   
                                        
Select item                             
                        [CHOICE]        
========================================
F4([CHOICE]) is pressed                
29-JAN-20 23:32 :02
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 4    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       6/7 
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 2000mm/sec FINE            
[End]                                   
                                        
                                        
                        [CHOICE]        
========================================
2000 is entered                        
29-JAN-20 23:31 :52
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 4    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       6/7 
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L  P[2] 100mmm/sec FINE            
[End]                                   
                                        
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
2 is entered                           
29-JAN-20 23:31 :48
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 4    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       6/7 
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
   6:L @P[5] 10] 100mm/sec FINE         
[End]                                   
                                        
Old Value: 5                            
                        [CHOICE]POSITION
========================================
'3 L P[] 100mm/sec FINE' is selected in
 'Default Motion' menu                 
29-JAN-20 23:31 :34
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\10\%
1 J P[] 100% FINE                       
2 J P[] 100% CNT100                     
3\L\P[]\100mm/sec\FINE\\\\\\\\\\\\\\\\\ 
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                       PAUSED       6/6 
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
[End]                                   
                                        
                                        
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:31 :32
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 4    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       6/6 
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 2000mm/sec FINE            
[End]                                   
                                        
                                        
                                        
 POINT                          TOUCHUP>
========================================
2000 is entered                        
29-JAN-20 23:31 :22
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 4    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       5/6 
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L  P[3] 100mmm/sec FINE            
[End]                                   
                                        
                                        
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
3 is entered                           
29-JAN-20 23:31 :16
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 4    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       5/6 
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
   5:L @P[5] 10] 100mm/sec FINE         
[End]                                   
                                        
                                        
Old Value: 5                            
                        [CHOICE]POSITION
========================================
'3 L P[] 100mm/sec FINE' is selected in
 'Default Motion' menu                 
29-JAN-20 23:31 :12
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\10\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                       PAUSED       5/5 
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
[End]                                   
                                        
                                        
                                        
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:30 :54
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 4    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       5/5 
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
[End]                                   
                                        
                                        
                                        
                                        
 POINT                          TOUCHUP>
========================================
PREV is pressed                        
29-JAN-20 23:30 :54
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:30 :40
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 4    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       5/5 
   1:J  P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L @P[4] 2000mm/sec FINE            
[End]                                   
                                        
                                        
                                        
                                        
                                        
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:30 :28
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:30 :24
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:30 :20
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:30 :18
========================================
'   YES' is selected in ' The cursor i
s on a different' window              
29-JAN-20 23:30 :18
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 2    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
     ________________________________/5 
     |The cursor is on a different  |   
     |line from where the program   |   
\\\1:|PAUSED [2].                   |   
   2:|Are you sure you want to run  |   
   3:|from this line ?              |   
   4:|                              |   
[End]|   \\\\YES\\\\       NO       |   
     |______________________________|   
                                        
                                        
                                        
[ INST ]                        [EDCMD]>
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:30 :16
========================================
F4(  YES   ) is pressed                
29-JAN-20 23:30 :12
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 2    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       5/6 
                                        
                                        
   1:J @P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
\\\5:  DO[115]=ON                       
[End]                                   
                                        
                                        
Delete line(s) ?                        
                          YES     NO    
========================================
'Delete' is selected                   
29-JAN-20 23:30 :10
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 2    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       5/6 
                                        
                      __________________
   1:J @P[1] 100% CNT1| 1\Insert\\\\\\ |
   2:J  P[2] 100% CNT1| 2 Delete       |
   3:L  P[3] 2000mm/se| 3 Copy         |
   4:L  P[4] 2000mm/se| 4 Find         |
\\\5:  DO[115]=ON     | 5 Replace      |
[End]                 | 6 Renumber     |
                      | 7 Comment      |
                      | 8 Undo         |
                      ----------+     +-
[ INST ]                        |EDCMD|>
========================================
F5([EDCMD]>) is pressed                
29-JAN-20 23:30 :08
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 2    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       5/6 
                                        
                                        
   1:J @P[1] 100% CNT100                
   2:J  P[2] 100% CNT100                
   3:L  P[3] 2000mm/sec CNT0            
   4:L  P[4] 2000mm/sec FINE            
\\\5:  DO[115]=ON                       
[End]                                   
                                        
                                        
                                        
[ INST ]                        [EDCMD]>
========================================
F4(  YES   ) is pressed                
29-JAN-20 23:30 :02
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 2    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       3/8 
                                        
                                        
   1:J @P[1] 100% CNT100                
\\\2:  LBL[1]                           
\\\3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:L  P[3] 2000mm/sec CNT0            
   6:L  P[4] 2000mm/sec FINE            
   7:  DO[115]=ON                       
[End]                                   
Delete line(s) ?                        
                          YES     NO    
========================================
'Delete' is selected                   
29-JAN-20 23:29 :58
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 2    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       2/8 
                                        
                      __________________
   1:J @P[1] 100% CNT1| 1\Insert\\\\\\ |
\\\2:  LBL[1]         | 2 Delete       |
   3:  IF DI[104]=OFF,| 3 Copy         |
   4:J  P[2] 100% CNT1| 4 Find         |
   5:L  P[3] 2000mm/se| 5 Replace      |
   6:L  P[4] 2000mm/se| 6 Renumber     |
   7:  DO[115]=ON     | 7 Comment      |
[End]                 | 8 Undo         |
                      ----------+     +-
[ INST ]                        |EDCMD|>
========================================
F5([EDCMD]>) is pressed                
29-JAN-20 23:29 :56
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 2    \T2\ PAUSED 
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                       PAUSED       2/8 
                                        
                                        
   1:J @P[1] 100% CNT100                
\\\2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:L  P[3] 2000mm/sec CNT0            
   6:L  P[4] 2000mm/sec FINE            
   7:  DO[115]=ON                       
[End]                                   
                                        
[ INST ]                        [EDCMD]>
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:29 :50
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:29 :50
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:29 :48
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:29 :48
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:29 :46
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:29 :46
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:29 :46
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:29 :44
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:29 :42
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:29 :38
========================================
SHIFT,FWD is pressed                   
29-JAN-20 23:29 :34
========================================
Single step ON                         
29-JAN-20 23:29 :32
========================================
STEP is pressed                        
29-JAN-20 23:29 :32
========================================
'On' is selected in 'I/O statement' men
u                                      
29-JAN-20 23:29 :18
--Screen image--------------------------
                                        
I/O\statement\\\\\\\\\\\\\\\\WORLD\\10\%
\1\On\\\\\\\\\\\\\\\5  (...)            
 2 Off              6                   
 3 Pulse (,width)   7                   
 4 R[ ]             8                   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    7/8 
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:L  P[3] 2000mm/sec CNT0            
   6:L @P[4] 2000mm/sec FINE            
   7:  DO[115]=...                      
Select item                             
                       [CHOICE]         
========================================
115 is entered                         
29-JAN-20 23:29 :12
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                                    7/8 
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:L  P[3] 2000mm/sec CNT0            
   6:L @P[4] 2000mm/sec FINE            
   7:  DO[...]=]=...                    
Old Value: 0                            
        DIRECT INDIRECT[CHOICE] [LIST]  
========================================
'DO[  ]=...' is selected in 'I/O state
ment' menu                            
29-JAN-20 23:29 :06
--Screen image--------------------------
                                        
I/O\statement\\\\\\\\\\\\\\\\WORLD\\10\%
\1\DO[\\]=...\\\\\\\5 GO[  ]=...        
 2 R[  ]=DI[  ]     6 R[  ]=GI[  ]      
 3 RO[  ]=...       7 AO[  ]=...        
 4 R[  ]=RI[  ]     8 ---next page---   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    7/7 
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:L  P[3] 2000mm/sec CNT0            
   6:L @P[4] 2000mm/sec FINE            
[End]                                   
Select item                             
                       [CHOICE]         
========================================
'I/O' is selected in 'Instruction' menu
29-JAN-20 23:29 :04
--Screen image--------------------------
                                        
Instruction\\\\\\\\\\\\\\\\\\WORLD\\10\%
\1\Registers\\\\\\\\5 JMP/LBL           
 2 I/O              6 CALL              
 3 IF/SELECT        7 Miscellaneous     
 4 WAIT             8 ---next page---   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    7/7 
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:L  P[3] 2000mm/sec CNT0            
   6:L @P[4] 2000mm/sec FINE            
[End]                                   
                                        
[ INST ]                        [EDCMD]>
========================================
F1([ INST ]) is pressed                
29-JAN-20 23:28 :56
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                                    7/7 
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:L  P[3] 2000mm/sec CNT0            
   6:L @P[4] 2000mm/sec FINE            
[End]                                   
                                        
[ INST ]                        [EDCMD]>
========================================
'Fine' is selected in 'Motion Modify' m
enu                                    
29-JAN-20 23:28 :50
--Screen image--------------------------
                                        
Motion\Modify\\\\\\\\\\\\\\\\WORLD\\10\%
\1\Fine\\\\\\\\\\\\\5                   
 2 Cnt              6                   
                    7                   
                    8                   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    6/7 
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:L  P[3] 2000mm/sec CNT0            
   6:L @P[4] 2000mm/sec CNT100          
[End]                                   
Select item                             
                        [CHOICE]        
========================================
F4([CHOICE]) is pressed                
29-JAN-20 23:28 :48
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                                    6/7 
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:L  P[3] 2000mm/sec CNT0            
   6:L @P[4] 2000mm/sec CNT100          
[End]                                   
Enter value                             
REGISTER                [CHOICE]        
========================================
'Linear' is selected in 'Motion Modify'
 menu                                  
29-JAN-20 23:28 :42
--Screen image--------------------------
                                        
Motion\Modify\\\\\\\\\\\\\\\\WORLD\\10\%
\1\Joint\\\\\\\\\\\\5                   
 2 Linear           6                   
 3 Circular         7                   
                    8                   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    6/7 
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:L  P[3] 2000mm/sec CNT0            
   6:J @P[4] 100% CNT100                
[End]                                   
Select item                             
                        [CHOICE]        
========================================
F4([CHOICE]) is pressed                
29-JAN-20 23:28 :40
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                                    6/7 
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:L  P[3] 2000mm/sec CNT0            
   6:J @P[4] 100% CNT100                
[End]                                   
                                        
                        [CHOICE]        
========================================
ENTER is pressed                       
29-JAN-20 23:28 :30
========================================
0 is entered                           
29-JAN-20 23:28 :30
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                                    5/7 
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:L  P[3] 2000mm/sec CNT100          
   6:J @P[4] 100% CNT100                
[End]                                   
Old Value: 100                          
REGISTER                [CHOICE]        
========================================
'Linear' is selected in 'Motion Modify'
 menu                                  
29-JAN-20 23:28 :20
--Screen image--------------------------
                                        
Motion\Modify\\\\\\\\\\\\\\\\WORLD\\10\%
\1\Joint\\\\\\\\\\\\5                   
 2 Linear           6                   
 3 Circular         7                   
                    8                   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    5/7 
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:J  P[3] 100% CNT100                
   6:J @P[4] 100% CNT100                
[End]                                   
Select item                             
                        [CHOICE]        
========================================
F4([CHOICE]) is pressed                
29-JAN-20 23:28 :18
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                                    5/7 
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:J  P[3] 100% CNT100                
   6:J @P[4] 100% CNT100                
[End]                                   
                                        
                        [CHOICE]        
========================================
SHIFT,F1( POINT  ) is pressed          
29-JAN-20 23:28 :08
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                                    6/6 
                                        
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
   5:J  P[3] 100% CNT100                
[End]                                   
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,-Z(J3) is pressed                
29-JAN-20 23:28 :02
========================================
SHIFT,F1( POINT  ) is pressed          
29-JAN-20 23:27 :56
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\10\%
                                    5/5 
                                        
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
   4:J  P[2] 100% CNT100                
[End]                                   
                                        
                                        
 POINT                          TOUCHUP>
========================================
SHIFT,+Z(J3) is pressed                
29-JAN-20 23:27 :46
========================================
SHIFT,+Z(J3) is pressed                
29-JAN-20 23:27 :22
========================================
SHIFT,+Z(J3) is pressed                
29-JAN-20 23:27 :20
========================================
SHIFT,+Z(J3) is pressed                
29-JAN-20 23:27 :18
========================================
Override 10%                           
29-JAN-20 23:27 :12
========================================
SHIFT -% is pressed                    
29-JAN-20 23:27 :12
========================================
Override 15%                           
29-JAN-20 23:27 :12
========================================
SHIFT -% is pressed                    
29-JAN-20 23:27 :12
========================================
SHIFT -% is pressed                    
29-JAN-20 23:27 :12
========================================
SHIFT,-Z(J3) is pressed                
29-JAN-20 23:27 :08
========================================
SHIFT,-Z(J3) is pressed                
29-JAN-20 23:27 :08
========================================
SHIFT,-Z(J3) is pressed                
29-JAN-20 23:27 :06
========================================
SHIFT,-Z(J3) is pressed                
29-JAN-20 23:26 :54
========================================
SHIFT,+Z(J3) is pressed                
29-JAN-20 23:26 :48
========================================
SHIFT,+Y(J2) is pressed                
29-JAN-20 23:26 :42
========================================
SHIFT,-Y(J2) is pressed                
29-JAN-20 23:26 :40
========================================
SHIFT,-Y(J2) is pressed                
29-JAN-20 23:26 :32
========================================
SHIFT,+Y(J2) is pressed                
29-JAN-20 23:26 :26
========================================
SHIFT,+X(J1) is pressed                
29-JAN-20 23:26 :04
========================================
SHIFT,-X(J1) is pressed                
29-JAN-20 23:25 :58
========================================
SHIFT,-X(J1) is pressed                
29-JAN-20 23:25 :56
========================================
Override 20%                           
29-JAN-20 23:25 :50
========================================
+% is pressed                          
29-JAN-20 23:25 :50
========================================
Override 15%                           
29-JAN-20 23:25 :50
========================================
+% is pressed                          
29-JAN-20 23:25 :50
========================================
+% is pressed                          
29-JAN-20 23:25 :50
========================================
  WORLD coordinate(G:1)                
29-JAN-20 23:25 :48
========================================
COORD is pressed                       
29-JAN-20 23:25 :48
========================================
  JGFRM coordinate(G:1)                
29-JAN-20 23:25 :48
========================================
COORD is pressed                       
29-JAN-20 23:25 :48
========================================
  JOINT coordinate(G:1)                
29-JAN-20 23:25 :48
========================================
COORD is pressed                       
29-JAN-20 23:25 :48
========================================
Override 10%                           
29-JAN-20 23:25 :46
========================================
   USER coordinate(G:1)                
29-JAN-20 23:25 :46
========================================
COORD is pressed                       
29-JAN-20 23:25 :46
========================================
Override 100%                          
29-JAN-20 23:25 :46
========================================
Override 10%                           
29-JAN-20 23:25 :46
========================================
   TOOL coordinate(G:1)                
29-JAN-20 23:25 :46
========================================
COORD is pressed                       
29-JAN-20 23:25 :46
========================================
'2 J P[] 100% CNT100' is selected in '
Default Motion' menu                  
29-JAN-20 23:24 :42
--Screen image--------------------------
                                        
Default\Motion\\\\\\\\\\\\\\\WORLD\\35\%
1 J P[] 100% FINE                       
2\J\P[]\100%\CNT100\\\\\\\\\\\\\\\\\\\\ 
3 L P[] 100mm/sec FINE                  
4 L P[] 100mm/sec CNT100                
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    4/4 
   1:J  P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
[End]                                   
                                        
                                        
                                        
 ED_DEF                         TOUCHUP>
========================================
F1( POINT  ) is pressed                
29-JAN-20 23:24 :38
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\35\%
                                    4/4 
                                        
                                        
                                        
                                        
   1:J  P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[1]        
[End]                                   
                                        
                                        
                                        
 POINT                          TOUCHUP>
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:23 :44
========================================
SYST-039 Operation mode T2 Selected    
                                       
                                       
SERVO                         00110110 
29-JAN-20 23:23 :44
========================================
Override 35%                           
29-JAN-20 23:23 :44
========================================
FILE 'MC:\PRO_MOV2.LS' is loaded       
29-JAN-20 23:23 :44
========================================
Override 100%                          
29-JAN-20 23:23 :44
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:23 :44
========================================
R E S E T                              
                                       
                              00000000 
29-JAN-20 23:23 :44
========================================
SYST-040 Operation mode AUTO Selected  
                                       
                                       
SERVO                         00110110 
29-JAN-20 23:23 :44
========================================
SYST-043 TP disabled in T1/T2 mode     
                                       
                                       
STOP.L                        00000110 
29-JAN-20 23:23 :44
========================================
1 is entered                           
29-JAN-20 23:23 :22
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\35\%
                                    3/4 
                                        
                                        
                                        
                                        
   1:J @P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF DI[104]=OFF,JMP LBL[...] ]    
[End]                                   
                                        
                                        
Old Value: 0                            
        DIRECT INDIRECT[CHOICE] [LIST]  
========================================
'JMP LBL[  ]' is selected in 'IF state
ment' menu                            
29-JAN-20 23:23 :20
--Screen image--------------------------
                                        
IF\statement\\\\\\\\\\\\\\\\\WORLD\\35\%
\1\JMP\LBL[\\]\\\\\\5 OR                
 2 CALL program     6                   
 3 CALL program()   7                   
 4 AND              8                   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    3/4 
   1:J @P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF DI[104]=OFF ...               
[End]                                   
                                        
                                        
Select item                             
                       [CHOICE]         
========================================
'Off' is selected in 'IF statement' men
u                                      
29-JAN-20 23:23 :14
--Screen image--------------------------
                                        
IF\statement\\\\\\\\\\\\\\\\\WORLD\\35\%
\1\R[\]\\\\\\\\\\\\\5 DI[  ]            
 2 On               6 RO[  ]            
 3 Off              7 RI[  ]            
 4 DO[  ]           8 ---next page---   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    3/4 
   1:J @P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF DI[104]=... ...               
[End]                                   
                                        
                                        
Select item                             
                       [CHOICE]         
========================================
104 is entered                         
29-JAN-20 23:23 :06
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\35\%
                                    3/4 
                                        
                                        
                                        
                                        
   1:J @P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF DI[...]=]=... ...             
[End]                                   
                                        
                                        
Old Value: 0                            
        DIRECT INDIRECT[CHOICE] [LIST]  
========================================
'DI[  ]' is selected in 'IF statement' 
menu                                   
29-JAN-20 23:23 :00
--Screen image--------------------------
                                        
IF\statement\\\\\\\\\\\\\\\\\WORLD\\35\%
\1\R[\]\\\\\\\\\\\\\5 RI[  ]            
 2 DO[  ]           6 GO[  ]            
 3 DI[  ]           7 GI[  ]            
 4 RO[  ]           8 ---next page---   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    3/4 
   1:J @P[1] 100% CNT100                
   2:  LBL[1]                           
   3:  IF ...=... ...                   
[End]                                   
                                        
                                        
Select item                             
                       [CHOICE]         
========================================
'IF ...=...' is selected in 'IF statem
ent' menu                             
29-JAN-20 23:22 :56
--Screen image--------------------------
                                        
IF\statement\\\\\\\\\\\\\\\\\WORLD\\35\%
\1\IF\...=...\\\\\\\5 IF ...>...        
 2 IF ...<>...      6 IF ...>=...       
 3 IF ...<...       7 IF (...)          
 4 IF ...<=...      8 ---next page---   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    3/3 
   1:J @P[1] 100% CNT100                
   2:  LBL[1]                           
[End]                                   
                                        
                                        
                                        
Select item                             
                       [CHOICE]         
========================================
'IF/SELECT' is selected in 'Instructio
n' menu                               
29-JAN-20 23:22 :52
--Screen image--------------------------
                                        
Instruction\\\\\\\\\\\\\\\\\\WORLD\\35\%
\1\Registers\\\\\\\\5 JMP/LBL           
 2 I/O              6 CALL              
 3 IF/SELECT        7 Miscellaneous     
 4 WAIT             8 ---next page---   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    3/3 
   1:J @P[1] 100% CNT100                
   2:  LBL[1]                           
[End]                                   
                                        
                                        
                                        
                                        
[ INST ]                        [EDCMD]>
========================================
F1([ INST ]) is pressed                
29-JAN-20 23:22 :48
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\35\%
                                    3/3 
                                        
                                        
                                        
                                        
   1:J @P[1] 100% CNT100                
   2:  LBL[1]                           
[End]                                   
                                        
                                        
                                        
                                        
[ INST ]                        [EDCMD]>
========================================
1 is entered                           
29-JAN-20 23:22 :34
--Screen image--------------------------
                                        
MULTIROBOTTASK    LINE 0    \T2\ ABORTED
MULTIROBOTTASK\\\\\\\\\\\\\\\WORLD\\35\%
                                    2/3 
                                        
                                        
                                        
                                        
   1:J @P[1] 100% CNT100                
   2:  LBL[...] ]                       
[End]                                   
                                        
                                        
                                        
Old Value: 0                            
                       [CHOICE]         
========================================
'LBL[  ]' is selected in 'JMP statemen
t' menu                               
29-JAN-20 23:22 :32
--Screen image--------------------------
                                        
JMP\statement\\\\\\\\\\\\\\\\WORLD\\35\%
\1\JMP\LBL[\\]\\\\\\5                   
 2 LBL[  ]          6                   
                    7                   
                    8                   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    2/2 
   1:J @P[1] 100% CNT100                
[End]                                   
                                        
                                        
                                        
                                        
Select item                             
                       [CHOICE]         
========================================
'JMP/LBL' is selected in 'Instruction' 
menu                                   
29-JAN-20 23:22 :28
--Screen image--------------------------
                                        
Instruction\\\\\\\\\\\\\\\\\\WORLD\\35\%
\1\Registers\\\\\\\\5 JMP/LBL           
 2 I/O              6 CALL              
 3 IF/SELECT        7 Miscellaneous     
 4 WAIT             8 ---next page---   
MULTIROBOTTASK\\\\\\\\\\\\\\\\\\\\\\\\\\
                                    2/2 
   1:J @P[1] 100% CNT100                
[End]                                   
                                        
                                        
                                        
                                        
                                        
[ INST ]                        [EDCMD]>
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
I/O              
========================================
 UO[    2]    OFF -> ON 
Tick:   1785720
TB:     1516128384
29-JAN-20 23:42 :50
========================================
 UO[    2]    ON  -> OFF
Tick:   1785588
TB:     1515801387
29-JAN-20 23:42 :50
========================================
 SO[    7]    ON  -> OFF
Tick:   1785529
TB:     1515560999
29-JAN-20 23:42 :50
========================================
 UO[    8]    ON  -> OFF
Tick:   1785528
TB:     1515559249
29-JAN-20 23:42 :50
========================================
 SO[    1]    ON  -> OFF
Tick:   1749751
TB:     1424860081
29-JAN-20 23:42 :10
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1749750
TB:     1424857810
29-JAN-20 23:42 :10
========================================
Paused       MULTIROBOTTASK,  14       
   (TASK:1,TB:1424737633)              
29-JAN-20 23:42 :10
========================================
 SO[    1]    OFF -> ON 
Tick:   1748725
TB:     1422188764
29-JAN-20 23:42 :08
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1748724
TB:     1422187330
29-JAN-20 23:42 :08
========================================
Run FWD      MULTIROBOTTASK,  14       
   (TASK:1,TB:1422098176)              
29-JAN-20 23:42 :08
========================================
 SO[    1]    ON  -> OFF
Tick:   1697719
TB:     1292310613
29-JAN-20 23:41 :10
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1697718
TB:     1292308795
29-JAN-20 23:41 :10
========================================
Paused       MULTIROBOTTASK,  13       
   (TASK:1,TB:1292266998)              
29-JAN-20 23:41 :10
========================================
 SO[    1]    OFF -> ON 
Tick:   1697401
TB:     1291474703
29-JAN-20 23:41 :10
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   1697400
TB:     1291473283
29-JAN-20 23:41 :10
========================================
Run FWD      MULTIROBOTTASK,  13       
   (TASK:1,TB:1291444705)              
29-JAN-20 23:41 :10
========================================
Aborted      MULTIROBOTTASK,   0       
   (TASK:1,TB:1271855281)              
29-JAN-20 23:41 :02
========================================
Aborted      MULTIROBOTTASK,   0       
   (TASK:1,TB:1249941740)              
29-JAN-20 23:40 :52
========================================
 SO[    1]    ON  -> OFF
Tick:   1584121
TB:     998583511
29-JAN-20 23:39 :00
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   1584120
TB:     998581914
29-JAN-20 23:39 :00
========================================
Aborted      MULTIROBOTTASK,   0       
   (TASK:1,TB:998519112)               
29-JAN-20 23:39 :00
========================================
 SO[    1]    OFF -> ON 
Tick:   1583257
TB:     996252903
29-JAN-20 23:38 :58
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   1583256
TB:     996251157
29-JAN-20 23:38 :58
========================================
Run FWD      MULTIROBOTTASK,  13       
   (TASK:1,TB:996162786)               
29-JAN-20 23:38 :58
========================================
 UO[    2]    OFF -> ON 
Tick:   1304472
TB:     280608863
29-JAN-20 23:33 :40
========================================
 UO[    2]    ON  -> OFF
Tick:   1304340
TB:     280294951
29-JAN-20 23:33 :38
========================================
 SO[    7]    OFF -> ON 
Tick:   1304281
TB:     280076815
29-JAN-20 23:33 :38
========================================
 UO[    8]    OFF -> ON 
Tick:   1304280
TB:     280075307
29-JAN-20 23:33 :38
========================================
 SO[    1]    ON  -> OFF
Tick:   1304053
TB:     279508349
29-JAN-20 23:33 :38
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   1304052
TB:     279507415
29-JAN-20 23:33 :38
========================================
Aborted      PRO_MOV2    ,   0         
 (TASK:7,TB:279438525)                 
29-JAN-20 23:33 :38
========================================
 SO[    1]    OFF -> ON 
Tick:   1303447
TB:     277987996
29-JAN-20 23:33 :38
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   1303446
TB:     277985742
29-JAN-20 23:33 :38
========================================
Run FWD      PRO_MOV2    ,   3         
 (TASK:7,TB:277936344)                 
29-JAN-20 23:33 :38
========================================
Run FWD      PRO_MOV2    ,   2         
 (TASK:7,TB:277936301)                 
29-JAN-20 23:33 :38
========================================
Run FWD      PRO_MOV2    ,   1         
 (TASK:7,TB:277936240)                 
29-JAN-20 23:33 :38
========================================
 UO[    4]    ON  -> OFF
Tick:   1303188
TB:     277307436
29-JAN-20 23:33 :38
========================================
Aborted      MULTIROBOTTASK,   8       
   (TASK:1,TB:277234745)               
29-JAN-20 23:33 :38
========================================
 SO[    3]    ON  -> OFF
Tick:   1300309
TB:     269933560
29-JAN-20 23:33 :34
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   1300308
TB:     269932342
29-JAN-20 23:33 :34
========================================
 SO[    3]    OFF -> ON 
Tick:   1300153
TB:     269503562
29-JAN-20 23:33 :34
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   1300152
TB:     269502056
29-JAN-20 23:33 :34
========================================
 SO[    7]    ON  -> OFF
Tick:   1300117
TB:     269379759
29-JAN-20 23:33 :34
========================================
 UO[    8]    ON  -> OFF
Tick:   1300116
TB:     269379333
29-JAN-20 23:33 :34
========================================
 SO[    1]    ON  -> OFF
Tick:   1254583
TB:     152693129
29-JAN-20 23:32 :42
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1254582
TB:     152690782
29-JAN-20 23:32 :42
========================================
Paused       MULTIROBOTTASK,   7       
   (TASK:1,TB:152635223)               
29-JAN-20 23:32 :42
========================================
 SO[    1]    OFF -> ON 
Tick:   1251769
TB:     145411919
29-JAN-20 23:32 :38
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1251768
TB:     145408171
29-JAN-20 23:32 :38
========================================
Run FWD      MULTIROBOTTASK,   7       
   (TASK:1,TB:145340313)               
29-JAN-20 23:32 :38
========================================
 SO[    1]    ON  -> OFF
Tick:   1137367
TB:     -143021795
29-JAN-20 23:30 :30
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1137366
TB:     -143024099
29-JAN-20 23:30 :30
========================================
Paused       MULTIROBOTTASK,   4       
   (TASK:1,TB:-143054959)              
29-JAN-20 23:30 :30
========================================
Run FWD      MULTIROBOTTASK,   4       
   (TASK:1,TB:-145800667)              
29-JAN-20 23:30 :28
========================================
 SO[    1]    OFF -> ON 
Tick:   1136185
TB:     -145942166
29-JAN-20 23:30 :28
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1136184
TB:     -145943744
29-JAN-20 23:30 :28
========================================
 SO[    1]    ON  -> OFF
Tick:   1134457
TB:     -150311738
29-JAN-20 23:30 :26
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1134456
TB:     -150318250
29-JAN-20 23:30 :26
========================================
Paused       MULTIROBOTTASK,   3       
   (TASK:1,TB:-150398001)              
29-JAN-20 23:30 :26
========================================
Run FWD      MULTIROBOTTASK,   3       
   (TASK:1,TB:-155296256)              
29-JAN-20 23:30 :24
========================================
 SO[    1]    OFF -> ON 
Tick:   1132501
TB:     -155347017
29-JAN-20 23:30 :24
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1132500
TB:     -155349210
29-JAN-20 23:30 :24
========================================
 SO[    1]    ON  -> OFF
Tick:   1132249
TB:     -156002629
29-JAN-20 23:30 :24
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1132248
TB:     -156003845
29-JAN-20 23:30 :24
========================================
Paused       MULTIROBOTTASK,   2       
   (TASK:1,TB:-156111745)              
29-JAN-20 23:30 :24
========================================
Run FWD      MULTIROBOTTASK,   2       
   (TASK:1,TB:-163505082)              
29-JAN-20 23:30 :20
========================================
 SO[    1]    OFF -> ON 
Tick:   1129237
TB:     -163566110
29-JAN-20 23:30 :20
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1129236
TB:     -163567477
29-JAN-20 23:30 :20
========================================
 SO[    1]    ON  -> OFF
Tick:   1127893
TB:     -166919367
29-JAN-20 23:30 :20
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1127892
TB:     -166922436
29-JAN-20 23:30 :20
========================================
Paused       MULTIROBOTTASK,   1       
   (TASK:1,TB:-167019230)              
29-JAN-20 23:30 :20
========================================
 SO[    1]    OFF -> ON 
Tick:   1127545
TB:     -167766189
29-JAN-20 23:30 :20
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1127544
TB:     -167767186
29-JAN-20 23:30 :20
========================================
Run FWD      MULTIROBOTTASK,   1       
   (TASK:1,TB:-167906020)              
29-JAN-20 23:30 :18
========================================
 SO[    1]    ON  -> OFF
Tick:   1102261
TB:     -231286592
29-JAN-20 23:29 :50
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1102260
TB:     -231289665
29-JAN-20 23:29 :50
========================================
Paused       MULTIROBOTTASK,   2       
   (TASK:1,TB:-231344448)              
29-JAN-20 23:29 :50
========================================
Run FWD      MULTIROBOTTASK,   3       
   (TASK:1,TB:-231344516)              
29-JAN-20 23:29 :50
========================================
 SO[    1]    OFF -> ON 
Tick:   1102231
TB:     -231356223
29-JAN-20 23:29 :50
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1102230
TB:     -231357223
29-JAN-20 23:29 :50
========================================
 SO[    1]    ON  -> OFF
Tick:   1101337
TB:     -233590514
29-JAN-20 23:29 :50
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1101336
TB:     -233591701
29-JAN-20 23:29 :50
========================================
Paused       MULTIROBOTTASK,   2       
   (TASK:1,TB:-233690951)              
29-JAN-20 23:29 :50
========================================
Run FWD      MULTIROBOTTASK,   2       
   (TASK:1,TB:-233690989)              
29-JAN-20 23:29 :50
========================================
 SO[    1]    OFF -> ON 
Tick:   1101271
TB:     -233756241
29-JAN-20 23:29 :50
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1101270
TB:     -233758561
29-JAN-20 23:29 :50
========================================
 SO[    1]    ON  -> OFF
Tick:   1100665
TB:     -235257943
29-JAN-20 23:29 :48
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1100664
TB:     -235259492
29-JAN-20 23:29 :48
========================================
Paused       MULTIROBOTTASK,   2       
   (TASK:1,TB:-235309817)              
29-JAN-20 23:29 :48
========================================
Run FWD      MULTIROBOTTASK,   3       
   (TASK:1,TB:-235310030)              
29-JAN-20 23:29 :48
========================================
 SO[    1]    OFF -> ON 
Tick:   1100629
TB:     -235347631
29-JAN-20 23:29 :48
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1100628
TB:     -235348809
29-JAN-20 23:29 :48
========================================
 SO[    1]    ON  -> OFF
Tick:   1099639
TB:     -237832906
29-JAN-20 23:29 :48
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1099638
TB:     -237835312
29-JAN-20 23:29 :48
========================================
Paused       MULTIROBOTTASK,   2       
   (TASK:1,TB:-237895382)              
29-JAN-20 23:29 :48
========================================
Run FWD      MULTIROBOTTASK,   2       
   (TASK:1,TB:-237895427)              
29-JAN-20 23:29 :48
========================================
 SO[    1]    OFF -> ON 
Tick:   1099609
TB:     -237900721
29-JAN-20 23:29 :48
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1099608
TB:     -237910662
29-JAN-20 23:29 :48
========================================
 SO[    1]    ON  -> OFF
Tick:   1098103
TB:     -241647281
29-JAN-20 23:29 :46
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1098102
TB:     -241649460
29-JAN-20 23:29 :46
========================================
Paused       MULTIROBOTTASK,   2       
   (TASK:1,TB:-241703076)              
29-JAN-20 23:29 :46
========================================
Run FWD      MULTIROBOTTASK,   3       
   (TASK:1,TB:-241703143)              
29-JAN-20 23:29 :46
========================================
 SO[    1]    OFF -> ON 
Tick:   1098073
TB:     -241719008
29-JAN-20 23:29 :46
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1098072
TB:     -241720580
29-JAN-20 23:29 :46
========================================
 SO[    1]    ON  -> OFF
Tick:   1097815
TB:     -242386965
29-JAN-20 23:29 :46
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1097814
TB:     -242389049
29-JAN-20 23:29 :46
========================================
Paused       MULTIROBOTTASK,   2       
   (TASK:1,TB:-242410315)              
29-JAN-20 23:29 :46
========================================
Run FWD      MULTIROBOTTASK,   2       
   (TASK:1,TB:-242410370)              
29-JAN-20 23:29 :46
========================================
 SO[    1]    OFF -> ON 
Tick:   1097785
TB:     -242458769
29-JAN-20 23:29 :46
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1097784
TB:     -242460144
29-JAN-20 23:29 :46
========================================
 SO[    1]    ON  -> OFF
Tick:   1097239
TB:     -243827141
29-JAN-20 23:29 :46
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1097238
TB:     -243834761
29-JAN-20 23:29 :46
========================================
Paused       MULTIROBOTTASK,   2       
   (TASK:1,TB:-243901273)              
29-JAN-20 23:29 :46
========================================
Run FWD      MULTIROBOTTASK,   3       
   (TASK:1,TB:-243901345)              
29-JAN-20 23:29 :46
========================================
 SO[    1]    OFF -> ON 
Tick:   1097209
TB:     -243908683
29-JAN-20 23:29 :46
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1097208
TB:     -243909984
29-JAN-20 23:29 :46
========================================
 SO[    1]    ON  -> OFF
Tick:   1096501
TB:     -245643918
29-JAN-20 23:29 :44
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1096500
TB:     -245646526
29-JAN-20 23:29 :44
========================================
Paused       MULTIROBOTTASK,   2       
   (TASK:1,TB:-245759243)              
29-JAN-20 23:29 :44
========================================
Run FWD      MULTIROBOTTASK,   2       
   (TASK:1,TB:-245759289)              
29-JAN-20 23:29 :44
========================================
 SO[    1]    OFF -> ON 
Tick:   1096441
TB:     -245827852
29-JAN-20 23:29 :44
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1096440
TB:     -245830656
29-JAN-20 23:29 :44
========================================
 SO[    1]    ON  -> OFF
Tick:   1095157
TB:     -248951261
29-JAN-20 23:29 :42
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1095156
TB:     -248951965
29-JAN-20 23:29 :42
========================================
Paused       MULTIROBOTTASK,   2       
   (TASK:1,TB:-249098537)              
29-JAN-20 23:29 :42
========================================
Run FWD      MULTIROBOTTASK,   3       
   (TASK:1,TB:-249098658)              
29-JAN-20 23:29 :42
========================================
 SO[    1]    OFF -> ON 
Tick:   1095097
TB:     -249123819
29-JAN-20 23:29 :42
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1095096
TB:     -249124944
29-JAN-20 23:29 :42
========================================
 SO[    1]    ON  -> OFF
Tick:   1090873
TB:     -259697138
29-JAN-20 23:29 :38
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1090872
TB:     -259697369
29-JAN-20 23:29 :38
========================================
Paused       MULTIROBOTTASK,   2       
   (TASK:1,TB:-259826962)              
29-JAN-20 23:29 :38
========================================
Run FWD      MULTIROBOTTASK,   2       
   (TASK:1,TB:-259827021)              
29-JAN-20 23:29 :38
========================================
 SO[    1]    OFF -> ON 
Tick:   1090807
TB:     -259869036
29-JAN-20 23:29 :38
========================================
 UO[    3]    OFF -> ON 
 UO[    4]    ON  -> OFF
 UO[   18]    OFF -> ON 
Tick:   1090806
TB:     -259872042
29-JAN-20 23:29 :38
========================================
 SO[    1]    ON  -> OFF
Tick:   1090105
TB:     -261608986
29-JAN-20 23:29 :38
========================================
 UO[    3]    ON  -> OFF
 UO[    4]    OFF -> ON 
 UO[   18]    ON  -> OFF
Tick:   1090104
TB:     -261610253
29-JAN-20 23:29 :38
========================================
Paused       MULTIROBOTTASK,   1       
   (TASK:1,TB:-261667308)              
29-JAN-20 23:29 :38
========================================
 SO[    1]    OFF -> ON 
Tick:   1087285
TB:     -268706464
29-JAN-20 23:29 :34
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   1087284
TB:     -268707902
29-JAN-20 23:29 :34
========================================
Run FWD      MULTIROBOTTASK,   1       
   (TASK:1,TB:-268756642)              
29-JAN-20 23:29 :34
========================================
 SO[    3]    ON  -> OFF
Tick:   776377
TB:     -1050471704
29-JAN-20 23:23 :46
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   776376
TB:     -1050473107
29-JAN-20 23:23 :46
========================================
 SO[    3]    OFF -> ON 
Tick:   776089
TB:     -1051168496
29-JAN-20 23:23 :44
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   776088
TB:     -1051169785
29-JAN-20 23:23 :44
========================================
 SO[    7]    OFF -> ON 
Tick:   776053
TB:     -1051258155
29-JAN-20 23:23 :44
========================================
 UO[    8]    OFF -> ON 
Tick:   776052
TB:     -1051258310
29-JAN-20 23:23 :44
========================================
 SO[    1]    ON  -> OFF
Tick:   775927
TB:     -1051587858
29-JAN-20 23:23 :44
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   775926
TB:     -1051590053
29-JAN-20 23:23 :44
========================================
Aborted      PRO_MOV2    ,   0         
 (TASK:7,TB:-1051647830)               
29-JAN-20 23:23 :44
========================================
 SO[    1]    OFF -> ON 
Tick:   775321
TB:     -1053084658
29-JAN-20 23:23 :44
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   775320
TB:     -1053086019
29-JAN-20 23:23 :44
========================================
Run FWD      PRO_MOV2    ,   3         
 (TASK:7,TB:-1053168310)               
29-JAN-20 23:23 :44
========================================
Run FWD      PRO_MOV2    ,   2         
 (TASK:7,TB:-1053168352)               
29-JAN-20 23:23 :44
========================================
Run FWD      PRO_MOV2    ,   1         
 (TASK:7,TB:-1053168413)               
29-JAN-20 23:23 :44
========================================
 SO[    3]    ON  -> OFF
Tick:   774871
TB:     -1054223398
29-JAN-20 23:23 :44
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   774870
TB:     -1054225643
29-JAN-20 23:23 :44
========================================
 SO[    3]    OFF -> ON 
Tick:   774649
TB:     -1054782844
29-JAN-20 23:23 :44
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   774648
TB:     -1054783058
29-JAN-20 23:23 :44
========================================
 SO[    7]    ON  -> OFF
Tick:   774613
TB:     -1054959765
29-JAN-20 23:23 :44
========================================
 UO[    8]    ON  -> OFF
Tick:   774612
TB:     -1054960626
29-JAN-20 23:23 :44
========================================
 SO[    3]    ON  -> OFF
Tick:   425623
TB:     -1936823409
29-JAN-20 23:17 :10
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   425622
TB:     -1936825653
29-JAN-20 23:17 :10
========================================
 SO[    3]    OFF -> ON 
Tick:   425401
TB:     -1937404471
29-JAN-20 23:17 :10
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   425400
TB:     -1937405350
29-JAN-20 23:17 :10
========================================
 SO[    7]    OFF -> ON 
Tick:   425209
TB:     -1937897001
29-JAN-20 23:17 :10
========================================
 UO[    8]    OFF -> ON 
Tick:   425208
TB:     -1937898539
29-JAN-20 23:17 :10
========================================
 SO[    1]    ON  -> OFF
Tick:   425077
TB:     -1938232638
29-JAN-20 23:17 :10
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   425076
TB:     -1938233808
29-JAN-20 23:17 :10
========================================
Aborted      PRO_MOV2    ,   0         
 (TASK:7,TB:-1938288494)               
29-JAN-20 23:17 :08
========================================
 SO[    1]    OFF -> ON 
Tick:   424663
TB:     -1939286320
29-JAN-20 23:17 :08
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   424662
TB:     -1939288409
29-JAN-20 23:17 :08
========================================
Run FWD      PRO_MOV2    ,   3         
 (TASK:7,TB:-1939307798)               
29-JAN-20 23:17 :08
========================================
Run FWD      PRO_MOV2    ,   2         
 (TASK:7,TB:-1939307877)               
29-JAN-20 23:17 :08
========================================
Run FWD      PRO_MOV2    ,   1         
 (TASK:7,TB:-1939307918)               
29-JAN-20 23:17 :08
========================================
 SO[    3]    ON  -> OFF
Tick:   424501
TB:     -1939815310
29-JAN-20 23:17 :08
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   424500
TB:     -1939815441
29-JAN-20 23:17 :08
========================================
 UO[    2]    ON  -> OFF
Tick:   424182
TB:     -1940673780
29-JAN-20 23:17 :08
========================================
 UO[    2]    OFF -> ON 
Tick:   424152
TB:     -1940738999
29-JAN-20 23:17 :08
========================================
 SO[    3]    OFF -> ON 
Tick:   423925
TB:     -1941547173
29-JAN-20 23:17 :08
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   423924
TB:     -1941547678
29-JAN-20 23:17 :08
========================================
 SO[    7]    ON  -> OFF
Tick:   423895
TB:     -1941614881
29-JAN-20 23:17 :08
========================================
 UO[    8]    ON  -> OFF
Tick:   423894
TB:     -1941615917
29-JAN-20 23:17 :08
========================================
 SO[    3]    ON  -> OFF
Tick:   421399
TB:     -1948067287
29-JAN-20 23:17 :04
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   421398
TB:     -1948069514
29-JAN-20 23:17 :04
========================================
 SO[    3]    OFF -> ON 
Tick:   421177
TB:     -1948634517
29-JAN-20 23:17 :04
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   421176
TB:     -1948634690
29-JAN-20 23:17 :04
========================================
 SO[    7]    OFF -> ON 
Tick:   421045
TB:     -1949008486
29-JAN-20 23:17 :04
========================================
 UO[    8]    OFF -> ON 
Tick:   421044
TB:     -1949009950
29-JAN-20 23:17 :04
========================================
 SO[    1]    ON  -> OFF
Tick:   420919
TB:     -1949324171
29-JAN-20 23:17 :04
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   420918
TB:     -1949326123
29-JAN-20 23:17 :04
========================================
Aborted      PRO_MOV2    ,   0         
 (TASK:7,TB:-1949404482)               
29-JAN-20 23:17 :04
========================================
 SO[    1]    OFF -> ON 
Tick:   420409
TB:     -1950510021
29-JAN-20 23:17 :04
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   420408
TB:     -1950511337
29-JAN-20 23:17 :04
========================================
Run FWD      PRO_MOV2    ,   3         
 (TASK:7,TB:-1950587467)               
29-JAN-20 23:17 :04
========================================
Run FWD      PRO_MOV2    ,   2         
 (TASK:7,TB:-1950587510)               
29-JAN-20 23:17 :04
========================================
Run FWD      PRO_MOV2    ,   1         
 (TASK:7,TB:-1950587565)               
29-JAN-20 23:17 :04
========================================
 SO[    3]    ON  -> OFF
Tick:   419833
TB:     -1951924152
29-JAN-20 23:17 :02
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   419832
TB:     -1951925703
29-JAN-20 23:17 :02
========================================
 SO[    3]    OFF -> ON 
Tick:   419605
TB:     -1952544974
29-JAN-20 23:17 :02
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   419604
TB:     -1952545941
29-JAN-20 23:17 :02
========================================
 SO[    7]    ON  -> OFF
Tick:   419575
TB:     -1952618950
29-JAN-20 23:17 :02
========================================
 UO[    8]    ON  -> OFF
Tick:   419574
TB:     -1952621094
29-JAN-20 23:17 :02
========================================
 SO[    3]    ON  -> OFF
Tick:   413305
TB:     -1968434609
29-JAN-20 23:16 :56
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   413304
TB:     -1968435319
29-JAN-20 23:16 :56
========================================
 SO[    3]    OFF -> ON 
Tick:   413077
TB:     -1969029814
29-JAN-20 23:16 :56
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   413076
TB:     -1969031676
29-JAN-20 23:16 :56
========================================
 SO[    7]    OFF -> ON 
Tick:   413017
TB:     -1969205571
29-JAN-20 23:16 :56
========================================
 UO[    8]    OFF -> ON 
Tick:   413016
TB:     -1969206246
29-JAN-20 23:16 :56
========================================
 SO[    1]    ON  -> OFF
Tick:   412855
TB:     -1969597707
29-JAN-20 23:16 :56
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   412854
TB:     -1969599817
29-JAN-20 23:16 :56
========================================
Aborted      PRO_MOV2    ,   0         
 (TASK:7,TB:-1969612586)               
29-JAN-20 23:16 :56
========================================
 SO[    1]    OFF -> ON 
Tick:   412441
TB:     -1970648918
29-JAN-20 23:16 :54
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   412440
TB:     -1970650272
29-JAN-20 23:16 :54
========================================
Run FWD      PRO_MOV2    ,   3         
 (TASK:7,TB:-1970724784)               
29-JAN-20 23:16 :54
========================================
Run FWD      PRO_MOV2    ,   2         
 (TASK:7,TB:-1970724826)               
29-JAN-20 23:16 :54
========================================
Run FWD      PRO_MOV2    ,   1         
 (TASK:7,TB:-1970724878)               
29-JAN-20 23:16 :54
========================================
 SO[    3]    ON  -> OFF
Tick:   412021
TB:     -1971715601
29-JAN-20 23:16 :54
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   412020
TB:     -1971716573
29-JAN-20 23:16 :54
========================================
 SO[    3]    OFF -> ON 
Tick:   411607
TB:     -1972865282
29-JAN-20 23:16 :54
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   411606
TB:     -1972867415
29-JAN-20 23:16 :54
========================================
 SO[    7]    ON  -> OFF
Tick:   411577
TB:     -1972981033
29-JAN-20 23:16 :54
========================================
 UO[    8]    ON  -> OFF
Tick:   411576
TB:     -1972982978
29-JAN-20 23:16 :54
========================================
 SO[    3]    ON  -> OFF
Tick:   409717
TB:     -1977821646
29-JAN-20 23:16 :52
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   409716
TB:     -1977852776
29-JAN-20 23:16 :52
========================================
 SO[    3]    OFF -> ON 
Tick:   409495
TB:     -1978412153
29-JAN-20 23:16 :52
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   409494
TB:     -1978414189
29-JAN-20 23:16 :52
========================================
 SO[    7]    OFF -> ON 
Tick:   409465
TB:     -1978497092
29-JAN-20 23:16 :52
========================================
 UO[    8]    OFF -> ON 
Tick:   409464
TB:     -1978498675
29-JAN-20 23:16 :52
========================================
 SO[    1]    ON  -> OFF
Tick:   409333
TB:     -1978840610
29-JAN-20 23:16 :50
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   409332
TB:     -1978842897
29-JAN-20 23:16 :50
========================================
Aborted      PRO_MOV2    ,   0         
 (TASK:7,TB:-1978926873)               
29-JAN-20 23:16 :50
========================================
 SO[    1]    OFF -> ON 
Tick:   408823
TB:     -1980119785
29-JAN-20 23:16 :50
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   408822
TB:     -1980121711
29-JAN-20 23:16 :50
========================================
Run FWD      PRO_MOV2    ,   3         
 (TASK:7,TB:-1980142664)               
29-JAN-20 23:16 :50
========================================
Run FWD      PRO_MOV2    ,   2         
 (TASK:7,TB:-1980142692)               
29-JAN-20 23:16 :50
========================================
Run FWD      PRO_MOV2    ,   1         
 (TASK:7,TB:-1980142732)               
29-JAN-20 23:16 :50
========================================
 UO[    2]    OFF -> ON 
Tick:   408408
TB:     -1981299883
29-JAN-20 23:16 :50
========================================
 UO[    2]    ON  -> OFF
Tick:   408276
TB:     -1981658137
29-JAN-20 23:16 :50
========================================
 SO[    7]    ON  -> OFF
Tick:   408247
TB:     -1981755878
29-JAN-20 23:16 :50
========================================
 UO[    8]    ON  -> OFF
Tick:   408246
TB:     -1981757554
29-JAN-20 23:16 :50
========================================
 SO[    3]    ON  -> OFF
Tick:   405781
TB:     -1987977526
29-JAN-20 23:16 :46
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   405780
TB:     -1987977996
29-JAN-20 23:16 :46
========================================
 SO[    3]    OFF -> ON 
Tick:   405589
TB:     -1988501544
29-JAN-20 23:16 :46
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   405588
TB:     -1988502295
29-JAN-20 23:16 :46
========================================
 SO[    7]    OFF -> ON 
Tick:   405271
TB:     -1989294680
29-JAN-20 23:16 :46
========================================
 UO[    8]    OFF -> ON 
Tick:   405270
TB:     -1989297270
29-JAN-20 23:16 :46
========================================
 SO[    1]    ON  -> OFF
Tick:   405079
TB:     -1989891125
29-JAN-20 23:16 :46
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   405078
TB:     -1989893482
29-JAN-20 23:16 :46
========================================
Aborted      PRO_MOV2    ,   0         
 (TASK:7,TB:-1989915276)               
29-JAN-20 23:16 :46
========================================
 SO[    1]    OFF -> ON 
Tick:   404533
TB:     -1991251608
29-JAN-20 23:16 :46
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   404532
TB:     -1991252603
29-JAN-20 23:16 :46
========================================
Run FWD      PRO_MOV2    ,   3         
 (TASK:7,TB:-1991273900)               
29-JAN-20 23:16 :46
========================================
Run FWD      PRO_MOV2    ,   2         
 (TASK:7,TB:-1991273940)               
29-JAN-20 23:16 :46
========================================
Run FWD      PRO_MOV2    ,   1         
 (TASK:7,TB:-1991273998)               
29-JAN-20 23:16 :46
========================================
 SO[    3]    ON  -> OFF
Tick:   403927
TB:     -1992905449
29-JAN-20 23:16 :44
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   403926
TB:     -1992906836
29-JAN-20 23:16 :44
========================================
 SO[    3]    OFF -> ON 
Tick:   403543
TB:     -1993979043
29-JAN-20 23:16 :44
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   403542
TB:     -1993981271
29-JAN-20 23:16 :44
========================================
 SO[    7]    ON  -> OFF
Tick:   403513
TB:     -1994050242
29-JAN-20 23:16 :44
========================================
 UO[    8]    ON  -> OFF
Tick:   403512
TB:     -1994050521
29-JAN-20 23:16 :44
========================================
 SO[    3]    ON  -> OFF
Tick:   365017
TB:     -2092662614
29-JAN-20 23:16 :00
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   365016
TB:     -2092663779
29-JAN-20 23:16 :00
========================================
 SO[    3]    OFF -> ON 
Tick:   364789
TB:     -2093241005
29-JAN-20 23:16 :00
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   364788
TB:     -2093241893
29-JAN-20 23:16 :00
========================================
 SO[    7]    OFF -> ON 
Tick:   364663
TB:     -2093570441
29-JAN-20 23:16 :00
========================================
 UO[    8]    OFF -> ON 
Tick:   364662
TB:     -2093572260
29-JAN-20 23:16 :00
========================================
 SO[    1]    ON  -> OFF
Tick:   364537
TB:     -2093877420
29-JAN-20 23:16 :00
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   364536
TB:     -2093878815
29-JAN-20 23:16 :00
========================================
Aborted      PRO_MOV2    ,   0         
 (TASK:7,TB:-2093980038)               
29-JAN-20 23:16 :00
========================================
 SO[    1]    OFF -> ON 
Tick:   363703
TB:     -2095976546
29-JAN-20 23:15 :58
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   363702
TB:     -2095979663
29-JAN-20 23:15 :58
========================================
Run FWD      PRO_MOV2    ,   3         
 (TASK:7,TB:-2096019351)               
29-JAN-20 23:15 :58
========================================
Run FWD      PRO_MOV2    ,   2         
 (TASK:7,TB:-2096019380)               
29-JAN-20 23:15 :58
========================================
Run FWD      PRO_MOV2    ,   1         
 (TASK:7,TB:-2096019434)               
29-JAN-20 23:15 :58
========================================
 SO[    3]    ON  -> OFF
Tick:   363127
TB:     -2097395818
29-JAN-20 23:15 :58
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   363126
TB:     -2097398165
29-JAN-20 23:15 :58
========================================
 SO[    3]    OFF -> ON 
Tick:   362869
TB:     -2098122163
29-JAN-20 23:15 :58
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   362868
TB:     -2098123180
29-JAN-20 23:15 :58
========================================
 SO[    7]    ON  -> OFF
Tick:   362839
TB:     -2098188311
29-JAN-20 23:15 :58
========================================
 UO[    8]    ON  -> OFF
Tick:   362838
TB:     -2098189812
29-JAN-20 23:15 :58
========================================
 SO[    3]    ON  -> OFF
Tick:   358999
TB:     -2107673242
29-JAN-20 23:15 :54
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   358998
TB:     -2107680596
29-JAN-20 23:15 :54
========================================
 SO[    3]    OFF -> ON 
Tick:   358777
TB:     -2108210089
29-JAN-20 23:15 :54
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   358776
TB:     -2108211046
29-JAN-20 23:15 :54
========================================
 SO[    7]    OFF -> ON 
Tick:   358645
TB:     -2108730526
29-JAN-20 23:15 :52
========================================
 UO[    8]    OFF -> ON 
Tick:   358644
TB:     -2108733054
29-JAN-20 23:15 :52
========================================
 SO[    1]    ON  -> OFF
Tick:   358519
TB:     -2109041460
29-JAN-20 23:15 :52
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   358518
TB:     -2109045277
29-JAN-20 23:15 :52
========================================
Aborted      PRO_MOV2    ,   0         
 (TASK:7,TB:-2109123188)               
29-JAN-20 23:15 :52
========================================
 SO[    1]    OFF -> ON 
Tick:   357685
TB:     -2111025604
29-JAN-20 23:15 :52
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   357684
TB:     -2111025745
29-JAN-20 23:15 :52
========================================
Run FWD      PRO_MOV2    ,   3         
 (TASK:7,TB:-2111105327)               
29-JAN-20 23:15 :52
========================================
Run FWD      PRO_MOV2    ,   2         
 (TASK:7,TB:-2111105380)               
29-JAN-20 23:15 :52
========================================
Run FWD      PRO_MOV2    ,   1         
 (TASK:7,TB:-2111105465)               
29-JAN-20 23:15 :52
========================================
 SO[    3]    ON  -> OFF
Tick:   356821
TB:     -2113164356
29-JAN-20 23:15 :50
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   356820
TB:     -2113165401
29-JAN-20 23:15 :50
========================================
 SO[    3]    OFF -> ON 
Tick:   356569
TB:     -2113866146
29-JAN-20 23:15 :50
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   356568
TB:     -2113867684
29-JAN-20 23:15 :50
========================================
 SO[    7]    ON  -> OFF
Tick:   356533
TB:     -2113951920
29-JAN-20 23:15 :50
========================================
 UO[    8]    ON  -> OFF
Tick:   356532
TB:     -2113952067
29-JAN-20 23:15 :50
========================================
 SO[    3]    ON  -> OFF
Tick:   353017
TB:     -2122763430
29-JAN-20 23:15 :46
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   353016
TB:     -2122765109
29-JAN-20 23:15 :46
========================================
 SO[    3]    OFF -> ON 
Tick:   352789
TB:     -2123334472
29-JAN-20 23:15 :46
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   352788
TB:     -2123335835
29-JAN-20 23:15 :46
========================================
 SO[    7]    OFF -> ON 
Tick:   352597
TB:     -2123802897
29-JAN-20 23:15 :46
========================================
 UO[    8]    OFF -> ON 
Tick:   352596
TB:     -2123804605
29-JAN-20 23:15 :46
========================================
 SO[    1]    ON  -> OFF
Tick:   352375
TB:     -2124362604
29-JAN-20 23:15 :46
========================================
 UO[    3]    ON  -> OFF
 UO[   18]    ON  -> OFF
Tick:   352374
TB:     -2124365754
29-JAN-20 23:15 :46
========================================
Aborted      PRO_MOV2    ,   0         
 (TASK:7,TB:-2124389880)               
29-JAN-20 23:15 :46
========================================
 SO[    1]    OFF -> ON 
Tick:   351925
TB:     -2125582715
29-JAN-20 23:15 :46
========================================
 UO[    3]    OFF -> ON 
 UO[   18]    OFF -> ON 
Tick:   351924
TB:     -2125583875
29-JAN-20 23:15 :46
========================================
Run FWD      PRO_MOV2    ,   3         
 (TASK:7,TB:-2125602116)               
29-JAN-20 23:15 :46
========================================
Run FWD      PRO_MOV2    ,   2         
 (TASK:7,TB:-2125602143)               
29-JAN-20 23:15 :46
========================================
Run FWD      PRO_MOV2    ,   1         
 (TASK:7,TB:-2125602209)               
29-JAN-20 23:15 :46
========================================
 SO[    3]    ON  -> OFF
Tick:   350809
TB:     -2128505381
29-JAN-20 23:15 :44
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   350808
TB:     -2128508754
29-JAN-20 23:15 :44
========================================
 SO[    3]    OFF -> ON 
Tick:   350425
TB:     -2129576405
29-JAN-20 23:15 :44
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   350424
TB:     -2129577955
29-JAN-20 23:15 :44
========================================
 SO[    7]    ON  -> OFF
Tick:   350389
TB:     -2129656868
29-JAN-20 23:15 :44
========================================
 UO[    8]    ON  -> OFF
Tick:   350388
TB:     -2129657024
29-JAN-20 23:15 :44
========================================
 SO[    3]    ON  -> OFF
Tick:   329623
TB:     2114586955
29-JAN-20 23:15 :20
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   329622
TB:     2114584656
29-JAN-20 23:15 :20
========================================
 SO[    3]    OFF -> ON 
Tick:   329401
TB:     2113800181
29-JAN-20 23:15 :20
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   329400
TB:     2113798678
29-JAN-20 23:15 :20
========================================
 SO[    7]    OFF -> ON 
Tick:   329077
TB:     2113000078
29-JAN-20 23:15 :20
========================================
 UO[    8]    OFF -> ON 
Tick:   329076
TB:     2112998486
29-JAN-20 23:15 :20
========================================
 UO[    2]    OFF -> ON 
Tick:   408
TB:     1287291275
29-JAN-20 23:09 :12
========================================
 AO[    3]    0
 AO[    3]    0
 AO[    5]    0
 AO[    5]    0
 AO[    7]    0
 UI[    1]    ON 
 UI[    2]    ON 
 UI[    3]    ON 
 UI[    4]    OFF
 UI[    5]    OFF
 UI[    6]    OFF
 UI[    7]    OFF
 UI[    8]    ON 
 UI[   17]    OFF
 UI[   18]    OFF
 UI[   19]    OFF
 UI[   20]    OFF
 UI[   21]    OFF
 UI[   22]    OFF
 UI[   23]    OFF
 UI[   24]    OFF
 UI[   33]    OFF
 UI[   34]    OFF
 UO[    1]    OFF
 UO[    2]    OFF
 UO[    3]    OFF
 UO[    4]    OFF
 UO[    5]    OFF
 UO[    6]    OFF
 UO[    7]    OFF
 UO[    8]    OFF
 UO[   17]    OFF
 UO[   18]    OFF
 UO[   19]    OFF
 UO[   20]    OFF
 UO[   21]    OFF
 UO[   22]    OFF
 UO[   23]    OFF
 UO[   24]    OFF
 UO[   33]    OFF
 UO[   34]    OFF
 UO[   35]    OFF
 UO[   36]    OFF
Tick:   234
TB:     1284699465
29-JAN-20 23:09 :10
========================================
 AI[   17]    0
 AI[   13]    0
 AI[   15]    0
 AI[   17]    0
 AI[   19]    0
 AI[   21]    0
 AI[   23]    0
 AO[    1]    0
Tick:   233
TB:     1284699337
29-JAN-20 23:09 :10
========================================
 AI[    7]    0
 AI[    9]    0
 AI[   11]    0
 AI[    7]    0
 AI[    9]    0
 AI[   11]    0
 AI[   13]    0
 AI[   15]    0
Tick:   232
TB:     1284673429
29-JAN-20 23:09 :10
========================================
 DO[   65]    OFF
 DO[   66]    OFF
 DO[   67]    OFF
 DO[   68]    OFF
 DO[   69]    OFF
 DO[   70]    OFF
 DO[   71]    OFF
 DO[   72]    OFF
 DO[   73]    OFF
 DO[   74]    OFF
 DO[   75]    OFF
 DO[   76]    OFF
 DO[   77]    OFF
 DO[   78]    OFF
 DO[   79]    OFF
 DO[   80]    OFF
 DO[   81]    OFF
 DO[   82]    OFF
 DO[   83]    OFF
 DO[   84]    OFF
 DO[   85]    OFF
 DO[   86]    OFF
 DO[   87]    OFF
 DO[   88]    OFF
 DO[   89]    OFF
 DO[   90]    OFF
 DO[   91]    OFF
 DO[   92]    OFF
 DO[   93]    OFF
 DO[   94]    OFF
 DO[   95]    OFF
 DO[   96]    OFF
 DO[   97]    OFF
 DO[   98]    OFF
 DO[   99]    OFF
 DO[  100]    OFF
 DO[  101]    OFF
 DO[  102]    OFF
 DO[  103]    OFF
 DO[  104]    OFF
 DO[  105]    OFF
 DO[  106]    OFF
 DO[  107]    OFF
 DO[  108]    OFF
 DO[  109]    OFF
 DO[  110]    OFF
 DO[  111]    OFF
 DO[  112]    OFF
 DO[  113]    OFF
 DO[  114]    OFF
 DO[  115]    OFF
 DO[  116]    OFF
 DO[  117]    OFF
 DO[  118]    OFF
 DO[  119]    OFF
 DO[  120]    OFF
 DO[  121]    OFF
 DO[  122]    OFF
 DO[  123]    OFF
 DO[  124]    OFF
 DO[  125]    OFF
 DO[  126]    OFF
 DO[  127]    OFF
 DO[  128]    OFF
 DO[  129]    OFF
 DO[  130]    OFF
 DO[  131]    OFF
 DO[  132]    OFF
 DO[  133]    OFF
 DO[  134]    OFF
 DO[  135]    OFF
 DO[  136]    OFF
 DO[  137]    OFF
 DO[  138]    OFF
 DO[  139]    OFF
 DO[  140]    OFF
 DO[  141]    OFF
 DO[  142]    OFF
 DO[  143]    OFF
 DO[  144]    OFF
 AI[    1]    0
 AI[    3]    0
 AI[    5]    0
Tick:   231
TB:     1284664123
29-JAN-20 23:09 :10
========================================
 DI[   81]    OFF
 DI[   82]    OFF
 DI[   83]    OFF
 DI[   84]    OFF
 DI[   85]    OFF
 DI[   86]    OFF
 DI[   87]    OFF
 DI[   88]    OFF
 DI[   89]    OFF
 DI[   90]    OFF
 DI[   91]    OFF
 DI[   92]    OFF
 DI[   93]    OFF
 DI[   94]    OFF
 DI[   95]    OFF
 DI[   96]    OFF
 DI[   97]    OFF
 DI[   98]    OFF
 DI[   99]    OFF
 DI[  100]    OFF
 DI[  101]    OFF
 DI[  102]    OFF
 DI[  103]    OFF
 DI[  104]    OFF
 DI[  105]    OFF
 DI[  106]    OFF
 DI[  107]    OFF
 DI[  108]    OFF
 DI[  109]    OFF
 DI[  110]    OFF
 DI[  111]    OFF
 DI[  112]    OFF
 DI[  113]    OFF
 DI[  114]    OFF
 DI[  115]    OFF
 DI[  116]    OFF
 DI[  117]    OFF
 DI[  118]    OFF
 DI[  119]    OFF
 DI[  120]    OFF
 DI[  121]    OFF
 DI[  122]    OFF
 DI[  123]    OFF
 DI[  124]    OFF
 DI[  125]    OFF
 DI[  126]    OFF
 DI[  127]    OFF
 DI[  128]    OFF
 DI[  129]    OFF
 DI[  130]    OFF
 DI[  131]    OFF
 DI[  132]    OFF
 DI[  133]    OFF
 DI[  134]    OFF
 DI[  135]    OFF
 DI[  136]    OFF
 DI[  137]    OFF
 DI[  138]    OFF
 DI[  139]    OFF
 DI[  140]    OFF
 DI[  141]    OFF
 DI[  142]    OFF
 DI[  143]    OFF
 DI[  144]    OFF
 DO[   21]    OFF
 DO[   22]    OFF
 DO[   23]    OFF
 DO[   24]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
 DO[   41]    OFF
 DO[   42]    OFF
 DO[   43]    OFF
 DO[   44]    OFF
 DO[   53]    OFF
 DO[   54]    OFF
 DO[   55]    OFF
 DO[   56]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   29]    OFF
 DO[   30]    OFF
 DO[   31]    OFF
 DO[   32]    OFF
 DO[   33]    OFF
 DO[   34]    OFF
 DO[   35]    OFF
 DO[   36]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
 DO[   41]    OFF
 DO[   42]    OFF
 DO[   43]    OFF
 DO[   44]    OFF
 DO[   45]    OFF
 DO[   46]    OFF
 DO[   47]    OFF
 DO[   48]    OFF
 DO[   49]    OFF
 DO[   50]    OFF
 DO[   51]    OFF
 DO[   52]    OFF
 DO[   53]    OFF
 DO[   54]    OFF
 DO[   55]    OFF
 DO[   56]    OFF
 DO[   57]    OFF
 DO[   58]    OFF
 DO[   59]    OFF
 DO[   60]    OFF
 DO[   61]    OFF
 DO[   62]    OFF
 DO[   63]    OFF
 DO[   64]    OFF
Tick:   230
TB:     1284664019
29-JAN-20 23:09 :10
========================================
 SI[    0]    ON 
 SI[    1]    OFF
 SI[    2]    ON 
 SI[    3]    ON 
 SI[    4]    OFF
 SI[    5]    OFF
 SI[    6]    OFF
 SI[    7]    OFF
 SI[    8]    OFF
 SI[    9]    OFF
 SI[   10]    OFF
 SI[   11]    OFF
 SI[   12]    OFF
 SI[   13]    OFF
 SI[   14]    OFF
 SI[   15]    OFF
 SO[    0]    OFF
 SO[    1]    OFF
 SO[    2]    OFF
 SO[    3]    OFF
 SO[    4]    OFF
 SO[    5]    OFF
 SO[    6]    OFF
 SO[    7]    OFF
 SO[    8]    OFF
 SO[    9]    OFF
 SO[   10]    OFF
 SO[   11]    OFF
 SO[   12]    OFF
 SO[   13]    OFF
 SO[   14]    OFF
 SO[   15]    OFF
 RI[    1]    OFF
 RI[    2]    OFF
 RI[    3]    OFF
 RI[    4]    OFF
 RI[    5]    OFF
 RI[    6]    OFF
 RI[    7]    OFF
 RI[    8]    OFF
 RO[    1]    OFF
 RO[    2]    OFF
 RO[    3]    OFF
 RO[    4]    OFF
 RO[    5]    OFF
 RO[    6]    OFF
 RO[    7]    OFF
 RO[    8]    OFF
 DI[   19]    OFF
 DI[   20]    OFF
 DI[   21]    OFF
 DI[   22]    OFF
 DI[   23]    OFF
 DI[   24]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   41]    OFF
 DI[   42]    OFF
 DI[   51]    OFF
 DI[   52]    OFF
 DI[   53]    OFF
 DI[   54]    OFF
 DI[   55]    OFF
 DI[   56]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   27]    OFF
 DI[   28]    OFF
 DI[   29]    OFF
 DI[   30]    OFF
 DI[   31]    OFF
 DI[   32]    OFF
 DI[   33]    OFF
 DI[   34]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   41]    OFF
 DI[   42]    OFF
 DI[   43]    OFF
 DI[   44]    OFF
 DI[   45]    OFF
 DI[   46]    OFF
 DI[   47]    OFF
 DI[   48]    OFF
 DI[   49]    OFF
 DI[   50]    OFF
 DI[   51]    OFF
 DI[   52]    OFF
 DI[   53]    OFF
 DI[   54]    OFF
 DI[   55]    OFF
 DI[   56]    OFF
 DI[   57]    OFF
 DI[   58]    OFF
 DI[   59]    OFF
 DI[   60]    OFF
 DI[   61]    OFF
 DI[   62]    OFF
 DI[   63]    OFF
 DI[   64]    OFF
 DI[   65]    OFF
 DI[   66]    OFF
 DI[   67]    OFF
 DI[   68]    OFF
 DI[   69]    OFF
 DI[   70]    OFF
 DI[   71]    OFF
 DI[   72]    OFF
 DI[   73]    OFF
 DI[   74]    OFF
 DI[   75]    OFF
 DI[   76]    OFF
 DI[   77]    OFF
 DI[   78]    OFF
 DI[   79]    OFF
 DI[   80]    OFF
Tick:   229
TB:     1284663812
29-JAN-20 23:09 :10
